### ISSUE TITLE
OnPushNotificationReceived is not triggered when Xamarin Forms Android application is killed

### ISSUE THREAD

**Issue by GuidoNeele** [Microsoft/AppCenter-SDK-DotNet#678] opened 2018-05-24 08:50 UTC
### **Description**

OnPushNotificationReceived is not triggered when Xamarin Forms Android application is killed. Notification is received, on tap the application will open, but OnPushNotificationReceived is not called.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Kill app on Android
2. Send push notification
3. Click on push notification
4. App is launched but OnPushNotificationReceived is not called

### **Details**

1. Xamarin.Forms 3.0 on Android
2. .NET standard 2.0. in a separate project
2. AppCenter SDK 1.6.1
4. Android 8.1.0
5. Tested on Nexus 6P
6. NuGet Packages:

FFImageLoading
Microsoft.AppCenter
Microsoft.AppCenter.Analytics
Microsoft.AppCenter.Crashes
Microsoft.AppCenter.Push
Newtonsoft.Json
Plugin.Connectivity
Plugin.CurrentActivity
Plugin.Messaging
Plugin.SecureStorage
Realm
Realm.DataBinding
Square.OkHttp3
Square.OkIO
Syncfusion.Compression.Portable
Syncfusion.Core
Syncfusion.DataSource
Syncfusion.GridCommon
Syncfusion.Pdf.Portable
Syncfusion.SfBusyIndicator
Syncfusion.SfListView
Syncfusion.SfPdfViewer
Syncfusion.SfPullToRefresh
Xamarin.Android.Support.Animated.Vector.Drawable
Xamarin.Android.Support.Annotations
Xamarin.Android.Support.Compat
Xamarin.Android.Support.Core.UI
Xamarin.Android.Support.Core.Utils
Xamarin.Android.Support.CustomTabs
Xamarin.Android.Support.Design
Xamarin.Android.Support.Fragment
Xamarin.Android.Support.Media.Compat
Xamarin.Android.Support.Transition
Xamarin.Android.Support.v4
Xamarin.Android.Support.v7.AppCompat
Xamarin.Android.Support.v7.CardView
Xamarin.Android.Support.v7.MediaRouter
Xamarin.Android.Support.v7.Palette
Xamarin.Android.Support.v7.RecyclerView
Xamarin.Android.Support.Vector.Drawable
Xamarin.Forms.Core
Xamarin.Forms.Platform
Xamarin.Forms.Platform.Android

**Comment by guperrot** [comment] 2018-05-29 22:06
Hi, is the forms activity the first activity of your application or do you have like a splash screen before?

**Comment by GuidoNeele** [comment] 2018-05-30 20:29
There's a splash screen activity before it. Should I move some code from MainActivity to the splash screen?

**Comment by guperrot** [comment] 2018-05-30 20:50
Can you find the code in your splash screen activity when you start the main activity and do something like this to start it?

```
Intent intent = new Intent(this, typeof(MainActivity));
            intent.PutExtras(Intent.Extras); // copy push info from splash to main
            StartActivity(intent);

**Comment by GuidoNeele** [comment] 2018-06-01 14:35
Yep this solved the problem! Thanks.

Intent.Extras needs to be null checked before adding it. Code becomes:

```
Intent intent = new Intent(this, typeof(MainActivity));

if(Intent.Extras != null)
    intent.PutExtras(Intent.Extras); // copy push info from splash to main

StartActivity(intent);
```

**Comment by guperrot** [comment] 2018-06-01 18:33
Glad this solution worked for you. We may add a section to the docs later.

**Comment by Mariuchii** [comment] 2018-06-05 08:44
Hi, i'm having a weird issue with this problem. I've added the extra code in the Splash screen activity yet it's not working as intended...

1. Kill app on Android
2. Send push notification
3. Click on push notification
4. App is launched but OnPushNotificationReceived is not called
5. Let the screen turn off, go to sleep or manually lock the phone/screen while still in App
6. Unlock the screen and OnPushNotificationReceived is now called and works

I want to be able to open a custom notifications page when the user enters the app via clicking on the push notification. It works when app is minimized, but does not work when the App is terminated.

**Comment by GuidoNeele** [comment] 2018-06-05 10:39
What is the LaunchMode of your main activity? You might need to override the OnNewIntent method. See https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-forms#android-additional-steps

**Comment by dhei** [comment] 2018-06-12 19:28
FYI, I followed up with @Mariuchii on support channel. His issue is resolved by following @GuidoNeele's [comment](https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/678#issuecomment-394663186).

**Closed by dhei** 2018-06-12 19:28 UTC
Labels: support
