### ISSUE TITLE
android.os.RemoteException from com.microsoft.appcenter.crashes.Crashes.saveUncaughtException

### ISSUE THREAD

**Issue by tbalcom** [microsoft/appcenter-sdk-dotnet#1528] opened 2021-05-25 16:42 UTC
### **Description**

I received a report from AppCenter about an internal crash in AppCenter with the following stack trace:

```
com.microsoft.appcenter.crashes.Crashes.saveUncaughtException
Crashes.java, line 1151
android.os.Parcel.createException Parcel.java:1970
android.os.Parcel.readException Parcel.java:1934
android.os.Parcel.readException Parcel.java:1884
android.app.IActivityManager$Stub$Proxy.reportSizeConfigurations IActivityManager.java:8630
android.app.ActivityThread.reportSizeConfigurations ActivityThread.java:3327
android.app.ActivityThread.handleLaunchActivity ActivityThread.java:3286
android.app.servertransaction.LaunchActivityItem.execute LaunchActivityItem.java:78
android.app.servertransaction.TransactionExecutor.executeCallbacks TransactionExecutor.java:108
android.app.servertransaction.TransactionExecutor.execute TransactionExecutor.java:68
android.app.ActivityThread$H.handleMessage ActivityThread.java:1970
android.os.Handler.dispatchMessage Handler.java:106
android.os.Looper.loop Looper.java:214
android.app.ActivityThread.main ActivityThread.java:7156
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:494
com.android.internal.os.ZygoteInit.main ZygoteInit.java:975
```

It may have something to do with no Internet connection. It happened 2s after the app started.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Android
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET Standard 2.1.
2. Which SDK version are you using?
    - 4.2.0
4. Which OS version did you experience the issue on?
    - Android 9
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Samsung Galaxy J7 physical device.
6. What third party libraries are you using? <!-- For .NET, you can find these in your .csproj, package.json, or package.config files 
    - FluentValidation 10.1.0
    - Microsoft.AppCenter.Analytics 4.2.0
    - Microsoft.AppCenter.Crashes 4.2.0
    - Microsoft.AppCenter.Distribute 4.2.0
    - MvvmCross 7.1.2
    - MvvmCross.Plugin.Messenger 7.1.2
    - MvvmCross.Plugin.ResxLocalization 7.1.2
    - Newtonsoft.Json 13.0.1
    - Polly Version=7.2.2
    - sqlite-net-pcl 1.7.335
    - Xamarin.Essentials 1.6.1
    - ZXing.Net.Mobile 3.1.0-beta2
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
    - I cannot reliably reproduce this.

**Comment by AnastasiaKubova** [comment] 2021-05-26 09:19
Hi, @tbalcom ! Thanks for getting in touch with us! Could you please share reproducing steps or [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/android#adjust-the-log-level) with reproducing this issue? I checked sending crash reports after the application starts without the Internet and for me all works as expected.

**Comment by tbalcom** [comment] 2021-05-26 14:09
I mentioned I'm not able to reproduce this. I only have the report in AppCenter.

**Comment by AnastasiaKubova** [comment] 2021-05-27 06:47
Unfortunately without additional info it difficult to figure out what exactly goes wrong. If you have a chance to share additional info (logs or repo steps) it will help us understand this issue.

**Comment by DmitriyKirakosyan** [comment] 2021-05-27 10:40
Hi @tbalcom 

This is likely not an SDK related crash. You app crashes and then the SDK crashes with the same reason.
The reason here could be lack of device memory or disk space.
Try to review the memory usage in your app and make sure that it doesn't have any big allocations on start.

Similar case: https://github.com/microsoft/appcenter-sdk-dotnet/issues/1392

**Comment by AnastasiaKubova** [comment] 2021-06-02 05:49
We haven’t heard from you in a while so I’m closing this issue but free to reopen this issue if you have additional questions.

**Closed by AnastasiaKubova** 2021-06-02 05:49 UTC
Labels: support

**Comment by Bowman74** [comment] 2022-02-14 19:17
@DmitriyKirakosyan 
I also got this and as you suspected it appears to be a resource issue where the app runs out of resources and that kills the app. That is to say this isn't a problem with the AppCenter SDK per se.

When I look at the individual devices this is what is in the raw trace:

Version Name: 12.65.7607
Android: 11
Android Build: RP1A.200720.012
Manufacturer: samsung
Model: SM-A526U
CrashReporter Key: a1344ed6-1a6d-4b59-b411-e548ddf48cc7
Start Date: 2022-02-09T16:59:15.379Z
Date: 2022-02-13T15:19:18.489Z

java.lang.IllegalStateException: Too many receivers, total of 1000, registered for pid: 13682, callerPackage: XXX.XXX.XXX
  at android.os.Parcel.createExceptionOrNull(Parcel.java:2393)
  at android.os.Parcel.createException(Parcel.java:2369)
  at android.os.Parcel.readException(Parcel.java:2352)
  at android.os.Parcel.readException(Parcel.java:2294)
  at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6381)
  at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1696)
  at android.app.ContextImpl.registerReceiver(ContextImpl.java:1650)
  at android.app.ContextImpl.registerReceiver(ContextImpl.java:1638)
  at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:686)
  at com.google.android.gms.common.GoogleApiAvailability.zae(Unknown Source:17)
  at com.google.android.gms.common.api.internal.zaaz.zac(Unknown Source:36)
  at com.google.android.gms.common.api.internal.zaag.zah(Unknown Source:12)
  at com.google.android.gms.common.api.internal.zabd.onConnectionSuspended(Unknown Source:7)
  at com.google.android.gms.common.api.internal.zas.onConnectionSuspended(Unknown Source:4)
  at com.google.android.gms.common.internal.zah.onConnectionSuspended(Unknown Source:2)
  at com.google.android.gms.common.internal.zzb.handleMessage(Unknown Source:220)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:246)
  at android.app.ActivityThread.main(ActivityThread.java:8587)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
  Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:18572)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2611)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3628)
	at android.os.Binder.execTransactInternal(Binder.java:1195)
	at android.os.Binder.execTransact(Binder.java:1159)


Thread 2:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:1736)
2   java.lang.Thread.getAllStackTraces(Thread.java:1812)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException
4   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException
5   com.microsoft.appcenter.crashes.UncaughtExceptionHandler.uncaughtException
6   org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-TrichromeWebViewGoogle.aab-stable-428014133:6)
7   java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
8   java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
9   java.lang.Thread.dispatchUncaughtException(Thread.java:2203)

Thread 647:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:442)
2   java.lang.Object.wait(Object.java:568)
3   java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:217)
4   java.lang.Daemons$Daemon.run(Daemons.java:139)
5   java.lang.Thread.run(Thread.java:923)

Thread 648:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:442)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
4   java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:273)
5   java.lang.Daemons$Daemon.run(Daemons.java:139)
6   java.lang.Thread.run(Thread.java:923)

Thread 649:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:442)
2   java.lang.Object.wait(Object.java:568)
3   java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:341)
4   java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:321)
5   java.lang.Daemons$Daemon.run(Daemons.java:139)
6   java.lang.Thread.run(Thread.java:923)

Thread 668:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 670:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 671:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 674:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 682:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:325)
2   com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:42)
3   com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:288)

Thread 737:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 2721:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 2723:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 2726:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 2728:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:442)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
4   CM.run(chromium-TrichromeWebViewGoogle.aab-stable-428014133:2)

Thread 2732:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 4663:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)
3   android.os.HandlerThread.run(HandlerThread.java:67)

Thread 6679:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 6685:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 6690:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 6693:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 6699:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 6704:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 6748:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 6756:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 9992:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 9999:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 10003:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 10006:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 10012:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 10016:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 11521:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 11590:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 11978:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 12221:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 13248:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:335)
2   android.os.Looper.loop(Looper.java:206)

Thread 13414:
0   sun.misc.Unsafe.park(Unsafe.java:-2)
1   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
2   java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:459)
3   java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
4   java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:920)
5   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
6   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
7   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
8   java.lang.Thread.run(Thread.java:923)
