### ISSUE TITLE
[Distribute] App does not receive new update notification [since v3.0.0]

### ISSUE THREAD

**Issue by rdeveen** [microsoft/appcenter-sdk-dotnet#1342] opened 2020-02-28 13:10 UTC
### **Description**
Since version update to Microsoft.AppCenter.Distribute version 3.0.0 the notification of a new version does not popup on app launch.

### **Repro Steps**
1. Update Microsoft.AppCenter and Microsoft.AppCenter.Distribute to version 3.0.0
2. Distribute new version of the app to AppCenter.
3. Update app on phone.
4. Distribute new version of the app to AppCenter.
5. No update on phone.

### **Details**
Xamarin.Forms Android and iOS.
SDK version 3.0.0

Reinstall version 2.6.4 of the SDK and the updates are working.

**Comment by Jamminroot** [comment] 2020-02-28 13:48
Hey, @rdeveen, thanks for getting in touch.
Can you collect verbose logs of when you launch application (when new update is supposed to be published on portal)? You would have to adjust LogLevel to verbose for that.
Also, are updates checked on same update track where new version is distributed? In other words: if you are checking for updates in public distribution group, is new version published to the same distribution group?

**Comment by rdeveen** [comment] 2020-02-28 14:06
> Also, are updates checked on same update track where new version is distributed? In other words: if you are checking for updates in public distribution group, is new version published to the same distribution group?

Correct, the updates are on the same update track.

**Comment by Jamminroot** [comment] 2020-02-28 14:17
Ok, I see. Can you please send us verbose logs?
For that you have to put this line right before calling `AppCenter.Start()`:
```csharp
AppCenter.LogLevel = LogLevel.Verbose;
```

**Comment by rdeveen** [comment] 2020-02-28 15:27
V/AppCenter(32094): HTTP response status=404 payload=**{"code":"not_found","message":"Error: App Version not found"}**
 E/AppCenterDistribute(32094): Failed to check latest release (delete setup state)
 E/AppCenterDistribute(32094): com.microsoft.appcenter.http.HttpException: 404 - **{"code":"not_found","message":"Error: App Version not found"}**
 E/AppCenterDistribute(32094): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:265)
 E/AppCenterDistribute(32094): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:279)
 E/AppCenterDistribute(32094): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:48)
 E/AppCenterDistribute(32094): 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
 E/AppCenterDistribute(32094): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 E/AppCenterDistribute(32094): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 E/AppCenterDistribute(32094): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 E/AppCenterDistribute(32094): 	at java.lang.Thread.run(Thread.java:761)


 D/AppCenterDistribute(32094): Resume distribute workflow...
 D/AppCenterAnalytics(32094): onActivityResumed
 D/AppCenterAnalytics(32094): noLogSentForLong=false wasBackgroundForLong=false
 W/AppCenter(32094): Try #1 failed and will be retried in 5394 ms
 W/AppCenter(32094): j**ava.net.SocketTimeoutException: SSL handshake timed out**
 W/AppCenter(32094): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
 W/AppCenter(32094): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
 W/AppCenter(32094): 	at com.android.okhttp.Connection.connectTls(Connection.java:235)
 W/AppCenter(32094): 	at com.android.okhttp.Connection.connectSocket(Connection.java:199)
 W/AppCenter(32094): 	at com.android.okhttp.Connection.connect(Connection.java:172)
 W/AppCenter(32094): 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
 W/AppCenter(32094): 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
 W/AppCenter(32094): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
 W/AppCenter(32094): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
 W/AppCenter(32094): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
 W/AppCenter(32094): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
 W/AppCenter(32094): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
 W/AppCenter(32094): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
 W/AppCenter(32094): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
 W/AppCenter(32094): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:226)
 W/AppCenter(32094): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:279)
 W/AppCenter(32094): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:48)
 W/AppCenter(32094): 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
 W/AppCenter(32094): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 W/AppCenter(32094): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 W/AppCenter(32094): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 W/AppCenter(32094): 	at java.lang.Thread.run(Thread.java:761)
 W/AppCenter(32094): **Try #1 failed and will be retried in 5482 ms
 W/AppCenter(32094): java.net.SocketTimeoutException: SSL handshake timed out**
 W/AppCenter(32094): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
 W/AppCenter(32094): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
 W/AppCenter(32094): 	at com.android.okhttp.Connection.connectTls(Connection.java:235)
 W/AppCenter(32094): 	at com.android.okhttp.Connection.connectSocket(Connection.java:199)
 W/AppCenter(32094): 	at com.android.okhttp.Connection.connect(Connection.java:172)
 W/AppCenter(32094): 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
 W/AppCenter(32094): 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
 W/AppCenter(32094): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
 W/AppCenter(32094): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
 W/AppCenter(32094): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
 W/AppCenter(32094): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
 W/AppCenter(32094): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
 W/AppCenter(32094): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
 W/AppCenter(32094): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
 W/AppCenter(32094): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doHttpCall(DefaultHttpClientCallTask.java:226)
 W/AppCenter(32094): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:279)
 W/AppCenter(32094): 	at com.microsoft.appcenter.http.DefaultHttpClientCallTask.doInBackground(DefaultHttpClientCallTask.java:48)
 W/AppCenter(32094): 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
 W/AppCenter(32094): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 W/AppCenter(32094): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 W/AppCenter(32094): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 W/AppCenter(32094): 	at java.lang.Thread.run(Thread.java:761)
 W/AppCenter(32094): 	Suppressed: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x8c6f4300: I/O error during system call, Connection reset by peer

**Comment by Jamminroot** [comment] 2020-02-28 15:44
Thanks.
Is the version you are checking updates FROM (aka currently installed) published on the portal (and distributed to same group)? Sorry for not asking this in previous message.
If so, some further investigation might be required. For that I'd suggest you open a ticket in intercom - for that, press chat button on the portal in the bottom-right corner.

**Comment by ilyashumihin** [comment] 2020-03-03 14:25
Hi, @rdeveen!
I can't reproduce this problem by your steps. Can you please add a bit more info? Which groups did you use on each step? I mean you update from public->public->public or private->private->private or perhaps other cases?

**Comment by rdeveen** [comment] 2020-03-03 15:48
Hi @ilyashumihin, thanks for the support. The update is private->private->private. 

Create app version 1.0.0 with SDK version 2.6.4 and push to AppCenter, start the app (verssion 1.0.0) and it's opening the browser to register to AppCenter.
Update app to version 1.0.1 with SDK version 2.6.4, push to AppCenter, start the app (version 1.0.0) and the update message appears for version 1.0.1. _So fare so good._

Update app to version 1.0.2 and update SDK to version 3.0.0, push to AppCenter, start the app (version 1.0.1), **no update message**.
Manual install version 1.0.2 from AppCenter, start the app, **nothing happens**.
Update app to version 1.0.3, push to AppCenter, start the app (version 1.0.2), **no update message**.

Extra:
Update app to version 1.0.4 and downgrade SDK to version 2.6.4, push to AppCenter, start the app,   it's opening the browser to register to AppCenter.
Update app to version 1.0.5, push to AppCenter, start the app (version 1.0.4) and the update message appears for version 1.0.5. Thats good but with the old SDK version.

**Comment by owlstronaut** [comment] 2020-03-04 01:00
Hello @rdeveen, I'd like to make sure that you are adding `Distribute.UpdateTrack = UpdateTrack.Private;` to your code before AppCenter.Start. As a behavior change in 3.0.0, we now default to public tracks in distribute without an explicit call before start. https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#use-private-distribution-group

**Comment by annakocheshkova** [comment] 2020-03-11 08:55
Hi @rdeveen, do you have any updates? I'm closing this issue, feel free to re-open if you have any more info and/or questions.

**Closed by annakocheshkova** 2020-03-11 08:55 UTC
Labels: support
