### ISSUE TITLE
Harmless warning: The referenced component 'Microsoft.AppCenter.Crashes.dll' could not be found

### ISSUE THREAD

**Issue by myokeeh** [Microsoft/AppCenter-SDK-DotNet#543] opened 2017-12-09 04:40 UTC
I can't seem to get rid of this error on projects referencing `Microsoft.AppCenter.Crashes`. Cleared NuGet cache, uninstalled, reinstalled the package, but it keeps coming back.

> The referenced component 'Microsoft.AppCenter.Crashes.dll' could not be found

**Comment by achocron** [comment] 2017-12-11 17:59
Strange, what platform are you building the application for? It won't work for AnyCpu.

**Comment by guperrot** [comment] 2017-12-13 01:12
If you are seeing this warning only in Visual Studio only in UWP apps but have no problem building, you can ignore it. We will try to remove the warning on our side.

Here is the warning that is harmless:

![capture](https://user-images.githubusercontent.com/623672/33916803-9ba1a86a-df5f-11e7-8e35-63d1cb0c69e7.PNG)

Please let us know if you are referring to a different issue.

**Comment by VagueGit** [comment] 2018-03-08 06:25
We are getting this issue with UWP targetting 16299 using AppCenter.Crashes 1.5. You've closed this issue. Does that mean it isn't going to be fixed?

**Comment by VagueGit** [comment] 2018-03-08 20:28
It's only harmless if you know it's harmless. We wasted time trying to fix our project because of this warning.

**Comment by guperrot** [comment] 2018-03-08 21:22
Hi, we are sorry for the inconvenience, we just have not found a solution yet.

**Comment by dhei** [comment] 2018-03-09 23:26
Based on my investigation, this warning message ("The referenced component 'Microsoft.AppCenter.Crashes.dll' could not be found") is not present in target platform `Windows 10 Anniversary Edition 10.0.14393.0`. It is only present in later versions--`Windows 10 Creators Update 10.0.15063` and `Windows 10 Fall Creators Update 10.0.16299`. Unfortunately I was not able to find the root cause.

**Comment by asierpn** [comment] 2018-05-17 12:33
I get the same issue, I think that something is wrong with Microsoft.AppCenter.Crashes.targets, maybe the HintPath of this ItemGroup:

`    <ItemGroup Condition=" ('$(TargetPlatformIdentifier)' == 'UAP') AND ('$(mc-crashes-IsCorrectArch)' == 'true')">
      <Reference Include="Microsoft.AppCenter.Crashes.dll">
        <HintPath>$(mc-crashes-ArchDir)\lib\uap10.0\Microsoft.AppCenter.Crashes.dll</HintPath>
      </Reference>
    </ItemGroup>`

**Comment by guperrot** [comment] 2018-06-20 00:11
@asierpn we removed that line from targets as part of the 1.7.0 release. However the warning will persist if just updating nuget in the app. To resolve the warning a full git clean might be necessary with visual studio being closed.

**Closed** 2018-06-20 00:13 UTC
Labels: bug

**Comment by usri** [comment] 2018-06-25 10:51
I am still facing Severity	Code	Description	Project	File	Line	Suppression State
Error		Detected package downgrade: Microsoft.AppCenter from 1.7.0 to 1.5.0. Reference the package directly from the project to select a different version. 
 ContosoFieldService.Core -> Microsoft.AppCenter.Crashes 1.7.0 -> Microsoft.AppCenter (>= 1.7.0) 
 ContosoFieldService.Core -> Microsoft.AppCenter (>= 1.5.0)			0	

Also, this applies to the following packages while trying to update the latest stable version:

Microsoft.AppCenter.Analytics
Microsoft.AppCenter.Push

**Comment by guperrot** [comment] 2018-06-25 18:15
Hi, this is a different issue, your are mixing and matching versions of our nugets. All packages depends on the core of the same version: Microsoft.AppCenter and the error is telling you are trying to downgrade version.

If you update all packages to the same version it will fix this issue.
