### ISSUE TITLE
Strong name signing NuGet packages

### ISSUE THREAD

**Issue by Suplanus** [microsoft/appcenter-sdk-dotnet#1092] opened 2019-08-19 13:31 UTC
In some cases I am only able to use strong name signed DLLs.

I also think it should be standard @ Microsoft:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md

**Comment by EatonZ** [comment] 2019-09-23 21:51
+1 for this. Had to sign them manually as a workaround.

**Comment by EatonZ** [comment] 2019-09-24 00:11
The [sqlite-net project](https://github.com/praeclarum/sqlite-net) will also need to strong name sign their dll for everything to work (everything silently fails in the background if not signed), [link to issue](https://github.com/praeclarum/sqlite-net/issues/367).

**Comment by NunoPeixotoPrimavera** [comment] 2019-10-03 22:21
Hi, does anyone have the assemblies and dependencies signed and working?

**Comment by NunoPeixotoPrimavera** [comment] 2019-10-04 13:48
> The [sqlite-net project](https://github.com/praeclarum/sqlite-net) will also need to strong name sign their dll for everything to work (everything silently fails in the background if not signed), [link to issue](https://github.com/praeclarum/sqlite-net/issues/367).

Hi EatonZ, do you have de assemblies signed and working. Can you send me the dlls?
Or create an attachment on this issue.

**Comment by EatonZ** [comment] 2019-10-04 16:44
I've attached strong named assemblies for the latest versions. What you want to do is go into your packages folder next to your project's .sln file and replace the dlls in each package's net45 folder (except sqlite-net, replace the one in netstandard2.0).

Any time these NuGet packages are updated or redownloaded/restored, you'll need to do this again.

How I did it: Add [this package](https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/) to your project and build it. It'll strong name sign any unsigned dlls. Then, replace them in the packages folder, then remove Brutal.Dev.StrongNameSigner from your project.

[Strong Named DLLs.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/3691485/Strong.Named.DLLs.zip)

**Comment by NunoPeixotoPrimavera** [comment] 2019-10-04 19:58
Thanks a lot Eaton.

**Comment by EatonZ** [comment] 2019-12-06 17:50
[sqlite-net-pcl is being removed](https://github.com/microsoft/appcenter-sdk-dotnet/pull/1246) so hopefully this will get resolved next.👍

**Comment by 304NotModified** [comment] 2019-12-06 21:36
All Microsoft dlls are strong named? Why not this one?

**Comment by jozefizso** [comment] 2020-03-05 20:25
When this will be fixed?

**Comment by MatkovIvan** [comment] 2020-05-08 12:20
Hi there, I've just realized that we have two opened issues to track strong named signing. This one was opened first, but another one was landed on common repository, where we're tracking feature requests. So, I'm going to mark this thread as duplicate of https://github.com/microsoft/appcenter/issues/1321 and close it. Let's continue track this request there.
Thanks

**Closed by MatkovIvan** 2020-05-08 12:20 UTC
Labels: feature request
