### ISSUE TITLE
"Library e_sqlite3 not found" on .Net Framework 4.7

### ISSUE THREAD

**Issue by alexagev** [microsoft/appcenter-sdk-dotnet#1716] opened 2022-12-10 10:16 UTC
### **Description**

All is done according to you get started guide. But it's not working

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create new WPF application 
2. Select .NET 4.7.2 Framework
3. Open the console in [Visual Studio](https://visualstudio.microsoft.com/vs/). To do this, choose Tools > NuGet Package Manager > Package Manager Console.
4. Install-Package Microsoft.AppCenter.Analytics
5. Install-Package Microsoft.AppCenter.Crashes
6.  Add code  AppCenter.Start("{Your App Secret}", typeof(Analytics), typeof(Crashes));
7. Launch app

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - e.g. Xamarin.Forms on all 3 platforms (Android, iOS and UWP).Win
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile? 4.7.2
    - e.g. .NET standard 2.0.
2. Which SDK version are you using? automatically is installed  5.0.1
    - e.g. 1.5.0 
8. Which OS version did you experience the issue on? Win 10
    - e.g. iOS 11, Android 8.1.0 Win 10
9. What device version did you see this error on?  Were you using an emulator or a physical device? PC
    - e.g. iPhone X physical device, Google Pixel 2 emulator
10. What third party libraries are you using? Non
11. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

Result:

2022-12-10 13:12:56.342 [AppCenter] ERROR: Failed to initialize sqlite3 provider.
System.Exception: Library e_sqlite3 not found
plat: win
suffix: DLL
possibilities (2):
    1) D:\Projects\test\testAnalysic2\bin\Debug\runtimes\win-x86\native\e_sqlite3.dll
    2) D:\Projects\test\testAnalysic2\bin\Debug\e_sqlite3.dll
win TryLoad: D:\Projects\test\testAnalysic2\bin\Debug\runtimes\win-x86\native\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
win TryLoad: D:\Projects\test\testAnalysic2\bin\Debug\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
NOT FOUND

   at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
   at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.Init()
   at Microsoft.AppCenter.Storage.StorageAdapter..cctor()
'testAnalysic2.exe' (CLR v4.0.30319: testAnalysic2.exe): Loaded 'D:\Projects\test\testAnalysic2\bin\Debug\System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2022-12-10 13:12:56.377 [AppCenter] ERROR: An error occurred while initializing storage
System.Exception: You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().
   at SQLitePCL.raw.get_Provider()
   at SQLitePCL.raw.sqlite3_open(utf8z filename, sqlite3& db)
   at SQLitePCL.raw.sqlite3_open(String filename, sqlite3& db)
   at Microsoft.AppCenter.Storage.StorageAdapter.Initialize(String databasePath)
   at Microsoft.AppCenter.Storage.Storage.InitializeDatabase()
2022-12-10 13:12:56.381 [AppCenter] ERROR: The storage operation failed
Microsoft.AppCenter.Storage.StorageException: The database wasn't initialized.
   at Microsoft.AppCenter.Storage.StorageAdapter.ExecuteSelectionSqlQuery(String query, IList`1 args)
   at Microsoft.AppCenter.Storage.StorageAdapter.Count(String tableName, String columnName, Object value)
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass19_0.<CountLogsAsync>b__0()
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
2022-12-10 13:12:56.384 [AppCenter] ERROR: Failed to initialize the log count: The database wasn't initialized.
2022-12-10 13:12:56.387 [AppCenter] ERROR: The storage operation failed
Microsoft.AppCenter.Storage.StorageException: The storage operation failed ---> Microsoft.AppCenter.Storage.StorageException: The database wasn't initialized.
   at Microsoft.AppCenter.Storage.StorageAdapter.SetMaxStorageSize(Int64 sizeInBytes)
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass23_0.<SetMaxStorageSizeAsync>b__0()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass23_0.<SetMaxStorageSizeAsync>b__0()
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
2022-12-10 13:12:56.388 [AppCenter] ERROR: The storage operation failed
Microsoft.AppCenter.Storage.StorageException: The database wasn't initialized.
   at Microsoft.AppCenter.Storage.StorageAdapter.ExecuteSelectionSqlQuery(String query, IList`1 args)
   at Microsoft.AppCenter.Storage.StorageAdapter.Count(String tableName, String columnName, Object value)
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass19_0.<CountLogsAsync>b__0()
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
2022-12-10 13:12:56.389 [AppCenter] ERROR: Failed to initialize the log count: The database wasn't initialized.
2022-12-10 13:12:56.396 [AppCenter] ERROR: The storage operation failed
Microsoft.AppCenter.Storage.StorageException: The database wasn't initialized.
   at Microsoft.AppCenter.Storage.StorageAdapter.ExecuteSelectionSqlQuery(String query, IList`1 args)
   at Microsoft.AppCenter.Storage.StorageAdapter.Count(String tableName, String columnName, Object value)
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass19_0.<CountLogsAsync>b__0()
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
'testAnalysic2.exe' (CLR v4.0.30319: testAnalysic2.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2022-12-10 13:12:56.397 [AppCenter] ERROR: Failed to initialize the log count: The database wasn't initialized.

**Comment by IlyaBausovAkvelon** [comment] 2022-12-12 08:09
Thank you @alexagev for reporting this issue. Let us take some time to investigate this.

**Comment by aleksandr-dorofeev** [comment] 2022-12-16 15:37
@alexagev, sorry for the delayed answer.
I'm marking it as a bug, we created a work item in our internal dashboard.

**Comment by MikhailSuendukov** [comment] 2023-01-05 13:39
@alexagev actually it looks like a duplicate of https://github.com/microsoft/appcenter-sdk-dotnet/issues/1722/. You can track the status of the solution to this issue in the mentioned issue.

**Comment by alexagev** [comment] 2023-01-07 23:49
So you have a bug in your project. You know about it and you don't want to
solve it? That ticket has no solution either. Now I only know that there
are more people with this bug. But it doesn't help me
And that is a demo of your solution and it doesn't work.

**Comment by DmitriyKirakosyan** [comment] 2023-01-09 06:10
@alexagev , we have this bug on our board and it is with a high priority, will start working on it asap. Meanwhile, contribution is always very welcome!

**Comment by smasherprog** [comment] 2023-01-16 17:17
This is a better approach if you need sqllite in the application instead of the current nuget packages

https://github.com/praeclarum/sqlite-net

**Comment by Vechkanov** [comment] 2023-02-02 09:32
@alexagev @massimotomasi
Sorry for a long research time. 
Please try this approach: 

- Clean your Solution in the Visual Studio. (Build -> Clean Solution)
- Remove your build folders (bin and obj), to make sure everything is clean.
- In Visual Studio, right-click on the packages.config file, and choose "Migrate packages.config to PackageReference".
- Rebuild solution (Build -> Rebuild Solution).
- Run solution

This steps helps me, with the sample app you provided. 

The issue is caused not by AppCenter but by a library that is a dependency of the AppCenter.
https://github.com/ericsink/SQLitePCL.raw/issues/537
 
 I am closing this ticket as not AppCenter SDK issue. 
 Feel free to comment or reopen if you still face this problem.

**Closed by Vechkanov** 2023-02-02 09:32 UTC
Labels: bug

**Comment by alexagev** [comment] 2023-02-02 11:15
Just querious , you want to tell me that your solution is not working from
the box, and it's  not an AppCenter SDK issue.I need to do some magic and
it's normal.
And you will continue to use that library with problem dependencies. And
you won't do anything else. Am I right?

**Comment by Vechkanov** [comment] 2023-02-02 11:43
Thank you for you response. 
The actions I suggest you is just a migration to a newer nuget managing system and cleaning the app. You can read about Package Reference [here](https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference).
Did this help you with a problem or it is still continues? 
As about changing SQLite library, we are not planning to do it for now. I asked SQLitePCL.raw team, are they planning to support packages.config or not. You can comment or subscribe to the question for SQLitePCL.raw, with a link I provided above.

**Comment by alexagev** [comment] 2023-02-02 11:46
Unfortunately all this took too long time and our company decided to
continue with google analytics. It doesn't require any additional installed
libraries and work without any problems

**Comment by Kalyxt** [comment] 2023-02-02 12:25
Thanks for your time, but its not working for me anyway. I created new .NET framework project, installed App center (all of them) via nuget package and then migrated SQLitePCL libraries to PackageReference. I have `Crashes.GenerateTestCrash();` on Form Load but there are no errors on App Center site. Could you please provide sample where it works ?

**Comment by smasherprog** [comment] 2023-02-02 15:01
Basically, their response is that we dont want to fix it. So, appcenter is completely broken for net framework applications.

**Comment by JeffriPraveen** [comment] 2023-02-06 10:16
Still facing the same

       2023-02-06 15:44:24.598 [AppCenter] ERROR: Failed to initialize sqlite3 provider.
System.Exception: Library e_sqlite3 not found
plat: win
suffix: DLL
possibilities (2):
    1) D:\Appcenter_Hv\hv-windows-app\HV_DESKTOP_APP\bin\x86\Debug\runtimes\win-x86\native\e_sqlite3.dll
    2) D:\Appcenter_Hv\hv-windows-app\HV_DESKTOP_APP\bin\x86\Debug\e_sqlite3.dll
win TryLoad: D:\Appcenter_Hv\hv-windows-app\HV_DESKTOP_APP\bin\x86\Debug\runtimes\win-x86\native\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
win TryLoad: D:\Appcenter_Hv\hv-windows-app\HV_DESKTOP_APP\bin\x86\Debug\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
NOT FOUND

   at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
   at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.Init()
   at Microsoft.AppCenter.Storage.StorageAdapter..cctor()
2023-02-06 15:44:24.599 [AppCenter] DEBUG: Creating database at: C:\Users\dell\AppData\Local\Microsoft\AppCenter\9e5f97c9-64de-43e1-8d81-9c78c6a01807\Logs.db
2023-02-06 15:44:24.601 [AppCenter] DEBUG: AddChannel(core)
'HV_DESKTOP_APP.exe' (CLR v4.0.30319: HV_DESKTOP_APP.exe): Loaded 'D:\Appcenter_Hv\hv-windows-app\HV_DESKTOP_APP\bin\x86\Debug\System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2023-02-06 15:44:24.617 [AppCenter] ERROR: An error occurred while initializing storage
System.Exception: You need to call SQLitePCL.raw.SetProvider().  If you are using a bundle package, this is done by calling SQLitePCL.Batteries.Init().
   at SQLitePCL.raw.get_Provider()
   at SQLitePCL.raw.sqlite3_open(utf8z filename, sqlite3& db)
   at SQLitePCL.raw.sqlite3_open(String filename, sqlite3& db)
   at Microsoft.AppCenter.Storage.StorageAdapter.Initialize(String databasePath)
   at Microsoft.AppCenter.Storage.Storage.InitializeDatabase()
2023-02-06 15:44:24.618 [AppCenter] INFO: App Center SDK configured successfully.
2023-02-06 15:44:24.620 [AppCenter] ERROR: The storage operation failed
Microsoft.AppCenter.Storage.StorageException: The database wasn't initialized.
   at Microsoft.AppCenter.Storage.StorageAdapter.ExecuteSelectionSqlQuery(String query, IList`1 args)
   at Microsoft.AppCenter.Storage.StorageAdapter.Count(String tableName, String columnName, Object value)
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass19_0.<CountLogsAsync>b__0()
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
2023-02-06 15:44:24.621 [AppCenter] DEBUG: AddChannel(analytics)
2023-02-06 15:44:24.622 [AppCenter] ERROR: Failed to initialize the log count: The database wasn't initialized.
2023-02-06 15:44:24.623 [AppCenter] DEBUG: CheckPendingLogsInternal(core) pending log count: 0
2023-02-06 15:44:24.624 [AppCenter] DEBUG: Set max storage size.
2023-02-06 15:44:24.625 [AppCenterAnalytics] DEBUG: SessionTracker.Resume
2023-02-06 15:44:24.626 [AppCenter] ERROR: The storage operation failed
Microsoft.AppCenter.Storage.StorageException: The storage operation failed ---> Microsoft.AppCenter.Storage.StorageException: The database wasn't initialized.
   at Microsoft.AppCenter.Storage.StorageAdapter.SetMaxStorageSize(Int64 sizeInBytes)
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass23_0.<SetMaxStorageSizeAsync>b__0()
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass23_0.<SetMaxStorageSizeAsync>b__0()
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
2023-02-06 15:44:24.626 [AppCenter] ERROR: The storage operation failed
Microsoft.AppCenter.Storage.StorageException: The database wasn't initialized.
   at Microsoft.AppCenter.Storage.StorageAdapter.ExecuteSelectionSqlQuery(String query, IList`1 args)
   at Microsoft.AppCenter.Storage.StorageAdapter.Count(String tableName, String columnName, Object value)
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass19_0.<CountLogsAsync>b__0()
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
2023-02-06 15:44:24.627 [AppCenter] ERROR: Failed to initialize the log count: The database wasn't initialized.
2023-02-06 15:44:24.627 [AppCenter] DEBUG: CheckPendingLogsInternal(analytics) pending log count: 0
2023-02-06 15:44:24.631 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'analytics'
2023-02-06 15:44:24.634 [AppCenter] INFO: 'Analytics' service started.
'HV_DESKTOP_APP.exe' (CLR v4.0.30319: HV_DESKTOP_APP.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2023-02-06 15:44:24.640 [AppCenter] DEBUG: AddChannel(crashes)
2023-02-06 15:44:24.643 [AppCenter] ERROR: The storage operation failed
Microsoft.AppCenter.Storage.StorageException: The database wasn't initialized.
   at Microsoft.AppCenter.Storage.StorageAdapter.ExecuteSelectionSqlQuery(String query, IList`1 args)
   at Microsoft.AppCenter.Storage.StorageAdapter.Count(String tableName, String columnName, Object value)
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass19_0.<CountLogsAsync>b__0()
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
2023-02-06 15:44:24.644 [AppCenter] ERROR: Failed to initialize the log count: The database wasn't initialized.
2023-02-06 15:44:24.644 [AppCenter] DEBUG: CheckPendingLogsInternal(crashes) pending log count: 0
2023-02-06 15:44:24.646 [AppCenter] INFO: 'Crashes' service started.
2023-02-06 15:44:24.647 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'core'
2023-02-06 15:44:24.652 [AppCenterCrashes] DEBUG: Process pending error file d0e76157-dc37-4455-bd46-87dd26981b33.json
'HV_DESKTOP_APP.exe' (CLR v4.0.30319: HV_DESKTOP_APP.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'HV_DESKTOP_APP.exe' (CLR v4.0.30319: HV_DESKTOP_APP.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'HV_DESKTOP_APP.exe' (CLR v4.0.30319: HV_DESKTOP_APP.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2023-02-06 15:44:24.705 [AppCenterCrashes] DEBUG: ShouldAwaitUserConfirmation returned false or is not implemented, will send logs.
2023-02-06 15:44:24.707 [AppCenter] DEBUG: Invoke EnqueuingLog event for channel 'crashes'
2023-02-06 15:44:24.709 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'crashes'
2023-02-06 15:44:24.717 [AppCenterCrashes] INFO: Deleting error log file d0e76157-dc37-4455-bd46-87dd26981b33.json.
2023-02-06 15:44:24.718 [AppCenterCrashes] DEBUG: Crashes.GetErrorAttachments returned null; no additional information will be attached to log: d0e76157-dc37-4455-bd46-87dd26981b33.
2023-02-06 15:44:24.729 [AppCenter] ERROR: Could not get max storage size.
2023-02-06 15:44:24.732 [AppCenter] ERROR: Error persisting log
Microsoft.AppCenter.Storage.StorageException: Failed to store a log to the database.
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass31_0.<AddTaskToQueue>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AppCenter.Channel.Channel.<PersistLogAsync>d__41.MoveNext()
'HV_DESKTOP_APP.exe' (CLR v4.0.30319: HV_DESKTOP_APP.exe): Loaded 'D:\Appcenter_Hv\hv-windows-app\HV_DESKTOP_APP\bin\x86\Debug\Notifications.Wpf.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'HV_DESKTOP_APP.exe' (CLR v4.0.30319: HV_DESKTOP_APP.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'HV_DESKTOP_APP.exe' (CLR v4.0.30319: HV_DESKTOP_APP.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Deployment\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Deployment.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
2023-02-06 15:44:24.818 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'analytics'
2023-02-06 15:44:24.853 [AppCenter] DEBUG: Invoke FilteringLog event for channel 'core'
2023-02-06 15:44:24.858 [AppCenter] ERROR: Could not get max storage size.
2023-02-06 15:44:24.860 [AppCenter] ERROR: Error persisting log
Microsoft.AppCenter.Storage.StorageException: Failed to store a log to the database.
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass31_0.<AddTaskToQueue>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AppCenter.Channel.Channel.<PersistLogAsync>d__41.MoveNext()
2023-02-06 15:44:24.863 [AppCenter] ERROR: Could not get max storage size.
2023-02-06 15:44:24.864 [AppCenter] ERROR: Error persisting log
Microsoft.AppCenter.Storage.StorageException: Failed to store a log to the database.
   at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass31_0.<AddTaskToQueue>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AppCenter.Channel.Channel.<PersistLogAsync>d__41.MoveNext()

**Comment by alexagev** [comment] 2023-02-06 11:10
Since they did nothing this is how it should be

**Comment by Kalyxt** [comment] 2023-02-06 12:15
Excuse my temerity, but if underlying DLLs renders App Center completely useless, its not App center concern ?

**Comment by vvechkanov** [comment] 2023-02-21 09:26
Hello! 
Sorry for long response. We did a research to understand reasons and our options with this problem. Here is what we found.
The problem is caused by SQLitePCL.raw. Problem appears after we update SQLitePCL version in AppCenter 4.5.3. There is an issue opened in there library. If you want some workaround until the problem is fixed on there side here they are:

- You can go to the previous version of AppCenter (4.5.1) it is working correctly, because it uses older version of the SQLitePCL
- You can get sqlite dll manually to your project. For it you need to create empty project with AppCenter, migrate to PackageReference, compile it. Get dll from that project and put into your project.
- Migrate project to PackageReference as I suggest earlier.

**Comment by fotoguy42** [comment] 2023-08-18 15:44
This really needs to be added to the [Get Started with WPF/WinForms](https://learn.microsoft.com/en-us/appcenter/sdk/getting-started/wpf-winforms) page, when using .net Framework, vs .net Core. I lost a lot of hours on this, and could have been easily rectified if the **App Center** team had done this.
(I might try my hand at updating that doc myself, though I suspect I dont have rights)

**Comment by fotoguy42** [comment] 2023-08-24 13:46
I converted to PackageReference and am now using the latest AppCenter nugets
