### ISSUE TITLE
"Native linking failed" error occured when using Mobile Center in Xamarin.iOS project

### ISSUE THREAD

**Issue by Li-Yanzhi** [Microsoft/AppCenter-SDK-DotNet#435] opened 2017-09-12 15:16 UTC
When we add mobile center nuget package to our Xamarin.iOS project and then build (Release for Device) will failed because of "Native Linking Failed" error as below: 

```
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed, undefined Objective-C class: MSAppDelegateForwarder. The symbol '_OBJC_CLASS_$_MSAppDelegateForwarder' could not be found in any of the libraries or frameworks linked with your application.
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed, undefined Objective-C class: MSChannelConfiguration. The symbol '_OBJC_CLASS_$_MSChannelConfiguration' could not be found in any of the libraries or frameworks linked with your application.
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed, undefined Objective-C class: MSHttpSender. The symbol '_OBJC_CLASS_$_MSHttpSender' could not be found in any of the libraries or frameworks linked with your application.
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed, undefined Objective-C class: MSKeychainUtil. The symbol '_OBJC_CLASS_$_MSKeychainUtil' could not be found in any of the libraries or frameworks linked with your application.
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed, undefined Objective-C class: MSLogger. The symbol '_OBJC_CLASS_$_MSLogger' could not be found in any of the libraries or frameworks linked with your application.
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed, undefined Objective-C class: MSMobileCenter. The symbol '_OBJC_CLASS_$_MSMobileCenter' could not be found in any of the libraries or frameworks linked with your application.
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed, undefined Objective-C class: MSSenderUtil. The symbol '_OBJC_CLASS_$_MSSenderUtil' could not be found in any of the libraries or frameworks linked with your application.
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed, undefined Objective-C class: MSServiceAbstract. The symbol '_OBJC_CLASS_$_MSServiceAbstract' could not be found in any of the libraries or frameworks linked with your application.
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed, undefined Objective-C class: MSUserDefaults. The symbol '_OBJC_CLASS_$_MSUserDefaults' could not be found in any of the libraries or frameworks linked with your application.
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed, undefined Objective-C class: MSUtility. The symbol '_OBJC_CLASS_$_MSUtility' could not be found in any of the libraries or frameworks linked with your application.
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed, undefined Objective-C class: MS_Reachability. The symbol '_OBJC_CLASS_$_MS_Reachability' could not be found in any of the libraries or frameworks linked with your application.
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed, undefined symbol: _OBJC_METACLASS_$_MSHttpSender. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed, undefined symbol: _OBJC_METACLASS_$_MSServiceAbstract. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
...\Xamarin.iOS.Common.targets(748,3): warning : References to 'BCrypt' might require additional -framework=XXX or -lXXX instructions to the native linker
...\Xamarin.iOS.Common.targets(748,3): warning : References to 'api-ms-win-core-file-l1-2-0' might require additional -framework=XXX or -lXXX instructions to the native linker
...\Xamarin.iOS.Common.targets(748,3): warning : References to 'api-ms-win-core-localization-l1-2-0' might require additional -framework=XXX or -lXXX instructions to the native linker
...\Xamarin.iOS.Common.targets(748,3): warning : References to 'api-ms-win-core-processthreads-l1-1-1' might require additional -framework=XXX or -lXXX instructions to the native linker
...\Xamarin.iOS.Common.targets(748,3): warning : References to 'api-ms-win-core-io-l1-1-1' might require additional -framework=XXX or -lXXX instructions to the native linker
...\Xamarin.iOS.Common.targets(748,3): warning : References to 'api-ms-win-core-synch-l1-2-0' might require additional -framework=XXX or -lXXX instructions to the native linker
...\Xamarin.iOS.Common.targets(748,3): warning : References to 'api-ms-win-core-handle-l1-1-0' might require additional -framework=XXX or -lXXX instructions to the native linker
...\Xamarin.iOS.Common.targets(748,3): warning : References to 'api-ms-win-core-libraryloader-l1-1-1' might require additional -framework=XXX or -lXXX instructions to the native linker
...\Xamarin.iOS.Common.targets(748,3): warning : References to 'api-ms-win-core-sysinfo-l1-2-1' might require additional -framework=XXX or -lXXX instructions to the native linker
...\Xamarin.iOS.Common.targets(748,3): warning : References to 'api-ms-win-core-sysinfo-l1-2-0' might require additional -framework=XXX or -lXXX instructions to the native linker
...\Xamarin.iOS.Common.targets(748,3): warning : References to 'api-ms-win-core-errorhandling-l1-1-1' might require additional -framework=XXX or -lXXX instructions to the native linker
...\Xamarin.iOS.Common.targets(748,3): warning : References to 'kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
...\Xamarin.iOS.Common.targets(748,3): error : Native linking failed. Please review the build log.
7>  Tool /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch execution finished. (Task ID: 277)
```

### Environment:
- Visual Studio 15.3.3
- Xamarin 4.6.0.299
- Xamarin.iOS and Xamarin.Mac SDK 10.12.0.20
- Mobile Center: 0.14

**Comment by guperrot** [comment] 2017-09-12 18:23
This issue is already being followed up on Intercom support center.

**Comment by Li-Yanzhi** [comment] 2017-09-19 15:21
Add "-gcc_flags -dead_strip" to additional mtouch arguments in project's iOS Build options, now build succeed.

**Comment by softlion** [comment] 2017-09-19 20:26
How did you find that ...

**Comment by tbaggett** [comment] 2017-09-25 17:34
FYI, adding "-gcc_flags -dead_strip" as suggested above made no difference for me. I manually deleted the bin and obj folders, tried rebuilding the solution and still see the same errors.

**Comment by guperrot** [comment] 2017-09-25 18:28
@tbaggett any chance you can share the sources? Or reproduce the bug in a sample app you can share?

**Comment by softlion** [comment] 2017-09-25 23:09
Happens only when using mobile distribution nuget on iOS.

**Comment by guperrot** [comment] 2017-09-25 23:12
We can't reproduce the issue in any on our test builds, so we would need to look at someone's sources that experience the issue.

**Comment by guperrot** [comment] 2017-10-10 21:23
Still no volunteer for sharing sources?

**Comment by irreal** [comment] 2017-11-03 23:11
This is extremely frustrating to me.
My main project fails with these exact same errors everytime I add distribute to iOS.
I am currently on 0.17.1, the version released about an hour ago, with all my packages.

I have spent the entire day today trying to do two things : fix my app's build and break the build of a new sample app that I've created to repro the issue.
I cannot do either so far :(

**Comment by guperrot** [comment] 2017-11-04 00:00
@irreal I don't have an issue with a sample app, can you share your own sample app?

**Comment by guperrot** [comment] 2017-11-17 03:10
@irreal @tbaggett @softlion 

We will need someone on this thread to provide us a reproduction scenario, none of our team members can reproduce the issue.

Sharing sources might the only way for us to investigate that issue at this point.

**Comment by guperrot** [comment] 2017-11-30 20:19
Closing this again as no-one shared enough details to reproduce the issue. Will re-open if someone provide sources or a reproduction scenario.

**Comment by attrib75** [comment] 2018-01-30 23:29
This happened to me just now as soon as I upgraded App Center.  Was fine before.  I will share whatever you need.  I guess I'll just downgrade now, as its late in the game, we're supposed to pilot soon :(

**Comment by guperrot** [comment] 2018-01-30 23:57
Make sure you have done a full clean build (close Visual Studio, remove every obj/bin folders manually, clean solution does not enough).

**Comment by attrib75** [comment] 2018-01-31 00:30
Thanks I'll give it a shot

**Comment by attrib75** [comment] 2018-01-31 14:12
This didn't work.  thanks

**Comment by guperrot** [comment] 2018-01-31 21:30
Thanks for sharing sample sources showing the problem and exact reproduction steps. As it was mentioned multiple times in the thread before, we never ever were able to reproduce the problem in any of our test apps so the only way for us to investigate this issue is to have someone willing to share sources so we can investigate.

**Comment by attrib75** [comment] 2018-01-31 21:43
Yes, I can do that as I said.   Where and how do I send it

**Comment by guperrot** [comment] 2018-01-31 21:45
If sources are private, you can contact us on intercom which is the dedicated and official/main support center of AppCenter. This can be accessed via the blue chat button on any https://appcenter.ms page.

**Comment by guperrot** [comment] 2018-02-14 01:03
Hey, we have not heard from you in a while and have not received sources so we will close the ticket now.
Given the nature of the issue we reopen only if someone share sources that can clearly show the issue is produced.

**Closed by guperrot** 2018-02-14 01:03 UTC
Labels: support

**Comment by pfbwitz** [comment] 2018-10-30 13:07
I get this error when there's still HockeyApp code present in the iOS-project, regardless of the order the code exists in the AppDelegate. I commented out all HockeyApp-source code and my projects build, all including the AppCenter nugets. I might use seperate build configurations for dev,tst,acc and prd, but for now I thought I'd offer a solution. :) I hope this works for everyone still struggling with this.

**Comment by csmac3144** [comment] 2019-01-17 13:59
Just got this error again. Right before a customer demo!

I'll send you whatever you need asap.

**Comment by clpolet** [comment] 2019-01-18 18:37
Hello, please provide us sample sources showing the problem and exact reproduction steps. Thanks

**Comment by Martyf101** [comment] 2019-01-24 21:07
Just got this error. Happens whenever i comment out AppCenter.Start(...); Compiles fine again when i add it back in.

**Comment by jwallra** [comment] 2019-01-25 01:09
Hi @Martyf101 - please open a [new issue](https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/new) using the template and we can give you a hand!
