### ISSUE TITLE
Xamarin.Insights Compatibility

### ISSUE THREAD

**Issue by projectgoav** [microsoft/appcenter-sdk-dotnet#615] opened 2018-03-08 14:22 UTC
I noticed today that Xamarin.Insights will be retired as of 31st March. 

I raised a feature-request (#529) previously about Xamarin.Mac support but it didn't look like this was going to be supported anytime soon. Will this be available before 31st March?

If not, and as AppCenter is the replacement for insights I was wondering how we'd support our Xamarin.Mac (and non UWP apps) ?

**Comment by EmilAlipiev** [comment] 2018-03-09 18:14
Xamarin Android and IOS are supported. I have been testing xamarin android and it works fine. I hope that they can bring Mac and UWP as well as soon as possible.

**Comment by elamalani** [comment] 2018-03-09 18:25
@projectgoav We are not in full parity between Xamarin Insights and App Center. We would like to support Xamarin Mac in App Center in the future, but it is not happening before March 31st and unfortunately, we don't have an ETA yet.

**Comment by EmilAlipiev** [comment] 2018-03-10 03:34
What about xamarin uwp?  Can we get that before 31th march?

**Comment by guperrot** [comment] 2018-03-10 03:46
(AppCenter has support for UWP analytics push and crashes but not handled exceptions.)

**Comment by EmilAlipiev** [comment] 2018-03-11 16:00
@guperrot  i integrated but it doesnt work properly when I asked to support i got answer as this link 

https://intercom.help/appcenter/crashes/setting-up-uwp-crashes

what it meant "distribute the build via Windows Dev Center", you mean if i upload my app to the windows store ? which i am doing already but i dont see any crash reported.

**Comment by elamalani** [comment] 2018-03-12 00:14
@EmilAlipiev There are some limitations when using Crashes services for UWP apps. Please refer to our documentation link to be sure that all the criteria is met for Crashes to work end to end so that you can see the reports in portal.
https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp

**Comment by EmilAlipiev** [comment] 2018-03-12 00:58
@elamalani  thanks for your reply but i am meeting all points. my min and target versions are falls creators update and i distributed my app through the Microsoft store. In my app.cs I initiliaze all as below. it works fine on android but I dont see any crashes reported for UWP. I am seeing crashes in xamarin insights for UWP.

```
   public App()
        {

            Microsoft.AppCenter.AppCenter.Start("android=xxxxx;" +
                   "uwp=xxxxx",
                   typeof(Microsoft.AppCenter.Analytics.Analytics), 
typeof(Microsoft.AppCenter.Crashes.Crashes));```

**Comment by stefandevo** [comment] 2018-03-16 18:10
MS and Xamarin did a VERY BAD job here ... when they said Xam Insights was going away they promised that this was not going to happen before a proper replacement was there and it had ALL THE FEATURES. Now they are stopping XamInsights and there is no 100% feature availability in App Center. It's a shame that MS is handling the community (and previous paying customers of Xamarin).

**Comment by keithballinger** [comment] 2018-03-16 18:48
Update: we're extending the Xamarin Insight shutdown until end of April. There will be an email communication on this soon. @stefandevo could you reach out to me on email (or we can arrange a call) about the above? Thanks!

**Comment by stefandevo** [comment] 2018-03-16 18:49
Hi Keith, we already had a conf call couple of months ago, where I did tell you that these were our concerns... 
Good to hear that it is extended; I hope this gives you the time to have a 100% transition of Xamarin Insights features. 
Thx.

**Comment by stefandevo** [comment] 2018-03-16 19:12
Why not open source the Xamarin Insights client library? That way we could change the URL's inside to forward the data to own servers; I think for a lot of people this could be a good in between situation. In that way, at least we do not have to change the implementation, and still have the data provided.

**Comment by EmilAlipiev** [comment] 2018-03-22 11:31
I am really sorry to say that App center errors are not useful at all if error properties have character limitation. I already reported on the backend. just wanted to state it here.  all of us upload android without pdb files in release mode and error wont show exact line information but we can only compensate this sending custom error properties. if you restrict it like events (probably you just inherited code from events) we cant just work with it. xamarin insights had no limitations. thank you.

**Comment by projectgoav** [comment] 2018-05-04 13:17
Now that Insights.Xamarin.com is redirecting to AppCenter, I assume that Insights has been turned off.

What's the plan for supporting Xamarin Mac? We'll require it to move to AppCenter. Otherwise, is there a way to keep looking at the Insights data until XamarinMac support is implemented?

**Comment by elamalani** [comment] 2018-05-04 17:41
@projectgoav We don't have plans to support Xamarin Mac in our short-term roadmap.

**Comment by projectgoav** [comment] 2018-11-06 15:14
Any update on Mac support?

I'd have thought it more of a priority to support existing Insights and Hockapp platforms before adding new platforms like Unity....

**Comment by elamalani** [comment] 2018-11-06 17:56
@projectgoav Unfortunately, there is no plan to support Xamarin Mac in App Center yet. We will share more information on our [Roadmap](https://docs.microsoft.com/en-us/appcenter/general/roadmap) page whenever this platform support is prioritized, please stay tuned.

**Comment by justin-caldicott** [comment] 2018-11-07 13:48
> please stay tuned.

Doesn't sound like it's going to happen within a year.. tuning out.

**Comment by EmilAlipiev** [comment] 2018-11-07 15:19
what is the ETA for UWP?

**Comment by projectgoav** [comment] 2021-02-10 12:02
In the linked issue: https://github.com/microsoft/appcenter-sdk-dotnet/issues/529 it appears that now HockeyApp has been shutdown there's a renewed focus on reliability and performance in 2021

3 years later, is the promised Xamarin.Insights feature parity no longer going to be delivered?

**Comment by projectgoav** [comment] 2021-11-03 14:12
https://github.com/microsoft/appcenter/issues/143

> 
> Hi folks, glad to inform that we are currently working on supporting Xamarin.Mac platform. You can track the progress here: [microsoft/appcenter-sdk-dotnet#1586](https://github.com/microsoft/appcenter-sdk-dotnet/pull/1586). The PR is based on @nor0x's implementation, thanks a lot to him for his great work.
> 
> The Xamarin.Mac support is expected to be available in the next release this quarter.

**Comment by DmitriyKirakosyan** [comment] 2021-12-01 14:12
I'm closing this issue as a duplicate of #143. Let's follow the progress in the original feature request.

**Closed by DmitriyKirakosyan** 2021-12-01 14:12 UTC
Labels: feature request
