### ISSUE TITLE
Android: Possibility to manage in-app updates when the app is in kiosk mode

### ISSUE THREAD

**Issue by andrekiba** [microsoft/appcenter-sdk-dotnet#787] opened 2018-12-13 16:32 UTC
**Feature request**

I have a Xamarin Android application that is a device admin and runs in kiosk mode (using `StartLockTask`).
Everything works fine...but I would also like to have the possibility to update the app through AppCenter in-app updates.

And actually it seems impossible.

I can workaround the one-time first registration to `Distribute` (I still don't understand why you have chosen this strategy) when the app is started for the first time...but I cannot figure out how to do the same for subsequent updates.
Using the `SetLockTaskPackages` I can setup _com.google.android.packageinstaller_ and _com.android.packageinstaller_ to be able to enter in lock task mode but I think the AppCenter SDK doesn't support this.

So the question is: is there a way to have in-app updates through AppCenter without leaving the kiosk mode or at least forcing the package installer to behave as if it were in kiosk mode?
Otherwise I'm forced to leave AppCenter, with great regret because we have everything in here, and use something like an MDM tool...

**Comment by guperrot** [comment] 2018-12-13 19:30
Hi, I think the issue is that your application is never restarted while the SDK checks for updates when the application starts (the launcher activity onCreate).

To work around the issue you need to call:

```
await Distribute.SetEnabledAsync(false);
await Distribute.SetEnabledAsync(true);
```

when you want to check updates (like for example at regular intervals).

**Comment by andrekiba** [comment] 2018-12-13 19:55
thanks @guperrot but this is not the problem. The problem occurs when the download of the new version is completed and AppCenter needs to startup the package installer to be able to install it. In logcat I can see the kiosk violation error because the application is in lock task mode

**Comment by guperrot** [comment] 2018-12-13 19:58
Can you share the Android logcat logs please?

**Comment by andrekiba** [comment] 2018-12-13 20:02
updated the prev comment 😀

**Comment by andrekiba** [comment] 2018-12-13 20:43
😀😀💪🏻 could you please explain this “try opening the installer from application code” better? Because, I receive the error exactly when the download bar (mandatory update) is completed and starting from this point the app is blocked (with the dialog bar completed in the middle of the screen) and I cannot do anything else, only restart the app. is there a way to avoid this and then manually launch the package installer within the app?

**Comment by guperrot** [comment] 2018-12-13 20:50
So it probably fails because of the NEW_TASK intent flag in the current SDK code.
If you mimick SDK code that does the startActivity call but from the current Activity Context and without using NEW_TASK intent flag, it might work.

**Comment by guperrot** [comment] 2018-12-14 01:31
I tried in my own Java app in Android 9 to lock and allow browser and installer.
For me the intent is not an issue and could click install, however after installing the user can click done instead of restarting the app, leaving the device unlocked and accessing home screen.

That particular issue cannot be addressed by the SDK as the SDK can only run in-process but the process is killed after installing so if leaving device unlocked right after updating is an issue, I am not sure what can be done.

For the details of my setup (it's java but should not matter):


in MainActivty onCreate:
```
        startLockTask();
        DevicePolicyManager pm = (DevicePolicyManager) getSystemService(Context.DEVICE_POLICY_SERVICE);
        pm.setLockTaskPackages(new ComponentName(this, MyDeviceAdminReceiver.class), new String[]{"com.android.chrome","com.google.android.packageinstaller"});
```

In adb shell:

```
adb shell dpm set-device-owner com.microsoft.appcenter.sasquatch.project/com.microsoft.appcenter.sasquatch.MyDeviceAdminReceiver
Success: Device owner set to package ComponentInfo{com.microsoft.appcenter.sasquatch.project/com.microsoft.appcenter.sasquatch.MyDeviceAdminReceiver}
Active admin set to component {com.microsoft.appcenter.sasquatch.project/com.microsoft.appcenter.sasquatch.MyDeviceAdminReceiver}
```

In `AndroidManifest.xml`:

```
        <receiver android:name=".MyDeviceAdminReceiver"
            android:permission="android.permission.BIND_DEVICE_ADMIN">
            <meta-data android:name="android.app.device_admin" android:resource="@xml/my_admin" />
            <intent-filter>
                <action android:name="android.app.action.DEVICE_ADMIN_ENABLED" />
            </intent-filter>
        </receiver>
```

`MyDeviceAdminReceiver.java`:

```
package com.microsoft.appcenter.sasquatch;

import android.app.admin.DeviceAdminReceiver;

public class MyDeviceAdminReceiver extends DeviceAdminReceiver {
}
```

**Comment by andrekiba** [comment] 2018-12-14 07:07
Again, thank you @guperrot !
It's strange because I have more or less exactly the same code with the only difference that for now my app runs as a device admin only, not also device owner (in this case then the only way to remove the owner is to wipe the device or remove it from inside the app itself with a deprecated `ClearDeviceOwnerApp` api).
There is also the way to set the attribute `android:testOnly` to `true` in the manifest but in that case then is impossible to install the app using AppCenter.
So I think the `SetLockTaskPackages` behaves in a different way. I try with device owner.
Then yes :-( , I already saw the problem related to the "Done" button at the end of the process and I need to find a way to workaround it...maybe setting the app as home.
Is there a way to "modify" the package installer popup to remove the "Done" button?

**Comment by guperrot** [comment] 2018-12-14 19:23
setLockTaskPackages requires device owner to pop up the installer. I tested with just admin and it does not work. When using device owner, it works and no modification is needed to our SDK.

The problem is that using the system installer is the only way to install packages when not being a system application like Play Store. Also this installer dialog is not configurable so no way to remove the Done button.

It is not a SDK issue but a limitation of the Android platform for non system apps, I am afraid we cannot implement the feature in AppCenter.

**Comment by AnastasiaKubova** [comment] 2021-12-15 11:42
As was described above there are no ways to resolve this issue due to Android system restriction, so I'm going to close this issue. Feel free to reopen it if you will have additional questions.

**Closed by AnastasiaKubova** 2021-12-15 11:42 UTC
Labels: feature request
