### ISSUE TITLE
.NET MAUI MacCatalyst app is trying to load ''System.Windows.Forms'

### ISSUE THREAD

**Issue by dhindrik** [microsoft/appcenter-sdk-dotnet#1702] opened 2022-11-24 06:58 UTC
### **Description**
Exception when running AppCenter.Start, it is trying to load ''System.Windows.Forms'. There are a similar issue for Windows, https://github.com/microsoft/appcenter-sdk-dotnet/issues/1693

### **Repro Steps**

1. Install the NuGet packages for crashes and analytics
2. Add the AppCenter.Start in App.xaml.cs
3. Run the App on MacCatalyst

### **Details**

```
System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

For full logs see the attached files.

[Visual Studio Enterprise 2022 for Mac Pr.txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/10081473/Visual.Studio.Enterprise.2022.for.Mac.Pr.txt)
[log (1).txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/10081485/log.1.txt)

**Comment by DmitriyKirakosyan** [comment] 2022-11-24 07:24
@dhindrik , thank you for creating a separate item! We will inform you once it is fixed.

**Comment by mhrastegari** [comment] 2023-01-30 11:38
Facing the same here.

**Comment by zahrabayatt** [comment] 2023-02-10 09:08
Any updates on this?

**Comment by IlyaBausovAkvelon** [comment] 2023-02-13 23:48
@zahrabayatt we are still working on this.

**Comment by kyurkchyan** [comment] 2023-05-16 06:28
Same issue :( It's very frustrating

**Comment by tpitman** [comment] 2023-06-22 14:15
Another one with the same issue. Any fix coming or is this even being worked on?

**Comment by busitech** [comment] 2023-08-03 01:29
We are facing the same problem here.

**Comment by DmitriyKirakosyan** [comment] 2023-08-08 10:17
Hello everyone,
Due to shifting priorities, we've had to postpone the work on MAUI MacCatalyst. However, please note that this task remains a high priority on our board. We are committed to addressing the issue at the earliest opportunity. Thanks for your patience and understanding.

**Comment by AndreasReitberger** [comment] 2023-08-08 16:48
Still facing this issue. Any ETA for a fix? It's been awhile.

**Comment by dfernandezramos** [comment] 2023-11-22 08:36
Hi there. I am reproducing the issue on a macBook PRO M1 with macOS Sonoma. My application is net7 using Avalonia 11

**Comment by tpitman** [comment] 2024-01-17 14:58
I am now seeing this error when running it on Android. We need a fix for this or a work around.

**Comment by alimuhammadiiii** [comment] 2024-01-17 17:16
Any news on this?

**Comment by Mogikan** [comment] 2024-01-23 13:13
Two years ago they stopped planning development for the next year and seemed to stop even maintaining this product.

**Comment by busitech** [comment] 2024-01-23 17:36
Wow, that's terrible news.  Did Microsoft announce this officially?

**Comment by NPadrutt** [comment] 2024-01-23 21:07
@busitech what I would consider at least an indicator for what @Mogikan  is saying is that the roadmap was never updated since 2022: https://github.com/Microsoft/appcenter/wiki/Roadmap

**Comment by thewizrd** [comment] 2024-01-24 01:20
Not sure if this is being worked on, but I've been using the below change for a few months and its been working fine.
Binaries for maccatalyst taken from the latest xcframework package.

[Binaries](https://github.com/microsoft/appcenter-sdk-apple/releases)
[Changes](https://github.com/thewizrd/appcenter-sdk-dotnet-1/commits/feature/maccatalyst-support/)

**Comment by Mogikan** [comment] 2024-01-30 16:13
@busitech since silverlight death they stopped announcing bad news. Now they open source products and abandon repos. For example, one drive sdk was abandoned 7 years ago. Sounds crazy, but nobody cares. https://github.com/OneDrive/onedrive-sdk-csharp

**Comment by mhrastegari** [comment] 2024-02-09 18:17
That's awesome! If it's working, why not doing a PR? @thewizrd

**Comment by DmitriyKirakosyan** [comment] 2024-02-21 09:13
Hi everyone, I prepared the maccatalyst support [PR](https://github.com/microsoft/appcenter-sdk-dotnet/pull/1771), based on https://github.com/microsoft/appcenter-sdk-dotnet/issues/1702/#issuecomment-1907191123 (thanks a lot to @thewizrd).
We will merge the PR once CI is fixed.

**Comment by mhrastegari** [comment] 2024-03-05 20:06
@DmitriyKirakosyan And when does CI getting fixed? :")

**Comment by vladPanasiuk** [comment] 2024-05-08 07:07
@DmitriyKirakosyan Any news about this fix?

**Comment by AndreasReitberger** [comment] 2024-05-29 12:05
As far as I can remember, AppCenter is shutdown by end of March 2025. So I guess there will be no efforts to fix this issue at all...

**Comment by MikhailSuendukov** [comment] 2024-05-29 16:27
Hello, the [AppCenter .NET SDK v5.0.4](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/5.0.4) has been released, including a fix for this issue. Therefore, I am closing this issue.

**Closed by MikhailSuendukov** 2024-05-29 16:27 UTC
Labels: bug

**Comment by mhrastegari** [comment] 2024-05-29 16:48
Did you even test it? 🙂 @MikhailSuendukov

**Comment by tylerwilson** [comment] 2024-05-29 16:51
Same, just tried 5.0.4 and same issue:

`System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)
   at Microsoft.AppCenter.AppCenter.Start(String appSecret, Type[] services)`

**Comment by domneedham** [comment] 2024-06-03 10:35
Also facing this issue still with 5.0.4 for Maccatalyst.

**Comment by sovdchains** [comment] 2024-06-07 07:54
5.0.5 seems to have fixed the issue

**Comment by MikhailSuendukov** [comment] 2024-06-07 08:52
Hello, the [AppCenter .NET SDK v5.0.5](
https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/5.0.5) with fix for this issue has been released.

**Comment by Mogikan** [comment] 2024-07-27 09:31
Forget about appcenter. As I mentioned earlier  

> Wow, that's terrible news. Did Microsoft announce this officially?

Yes
