### ISSUE TITLE
PRI257 warning changing the default language in UWP and using with Microsoft.Xaml.Behaviors.Uwp.Managed 

### ISSUE THREAD

**Issue by asierpn** [microsoft/appcenter-sdk-dotnet#1497] opened 2021-03-11 06:56 UTC
If you change the default language in UWP and adds Microsoft.AppCenter.Crashes and Microsoft.Xaml.Behaviors.Uwp.Managed nuget packages the PRI257 warning appears.

Repro steps:

1. Create a new UWP app
2. Add Microsoft.AppCenter.Crashes and Microsoft.Xaml.Behaviors.Uwp.Managed nuget packages
3. Change default language in Package.appxmanifest to es-ES
4. Build the project

Reported also in https://github.com/microsoft/XamlBehaviors/issues/215

**Comment by Jamminroot** [comment] 2021-03-12 09:20
Hey @asierpn, thanks for reaching out to us!
However, that does not look like a problem with the SDK, but rather a warning regarding some additional changes required in the project itself.

If you are certain that the problem is somewhere in the SDK, can you share a sample project (clean, without anything), where only SDK is added and warning appears upon build?

**Comment by asierpn** [comment] 2021-03-12 09:33
Hey @Jamminroot, thanks for your response.

I know that it's a weird warning, but it only happens when installing Microsoft.AppCenter.Crashes and Microsoft.Xaml.Behaviors.Uwp.Managed nuget packages and changing the default language of the package, considering that both packages are owned by Microsoft I thought that you could work together with the XamlBehaviors team to identify the cause of it.

Here is a repro project.
[App5.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/6128931/App5.zip)

**Comment by Jamminroot** [comment] 2021-03-12 09:49
Let me some time to run through the project

**Comment by Jamminroot** [comment] 2021-03-12 11:14
It appears to be a known issue: https://developercommunity.visualstudio.com/t/warning-pri257-0xdef00522-when-installing-a-nuget/862984. As per the ticket - it claims to have no impact on runtime, just a warning in the build time.

I believe that it should be fixed on NuGet \ UWP side, and not on SDK side (our default language is en-US). 

I'm closing the issue now.

**Closed by Jamminroot** 2021-03-12 11:14 UTC
Labels: support

**Comment by asierpn** [comment] 2021-03-12 12:31
Thanks for your time, I will try to open a new ticket in the developer community site.
