### ISSUE TITLE
Xamarin Mac Support

### ISSUE THREAD

**Issue by projectgoav** [microsoft/appcenter-sdk-dotnet#529] opened 2017-12-05 10:42 UTC
Any plans to support this platform?

**Comment by elamalani** [comment] 2017-12-18 22:18
@projectgoav We only support native macOS at the moment. Xamarin Madc support is in our backlog but there is no ETA yet.

**Comment by andymac4182** [comment] 2018-01-07 04:03
It would be great if this support could include Xamarin.Forms support as well.

**Comment by andymac4182** [comment] 2018-01-08 12:05
@elamalani @guperrot Is there possibly some generic handlers we can send crashs to by handling this? Or possibly point me in the right direction where I can start implementing this as a PR.

**Comment by elamalani** [comment] 2018-01-08 21:16
@andymac4182 Xamarin Mac support is on our roadmap but we haven't started working on this feature yet. So there is no timeline when this platform support would be available. Apart from the SDK, we also need to do work in our backend services before we fully support this platform in App Center.

I'd be sad if you submit a PR now and we can't review and merge it for a while until we have the complete platform support ready. Would it be possible to work with you on a PR once we start implementing Xamarin Mac support? We will contact you in that case and it could be a close collaboration between you and our team if you'd like to work on it.

**Comment by andymac4182** [comment] 2018-01-10 01:42
Thank you for your reply @elamalani. I am happy to hold off. I was hoping to be able to use AppCenter for all three platforms but I will have to find an alternative for mac. 

It would be great to hear back when you are working on Xamarin.Mac support. I know it isn't on the timeline but are we talking 3 or 6 months? It would be great if there was a rough timeline similar to Xamarin.Forms. https://github.com/xamarin/Xamarin.Forms/wiki/Feature-Roadmap

**Comment by apparentvisuals** [comment] 2018-03-06 16:27
I forked and implemented the bindings for Mac based on the iOS bindings for a project, both Crash and Analytics seems to be functional. It will report the crash but is missing the symbols right now. I will be keeping it up to date as new native Mac features are added. Based on what @elamalani said I haven't created a PR, but more than willing to work together when Mac is ready.

Still, if anyone wants to try it. https://github.com/apparentvisuals/AppCenter-SDK-DotNet.git

**Comment by equinox2k** [comment] 2018-04-23 19:52
For those interested I’ve done PR #658

**Comment by apparentvisuals** [comment] 2018-04-25 20:32
@equinox2k No, I didn't do anything special when translating from iOS to Mac. 

I did a quick comparison, and setting logging to verbose it sends out exceptions but doesn't show up on the dashboard for me. 

I have to admit though the last time I used crashes was when I wrote my own bindings rather than taking the iOS source code verbatim. This would send out native ObjC level crash info and would show up on the dashboard without symbols.

Neither solution I found particularly useful so I didn't bother with a PR. But if you want to send pure native exceptions, generate the bindings manually so it wraps the native frameworks 100%, the iOS source code doesn't do that.

**Comment by projectgoav** [comment] 2018-11-06 15:14
Any update on plans to support Mac? 

There's no way for old Xamarin Insights users to gets stats from Xamarin.Mac apps.

**Comment by projectgoav** [comment] 2018-11-07 13:35
See response here: https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/615#issuecomment-436347378

**Comment by equinox2k** [comment] 2018-11-07 13:55
Hi,

I came across same problem and did my own work around by using application insights directly. I had to create my own exception handling and do lots of try catches around code which then calls my own error logging to insights but has given me approximate areas code crashes with line numbers etc. I also used events etc to track other things. If anyone interested I can create a demo app.

Sent from my iPhone

On Nov 7, 2018, at 5:35 AM, Ewan <notifications@github.com<mailto:notifications@github.com>> wrote:


See response here: #615 (comment)<https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/615#issuecomment-436347378>

**Comment by NickSpag** [comment] 2019-01-26 00:50
@andymac4182 were you able to find an alternative?

**Comment by andymac4182** [comment] 2019-01-26 05:11
I ended up leaving the project this was for so not sure if they worked out a work around or alternative. It really sucks it is still not available.

**Comment by bluebirdtech** [comment] 2019-01-27 18:13
We're running without centralised logging for the desktop apps.  Wasn't entirely satisfied with any of the other options out there either. :(

**Comment by jacobshepherd** [comment] 2019-04-30 21:23
> I forked and implemented the bindings for Mac based on the iOS bindings for a project, both Crash and Analytics seems to be functional. It will report the crash but is missing the symbols right now. I will be keeping it up to date as new native Mac features are added. Based on what @elamalani said I haven't created a PR, but more than willing to work together when Mac is ready.
> 
> Still, if anyone wants to try it. https://github.com/apparentvisuals/AppCenter-SDK-DotNet.git

Hey Guys - 

Did you ever figure out how to build the nuget packages after adding xamarin mac support?  We have a similar need coming up and would appreciate any help you could offer!

Jacob

**Comment by nor0x** [comment] 2019-07-04 18:41
> Hi, I came across same problem and did my own work around by using application insights directly. I had to create my own exception handling and do lots of try catches around code which then calls my own error logging to insights but has given me approximate areas code crashes with line numbers etc. I also used events etc to track other things. If anyone interested I can create a demo app.


Hi @equinox2k - i'm going through your PR because i'm working on AppCenter integration for my Xamarin.Mac app - thank you for your work. Actually I would be interest in a possible demo app as you mentioned, because i'm not 100% sure on how to use the bindings - i always get a linker error

**Comment by tipa** [comment] 2020-02-17 12:22
> I forked and implemented the bindings for Mac based on the iOS bindings for a project, both Crash and Analytics seems to be functional. It will report the crash but is missing the symbols right now. I will be keeping it up to date as new native Mac features are added. Based on what @elamalani said I haven't created a PR, but more than willing to work together when Mac is ready.
> 
> Still, if anyone wants to try it. https://github.com/apparentvisuals/AppCenter-SDK-DotNet.git

Did anyone get this to work recently? I just tried to build the bindings with [v3.0](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/3.0.0) (released 3 days ago). The build succeeded, but building my main project fails with  `MMP : warning MM2006: Native library 'libsecret-1.so.0' was referenced but could not be found.` - Do I need to use v2.x?

**Comment by MatkovIvan** [comment] 2020-02-17 12:41
@tipa we'll release .NET SDK with updated bindings for the new version soon. 

_(please open separate issues for questions not related to this feature request)_

**Comment by tipa** [comment] 2020-02-17 12:46
@MatkovIvan so that means there will be official AppCenter bindings for Xamarin.Mac soon? That would be fantastic news!
Sorry for posting the question here, @apparentvisuals disabled issues for [his bindings repo](https://github.com/apparentvisuals/AppCenter-SDK-DotNet)

**Comment by MatkovIvan** [comment] 2020-02-17 13:00
No sorry, I have no updates about macOS support. I meant that the .NET SDK wrapping the App Center Apple SDK v3.0 has not yet been released, and if you want to use this version of native library in .NET, you should wait for this release.

**Comment by guperrot** [comment] 2020-02-20 22:39
The Apple SDK 3.0.0 has been released and the .NET SDK using those 3.0.0 bindings as well in version [3.0.0](https://github.com/microsoft/appcenter-sdk-android/releases/tag/3.0.0).

**Comment by tipa** [comment] 2020-02-20 22:47
I am a bit confused. So that means I can use the AppCenter SDK in a native Swift MacOS app, but still not on Xamarin.MacOS? What bindings were released in v3.0.0? As far as I understood there are no plans for Xamarin.MacOS bindings...

**Comment by ivanicin** [comment] 2020-02-20 22:53
@tipa , @guperrot , @MatkovIvan - please stop spamming us about something that is not this issue. If you wish open the new issue and talk there or talk somewhere else. Thanks.

**Comment by guperrot** [comment] 2020-02-20 23:06
No we don't have bindings for MacOS in the .NET SDK, I was just replying to the previous comment:

> I meant that the .NET SDK wrapping the App Center Apple SDK v3.0 has not yet been released, and if you want to use this version of native library in .NET, you should wait for this release.

Sorry for the confusion.

**Comment by kcrandall** [comment] 2020-05-12 02:54
Is macOS in development still? Will it be out anytime this year/soon?

**Comment by ivanicin** [comment] 2020-05-12 10:04
@kcrandall I can't provide anything official, but if you look in the right column no one is assigned to this and there is no milestone plan, so I would say there are no current plans for this.

But if you want (just like me) for this to happen, at least upvote the bug report, if everyone does it maybe they'll take a look sooner...

**Comment by Suplanus** [comment] 2020-06-05 04:42
Microsoft focus macOS with MAUI in the roadmap as first platform.
Is that an argument to focus this platform also in AppCenter?
Second argument is that this issue is the most upvoted one in the repo.

Would love to see this 💕

**Comment by projectgoav** [comment] 2020-06-05 20:20
> Microsoft focus macOS with MAUI in the roadmap as first platform.

I believe Mac support is under the "community" tier which means that any devs that wish it need to support it themselves. 

--
I think given it's 2.5 years since they shut Xamarin Insights down and told everyone there would be feature partiy with AppCenter but that has yet to materialise, it's not going to happen.

**Comment by kcrandall** [comment] 2020-06-05 20:31
> > Microsoft focus macOS with MAUI in the roadmap as first platform.
> 
> I believe Mac support is under the "community" tier which means that any devs that wish it need to support it themselves.
> 
> --
> I think given it's 2.5 years since they shut Xamarin Insights down and told everyone there would be feature partiy with AppCenter but that has yet to materialise, it's not going to happen.

I think it is going to be fully supported for MAUI. For xamarin.forms it is in community.

**Comment by projectgoav** [comment] 2020-06-05 20:32
> I think it is going to be fully supported for MAUI. For xamarin.forms it is in community.

Thanks for clearing that up. I was under the impression it was all Mac support. Maybe there's some hope yet.

**Comment by nor0x** [comment] 2020-09-30 19:57
Hi all 👋
since i couldn't wait for MAUI i have set out to created Xamarin.Mac bindings for AppCenter myself. If someone of you still need it you are all welcome to check it out at and contribute https://github.com/nor0x/AppCenter-XMac. These bindings are based on the latest SDK versions and currrently i have `AppCenter.Analytics` and `AppCenter.Crashes` working `AppCenter.Push` is next on my list

**Comment by MatkovIvan** [comment] 2020-10-02 07:01
@nor0x 👍 
but regarding `Push` module:
> Earlier this year, Microsoft announced the retirement of the preview MBaaS services in Visual Studio App Center, which include Auth, Data, and Push services.

See [Migrating off App Center Push](https://devblogs.microsoft.com/appcenter/migrating-off-app-center-push/)

**Comment by nor0x** [comment] 2020-10-02 07:12
thanks for the info @MatkovIvan , luckily i haven't started working on `Push` yet 😉

**Comment by Suplanus** [comment] 2021-02-10 09:59
Any updates?

**Comment by russelarms** [comment] 2021-02-10 11:54
@Suplanus, AppCenter team is focused on improving reliability and performance through mid-2021: https://github.com/microsoft/appcenter#planning
Maybe you can try https://github.com/nor0x/AppCenter-XMac

**Comment by projectgoav** [comment] 2021-02-10 11:57
@russelarms - Is feature parity with Xamarin.Insights no longer a priority? 

It was promised when AppCenter was first launched, then when Xamarin.Insights was shutdown.

**Comment by Suplanus** [comment] 2021-02-10 11:58
Thanks for the reply @russelarms 
I tried @nor0x version, but stuck with this issue: https://github.com/nor0x/AppCenter-XMac/issues/17

I think it should be "Roadmap 2021" and not "Roadmap 2020".

**Comment by russelarms** [comment] 2021-02-10 12:21
@projectgoav features may be prioritized later this year, but for now, the App Center team is focused on dealing with current technical debt.

**Comment by Suplanus** [comment] 2021-06-16 12:39
Any update?

**Comment by ivmirx** [comment] 2021-06-21 01:18
@Suplanus I guess, no new features until [at least the end of this year](https://github.com/Microsoft/appcenter/wiki/Roadmap). See https://github.com/nor0x/AppCenter-XMac above.

It is annoying how MS management wants to have cross-platform solutions without actually investing in teams. As far as I know, the MAUI team is understaffed too.

**Comment by Suplanus** [comment] 2021-06-21 04:27
Thank you @ivmirx.
I know about nor0x solution, but I can use it, because of: https://github.com/nor0x/AppCenter-XMac/issues/17

**Comment by projectgoav** [comment] 2021-11-03 14:12
https://github.com/microsoft/appcenter/issues/143

> 
> Hi folks, glad to inform that we are currently working on supporting Xamarin.Mac platform. You can track the progress here: [microsoft/appcenter-sdk-dotnet#1586](https://github.com/microsoft/appcenter-sdk-dotnet/pull/1586). The PR is based on @nor0x's implementation, thanks a lot to him for his great work.
> 
> The Xamarin.Mac support is expected to be available in the next release this quarter.

**Comment by DmitriyKirakosyan** [comment] 2021-12-01 14:12
I'm closing this issue as a duplicate of #143. Let's follow the progress in the original feature request.

**Closed by DmitriyKirakosyan** 2021-12-01 14:12 UTC
Labels: feature request
