### ISSUE TITLE
Unable to compile iOS - MT0009 : Error while loading assemblies ... Microsoft.AppCenter.Crashes.iOS.Bindings.dll

### ISSUE THREAD

**Issue by dleinius** [microsoft/appcenter-sdk-dotnet#1362] opened 2020-03-31 15:37 UTC
### **Description**

I am unable to compile a newly created iOS Project with Visual Studio 16.5.1 on Windows 10 with AppCenter (remote Mac compilation)

The following error occurs during the compilation:
>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(845,3): error MT0009: Error while loading assemblies: /Users/admin/Library/Caches/Xamarin/mtbs/builds/App4/167ed36897e31ece62c888758d8dbafb/bin/iPhoneSimulator/Debug/Microsoft.AppCenter.Crashes.iOS.Bindings.dll

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. On Visual Studio 16.5.1 on Windows 10: Create new native iOS Project
2. Pair to Mac (remote compile)
3. Compile empty iOS project -> compilation successful
4. Open Package Manager and add reference to AppCenter.Crashes (3.1.0)
5. Clean Project
6. Compile iOS project -> compilation with error:

>  Connecting to Mac server xxx.xxx.xxx.xxx...
1>  /usr/bin/plutil -convert binary1 -o obj/iPhoneSimulator/Debug/optimized/Entitlements.plist Entitlements.plist 
1>  App4 -> C:\Users\xxx\Source\repos\App4\App4\bin\iPhoneSimulator\Debug\App4.exe
1>  Detected signing identity:
1>    Bundle Id: com.companyname.App4
1>    App Id: com.companyname.App4
1>  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/admin/Library/Caches/Xamarin/mtbs/builds/App4/167ed36897e31ece62c888758d8dbafb/obj/iPhoneSimulator/Debug/response-file.rsp -v -v -v -v 
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(845,3): error MT0009: Error while loading assemblies: /Users/admin/Library/Caches/Xamarin/mtbs/builds/App4/167ed36897e31ece62c888758d8dbafb/bin/iPhoneSimulator/Debug/Microsoft.AppCenter.Crashes.iOS.Bindings.dll
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Doing the same steps on the Mac itself with VS Community Mac results in no errors.

### **Details**

1. Which SDK version are you using?
    - 3.1.0 (tested down to 2.6.4)
2. Which OS version did you experience the issue on?
    - VS 16.5.1 on Windows 10 with Pair to Mac with MacOS 10.15.4

Any help appreciated!
Daniel

**Comment by russelarms** [comment] 2020-04-02 16:18
MT0009: Error while loading assemblies
This error is described here.
https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/mtouch-errors#mt0009-error-while-loading-assemblies-
this error occurs due to improperly configured parameters, the environment, or the absence of any components.

We were not able to reproduce it yet, for us it worked fine.
Сan I clarify what version of Mono and Xamarin you have?

**Comment by dleinius** [comment] 2020-04-03 07:53
@russelarms - first of all, thanks for your help!

I attached the version info of the Visual Studio on the Windows machine:
[Visual Studio Info - Windows.txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/4425502/Visual.Studio.Info.-.Windows.txt)

On the remote MAC Mono 6.8.0.99 is installed.

Furthermore I attached the sample project:
[iOSAppCenter.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/4425697/iOSAppCenter.zip)

The project was build as guided in the tutorial:
https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin

0) Visual Studio for Window -  Created a iOS Project - **compilation without errors**

1) Visual Studio for Windows
    Open Visual Studio for Windows.
    Click File > Open and choose your solution.
    In the solution navigator, right-click References and choose Manage NuGet Packages.
    Search for App Center, and install Microsoft.AppCenter.Analytics and Microsoft.AppCenter.Crashes packages.

2) **after** the adding of the NuGet Packages the compilation **fails** with:
1>  Connecting to Mac server xxx.xxx.xxx.xxx
1>  iOSAppCenter -> C:\Users\xxx\Source\repos\iOSAppCenter\iOSAppCenter\bin\iPhoneSimulator\Debug\iOSAppCenter.exe
1>  Detected signing identity:
1>    Bundle Id: com.companyname.iOSAppCenter
1>    App Id: com.companyname.iOSAppCenter
1>  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/admin/Library/Caches/Xamarin/mtbs/builds/iOSAppCenter/c7645004323a6da0113026334a5daaf3/obj/iPhoneSimulator/Debug/response-file.rsp 
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(844,3): error MT0009: Error while loading assemblies: /Users/admin/Library/Caches/Xamarin/mtbs/builds/iOSAppCenter/c7645004323a6da0113026334a5daaf3/bin/iPhoneSimulator/Debug/Microsoft.AppCenter.Analytics.iOS.Bindings.dll

**Comment by olmisa** [comment] 2020-04-03 11:01
Hello @dleinius ,
I tried to build your sample project and all works fine on my environment. I was able to run ios application on Windows simulator without any error. I have installed the same soft versions as you described (VS 16.5.2 on Windows 10 with Remote Pairing to Mac with MacOS 10.15.4 and Xcode 11.4). Is it possible that Visual Studio for Mac is not fully up-to-date? I have installed the latest updates for Visual Studio for Mac.
Also, could you try to run my sample project? (
[iOSTest.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/4426669/iOSTest.zip)
)
If your Visual Studio for Mac is not fully up-to-date then could you, please, install the latest updates and try again?

**Comment by dleinius** [comment] 2020-04-03 12:23
> 
> 
> Hello @dleinius ,
> I tried to build your sample project and all works fine on my environment. I was able to run ios application on Windows simulator without any error. I have installed the same soft versions as you described (VS 16.5.2 on Windows 10 with Remote Pairing to Mac with MacOS 10.15.4 and Xcode 11.4). Is it possible that Visual Studio for Mac is not fully up-to-date? I have installed the latest updates for Visual Studio for Mac.
> Also, could you try to run my sample project? ([iOSTest.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/4426669/iOSTest.zip))
> If your Visual Studio for Mac is not fully up-to-date then could you, please, install the latest updates and try again?

Hello @olmisa,

Thanks for your help and providing the sample project. Unfortunately the compilation fails with the same error.

I run the update for the Visual Studio for Mac (on the Mac). The update mechanism updated Mono to Version 6.8.0.123 (6.8.0.99 was installed before). During the establishment with remote Mac Connection the VS 16.5.2. tried to downgrade Mono again to 6.8.0.99 - which I denied. Nevertheless the compilation still fails on the windows side with the MT0009 error mentioned above.

Any ideas?

**Comment by dleinius** [comment] 2020-04-04 17:21
Hi @olmisa,

Thanks for your suggestions.

1) I added the settings in the csproj, but still the same error during compilation.
2) Remote Management and Remote Login is enabled for all users, but still the same error.

I think the problem lies somewhere in this specific Mac (MacInCloud.com dedicated server). I was able to build the project with the Azure DevOps pipeline and a Azure hosted Build Mac. 

That is a pitty. Do you have any clue, in which direction I can proceed for analyzing the problem?

Thanks,
Daniel

**Comment by dleinius** [comment] 2020-04-06 07:30
Further troubeshooting. 

1) 
I did the compilation with Verbose for MTouch. The innerexception is a BadImageFormatException

error MT0009: Error while loading assemblies: [..]/iPhoneSimulator/Debug/Microsoft.AppCenter.Analytics.iOS.Bindings.dll
1>  --- inner exception (TaskId:127)
1>  System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid. (TaskId:127)
1>    at Mono.Cecil.PE.ImageReader.ReadImage () [0x000cc] in /Users/builder/jenkins/workspace/archive-mono/2019-10/ios/release/external/cecil/Mono.Cecil.PE/ImageReader.cs:93  (TaskId:127)
1>    at Mono.Cecil.PE.ImageReader.ReadImage (Mono.Disposable`1[T] stream, System.String file_name) [0x00007] in /Users/builder/jenkins/workspace/archive-mono/2019-10/ios/release/external/cecil/Mono.Cecil.PE/ImageReader.cs:763  (TaskId:127)
1>    at Mono.Cecil.ModuleDefinition.ReadModule (Mono.Disposable`1[T] stream, System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x00006] in /Users/builder/jenkins/workspace/archive-mono/2019-10/ios/release/external/cecil/Mono.Cecil/ModuleDefinition.cs:1146  (TaskId:127)
1>    at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0006c] in /Users/builder/jenkins/workspace/archive-mono/2019-10/ios/release/external/cecil/Mono.Cecil/ModuleDefinition.cs:1118  (TaskId:127)
1>    at Xamarin.Bundler.CoreResolver.Load (System.String fileName) [0x0009b] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/CoreResolver.cs:92  (TaskId:127)
1>  --- (TaskId:127)
1>    at Xamarin.Bundler.CoreResolver.Load (System.String fileName) [0x00115] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/common/CoreResolver.cs:104  (TaskId:127)
1>    at MonoTouch.Tuner.MonoTouchManifestResolver.Load (System.String file) [0x00041] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/AssemblyResolver.cs:35  (TaskId:127)
1>    at Xamarin.Bundler.Target.Initialize (System.Boolean show_warnings) [0x000ef] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Target.cs:288  (TaskId:127)
1>    at Xamarin.Bundler.Application.Initialize () [0x007ec] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:1347  (TaskId:127)
1>    at Xamarin.Bundler.Application.BuildInitialize () [0x00008] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:894  (TaskId:127)
1>    at Xamarin.Bundler.Application+<>c.<BuildAll>b__147_0 (Xamarin.Bundler.Application v) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:848  (TaskId:127)
1>    at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x0001e] in <5af71a3f034041b7a582d7d0de9be721>:0  (TaskId:127)
1>    at Xamarin.Bundler.Application.BuildAll () [0x00023] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/Application.cs:848  (TaskId:127)
1>    at Xamarin.Bundler.Driver.Main2 (System.String[] args) [0x00433] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/mtouch.cs:1340  (TaskId:127)
1>    at Xamarin.Bundler.Driver.Main (System.String[] args) [0x00015] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/tools/mtouch/mtouch.cs:849  (TaskId:127)
1>  The command exited with code 1. (TaskId:127)
1>  MTouch: 2020-04-06T09:14:09.5700927+02:00 - Finished (TaskId:127)
1>Done executing task "MTouch" -- FAILED. (TaskId:127)

**Comment by olmisa** [comment] 2020-04-06 10:28
Hi @dleinius 
it doesn't look like the App Center SDK issue.  The possible exception conditions described here https://docs.microsoft.com/en-us/dotnet/api/system.badimageformatexception?view=xamarinios-10.8 . If it is a bug (not a configuration issue) then, in my opinion, the issue should be created for the Xamarin team. 
So, I'm closing this issue now, please reopen/comment if you have more questions.
Thanks

**Closed by olmisa** 2020-04-06 10:28 UTC

**Comment by dleinius** [comment] 2020-04-06 10:41
@Olmisa - nevertheless, thank you for your help so far
