### ISSUE TITLE
AppCenter assembly does not have a strong name

### ISSUE THREAD

**Issue by jozefizso** [microsoft/appcenter-sdk-dotnet#1325] opened 2020-02-13 13:36 UTC
### **Description**

When I build the project which uses AppCenter SDK, I get this warnings during build:

```
1>CSC : warning CS8002: Referenced assembly 'Microsoft.AppCenter, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
1>CSC : warning CS8002: Referenced assembly 'Microsoft.AppCenter.Analytics, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

When I run the application which uses this SDK, the application crashes with this error:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AppCenter, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create .NET project
2. Reference AppCenter SDK
3. Enable strong name for the project
4. Build the project

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Windows
2. Which SDK version are you using?
    - 2.6.4
4. Which OS version did you experience the issue on?
    - Windows 10
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Windows 10 PC
6. What third party libraries are you using?
    - none

**Comment by MatkovIvan** [comment] 2020-02-13 16:38
Duplicate of #1092

**Closed by MatkovIvan** 2020-02-13 16:38 UTC
Labels: support
