### ISSUE TITLE
iOS 8 is not supported anymore

### ISSUE THREAD

**Issue by shivsnathan** [Microsoft/AppCenter-SDK-DotNet#619] opened 2018-03-14 08:50 UTC
Getting this warning after updating Microsoft.AppCenter to 1.5.0.

**Comment by MatkovIvan** [comment] 2018-03-14 10:50
Hi.

Thanks for getting in touch.
The version 1.3.0 and newer requires iOS 9 or later.
Please make sure that your project matches that requirement.

Best,
Ivan

**Comment by shivsnathan** [comment] 2018-03-14 13:54
Thanks for your reply.

When I was using 1.4.0 I never got any linker warning regarding the version. It was working fine.

_MT5203: Warning: warning: object file (/Users/sivaramalingams/Workspace/ProjSln/Proj.iOS/obj/iPhoneSimulator/Debug/device-builds/iphone10.4-11.2/mtouch-cache/AppCenter.a(MSIngestionSender.o)) was built for newer iOS version (9.0) than being linked (8.0) (Proj.iOS) Native linking_

I have got around 116 similar kinds of warnings after updating to 1.5.0.

**Comment by guperrot** [comment] 2018-03-14 18:00
Have you tried a full clean build (some obj/bin folders stay even after clean solution)? Unable to repro here.

**Comment by shivsnathan** [comment] 2018-03-15 05:40
I have changed my deployment target to iOS 9.0, trashed bin/obj folders and rebuild the project, warning disappeared.
Still, no luck when the deployment target is iOS 8.0.

**Comment by guperrot** [comment] 2018-03-15 21:49
Hi yes this is by design as we removed support for iOS 8.0 recently.

**Comment by shivsnathan** [comment] 2018-03-17 04:39
Thanks for your info.

**Comment by guperrot** [comment] 2018-03-19 18:02
Instead of closing, we can keep this open for better visibility about the change. I renamed title.

**Comment by guperrot** [comment] 2018-05-18 20:08
Closing again now that most people updated the SDK, can still reply to a new issue if someone asks.

**Closed by guperrot** 2018-05-18 20:08 UTC
Labels: known-issue
