### ISSUE TITLE
StorageException

### ISSUE THREAD

**Issue by nabeelio** [microsoft/appcenter-sdk-dotnet#1551] opened 2021-08-08 02:11 UTC
Hello,

WPF app, clients are randomly getting this error. It's an uncaught exception and I'm just unwinding it before, funnily enough, reporting it AppCenter (otherwise what got reported was the AggregateException).

```
08-07 18:06:21|ERROR; UncaughtException::System.AggregateException
08-07 18:06:21|ERROR; UncaughtException:: (unwind) Microsoft.AppCenter.Storage.StorageException
08-07 18:06:21|ERROR; UnhandledException StackTrace :    at Microsoft.AppCenter.Storage.Storage.<>c__DisplayClass32_0`1.<AddTaskToQueue>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AppCenter.Storage.Storage.<FlushQueueAsync>d__35.MoveNext()
```

It's .NET 4.8, using 4.3.0. I was thinking of deleting the sqlite db file (manually building the path with the install ID) when encountering this error but it's not crashing the app and I'm not sure how the library will react if that file just disappears (not very well I would guess)

Also, please consider https://github.com/microsoft/appcenter-sdk-dotnet/issues/1354, it's been open for a long time. I hate having to ship sqlite and all of the trouble of shipping it just for this dependency; I might move to Raygun just to avoid the hassle. sqlite still is causing issues which are preventing me from migrating to .net core because I want to do a single-file publish. And now that we've hit the mid-2021 in that issue... I hope this is on the map

Thanks!

**Comment by DmitriyKirakosyan** [comment] 2021-08-09 16:41
Hi @nabeelio 

Thanks for reaching out!
Could you please clarify some details about your app. Is it WPF or something else? What third party libraries are you using?

Do you have any clue when this error could happen? Some specifics of your app and its usage? Small storage size? Being long time offline? Storing big files as attachments?
Do you have any analytics in your app that could help to identify the root cause?

Meanwhile it is hard to investigate this issue without additional details.

Regarding the #1354 issue, thank you for bumping it! I'll address the question to our PMs.

**Comment by nabeelio** [comment] 2021-08-09 18:52
Hi @DmitriyKirakosyan, yeah I'm sorry it's so light on details. It's not even being reported through AppCenter, but through Raygun. It's a WPF app - I'm thinking it's some threading issue, with a smaller DB. 3rd party libraries - there are a lot of them. It's a rare issue that seems to only affect a couple of customers, but it seems to happen on startup when the AppCenter is initializing. But I figured if I posted here, someone else might recognize the issue or something it had come up, and I guess suggestions on how to get some more information to be able to debug? I'm trying to figure out who exactly the client is where this is happening so I can maybe get the sqlite db itself to see if that has any clues.

And yeah #1354 would be great!

**Comment by DmitriyKirakosyan** [comment] 2021-08-09 22:14
@nabeelio, that would be great if you could find more details about the affected clients and even better if you could get the DB details. Please let us know if you find more info.

Let's keep this issue open for now.

**Comment by tomaustin700** [comment] 2021-09-16 13:49
Hi,
We are seeing this also, we've raised similar issues in the past (#1530 and #1423).

**Comment by AnastasiaKubova** [comment] 2021-09-16 16:39
Hi! thanks for getting in touch with us! Could you please share the [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/wpf-winforms#adjust-the-log-level) and repro steps of this issue?

**Comment by tomaustin700** [comment] 2021-09-17 07:26
Hi @AnastasiaKubova,
This is coming from our clients and we've never really been able to duplicate it locally. If you look at the two issues I linked in ym comment it goes into more detail.

Thanks

**Comment by AnastasiaKubova** [comment] 2021-09-17 07:35
@tomaustin700, both issues which you linked were fixed and I'm not sure that the current issue is similar. Unfortunately, we can't reproduce this issue from our side and we need more info about this issue (repro steps or verbose logs). If you have a chance to share with us this information it will be very helpful in investigating this issue.

**Comment by DmitriyKirakosyan** [comment] 2021-12-01 13:38
Hi @nabeelio and @tomaustin700 , just a friendly ping, were you able to find a way to reproduce this issue?

**Comment by nabeelio** [comment] 2021-12-01 14:08
Hi @DmitriyKirakosyan , I haven't seen any more reports of this come through

**Comment by nabeelio** [comment] 2021-12-01 14:09
Hi @DmitriyKirakosyan , I haven't been able to, it seems like it's just the same couple of clients. But I just ignore them now because it doesn't seem to have any bad effects.

**Comment by tomaustin700** [comment] 2021-12-01 14:16
Hi @DmitriyKirakosyan, we were never able to duplicate it either - we only see it from some of our clients unfortunately.

**Comment by AnastasiaKubova** [comment] 2021-12-02 06:32
Hi there! Unfortunately without additional information will be difficult to figure out what exactly happens wrong. I'm going to close this issue, but feel free to reopen it if you will have additional questions or information about this issue.

**Closed by AnastasiaKubova** 2021-12-02 06:32 UTC
Labels: support
