### ISSUE TITLE
Support handled exceptions for UWP apps

### ISSUE THREAD

**Issue by guperrot** [microsoft/appcenter-sdk-dotnet#669] opened 2018-05-16 00:47 UTC
`Crashes.TrackError` is currently not supported in UWP applications.

As mentioned in https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/140#issuecomment-389319219, there is no short term plan to support the missing feature.

**Comment by brycehutchings** [comment] 2018-05-16 05:54
I have been really happy with everything about App Center except for this missing feature. It really is important. It's ironic that I get more data when my app crashes than when I catch an exception. I'm almost tempted to allow the app to crash just to get the stacktrace.

**Comment by mjfara** [comment] 2018-06-21 19:01
Is this some kind of joke? Microsoft, you want us to treat UWP as a first class citizen yet your own services can't even provide basic analytics functionality for your own platform? This issue was brought up over a year ago and there's still no resolution or not even a "short term plan to support the missing feature". Incredibly disappointing, this just further adds to the regret I feel for investing in UWP.

**Comment by mfe-** [comment] 2018-06-22 15:48
Greetings, I'm also looking forward to the UWP support.

**Comment by nmilcoff** [comment] 2018-10-17 14:57
The issue description should probably be edited, since apparently there are no short term plans to include this feature in UWP :(

**Comment by elamalani** [comment] 2018-10-19 17:21
@nmilcoff Unfortunately, it is not in our mid-term roadmap (3-5 months) to support this feature in UWP SDK.

**Comment by asierpn** [comment] 2018-11-16 12:20
I've received an email announcing that HockeyApp will be retired on November 16, 2019. How will I log crashes for UWP after that date?

**Comment by mfe-** [comment] 2018-11-16 12:29
It's strange that `Crashes.TrackError` isn't implemented. On the other side, installing the nuget package `Microsoft.AppCenter.Crashses` tracks somehow exceptions, which can be viewed in the appcenter.ms in the menu `Diagnostics`.

**Comment by winnieli1208** [comment] 2018-11-16 18:18
Thank you all for the feedback! We understand this is not an ideal experience and are actively investigating what work is needed to support UWP developers. Unfortunately, we don’t have a committed time frame yet but we have a year to retire HockeyApp and our focus is to prioritize the customer feedback we receive to ensure a smooth transition. Your feedback helps our team better prioritize features as we are dedicated to improving this experience. Thank you for your support and patience!

**Comment by mieliespoor** [comment] 2018-11-29 21:54
Yes please prioritise this! We need to migrate, but there is no point in migrating if we can't log and exception from a try...catch block. I am not willing to let my app crash just to get some crash logs.

**Comment by alekkowalczyk** [comment] 2019-01-03 14:22
This is a big road-block for using app center :/

**Comment by winnieli1208** [comment] 2019-01-29 22:53
Hi there,

Quick update from my prevsious comment: we have now committed to fully supporting UWP and WPF in App Center diagnostics (meaning all the features we offer for App Center diagnostics on other platforms will be implemented for UWP and WPF, with the possible exception of handled errors). We will continue to evaluate the priority of supporting errors for Windows and update the community if we have any news. 

We expect to start working on Windows in around March and I'll post here for any updates (along with our [App Center roadmap](https://docs.microsoft.com/en-us/appcenter/general/roadmap#diagnostics)/changelog). Thank you all for your patience!

**Comment by andrewleader** [comment] 2019-02-07 05:50
AppCenter is pointless to me if it doesn't support handled errors. All I use it for is telemetry, not distribution or testing. I just wish I had the functionality of HockeyApp back (and looks like I'll have to stay on there for even longer).

**Comment by winnieli1208** [comment] 2019-02-09 00:42
Hi @andrewleader - we are committed to supporting unhandled exceptions (crashes) for UWP/WPF apps in App Center and are considering supporting handled errors as well.

We decided to commit to supporting crashes first since HockeyApp doesn't support handled errors. I'll keep this thread updated if anything changes. Thanks!

**Comment by WilliamABradley** [comment] 2019-02-09 01:17
@winnieli1208 HockeyClient has a TrackException function that allowed you to report handled errors.

**Comment by nguyenquyhy** [comment] 2019-02-09 01:34
@winnieli1208 I have been tracking handled exception in my apps with HockeyApp for years. Lacking that is a huge blocker in migrating to AppCenter.

**Comment by asierpn** [comment] 2019-02-11 11:32
The title of this issue is clear, it's about supporting handled exceptions, unhandled exceptions for UWP apps are already supported in App Center.

**Comment by winnieli1208** [comment] 2019-02-14 05:44
Hi @WilliamABradley - HockeyApp does not support handled exceptions, only unhandled exceptions for UWP apps. The instructions in the [HockeyApp documentation](https://support.hockeyapp.net/kb/client-integration-windows-and-windows-phone/crash-reporting-for-uwp) are only for unhandled exceptions.

I confirmed this again with our team and the engineers who originally worked on HockeyApp mentioned that customers have previously added support themselves with some reverse engineering. HockeyApp's SDK provides no support for handled exceptions out of the box.

@nguyenquyhy thank you for the feedback! We're actively monitoring requests to help our team better prioritize this feature. I will let you know when I get more details on an ETA. 

@asierpn - great point, I'll ask our team admin to change the name of the issue. We do support unhandled exceptions for UWP however there are many [limitations](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp) at the moment and we are looking to improve this in the next few months. 

We understand this is an important feature for many of you and our team is really focused on ensuring a smooth HockeyApp transition experience. I encourage you all to continue sharing your feedback and requests. Thank you all for your patience!

**Comment by nguyenquyhy** [comment] 2019-02-14 07:09
I was quite OK waiting for the TrackException to be implemented in AppCenter because I understand that any migration takes time and there are always priorities to be made.

However, the excuse given by @winnieli1208 and whoever engineer in the previous reply is simply too irresponsible and bizarre for a company at the scale of Microsoft.

After so many people in this thread confirmed that HockeyApp support tracking handled exceptions with TrackException API, I would expect Microsoft to at least have the courtesy to check their assumption. Instead, Microsoft pushes the support to customers for ` added support themselves with some reverse engineering`.

For your information, I am using the nuget packages from https://www.nuget.org/packages/HockeySDK.UWP, which can also be downloaded from https://www.hockeyapp.net/releases. Are you saying that those packages are from customers although the author is stated as Microsoft? Have you ever tried to at least look at the TrackException in that package that people have been talking about?

This is hugely disappointed and I now start to doubt the seriousness of Microsoft on supporting UWP on their new AppCenter.

**Comment by asierpn** [comment] 2019-02-14 11:48
@winnieli1208 the engineers who informed you are wrong, Hockey App support UWP handled exceptions, I'm using it for years. and the goal of this ticket is to support it in App Center, because Hopckey App will be retired on November and we don't know how we will track handled exceptions for our UWP apps after that date. This answer is unacceptable after 9 months waiting news about supporting handled exceptions.

**Comment by alekkowalczyk** [comment] 2019-02-14 12:49
Also it seems AppCenter doesn't track for me unhandled exceptions in UWP, might it be related to the fact that I already try to handle exceptions globally by subscribing to the `UnhandledException` event in the `App.xaml.cs`?
Asking because in case of xamarin unhandled exceptions were not tracked when I subscribed to the `AndroidEnvironment.UnhandledExceptionRaiser` event in the Droid project (side note - also nowhere documented  and took some time to find out)

**Comment by andrewleader** [comment] 2019-02-14 15:31
Yeah @winnieli1208, as everyone here has told you, you're misinformed and HockeyApp DOES support handled exceptions. That's why we're all so vocal, since we need parity with what we were using in HockeyApp.

**Comment by andrewleader** [comment] 2019-02-14 15:42
Here's proof from my app... I'm using NuGet package: HockeySDK.UWP

```csharp
HockeyClient.Current.TrackException(ex);
```

Zero reverse engineering required. There's a method available directly in the SDK, and it works, and has been working for years.

**Comment by lumaxis** [comment] 2019-02-14 22:49
@nguyenquyhy @andrewleader Hey all! I'm one of the original HockeyApp engineers that @winnieli1208 mentioned 👋🏼 🙂

We obviously hear the dissatisfaction you're voicing about the lack of handled exception support in App Center today but Winnie's original statement was still correct. HockeyApp has never officially supported handled exceptions for any platform. While it might technically be possible to send handled exceptions, it is not a scenario we document or encourage users to do.

Additionally, HockeyApp has some technical limitations, such as a 60 requests per minute per app rate limit, that restrict the way this is possible. See also this comment by a former colleague: https://github.com/bitstadium/HockeySDK-Windows/issues/41#issuecomment-211813649

The part about having to reverse engineer the crash report format got indeed lost in communication a bit, it applies to all other platforms but as you correctly noted, obviously not to UWP. Sorry about that!

**Comment by asierpn** [comment] 2019-02-15 10:38
@winnieli1208 @lumaxis At this point, if HockeyApp never officially supported handled exceptions, you will retire it on November without providing any alternative from Microsoft to track exceptions of UWP apps? How will we maintain the quality of our applications without a tool to register errors? What should we do? Migrate from UWP to WPF or Windows Forms? Find a third-party tool for UWP that doesn't exist right now?

**Comment by mieliespoor** [comment] 2019-02-16 22:14
@lumaxis @winnieli1208  I understand what you are saying, but weather or not HockeyApp officially supports handled exceptions, is a moot point because the SDK provided does allow for it, so from my point of view - it is supported.

The fact remains that AppCenter, in it's current form, is close to worthless for me as an UWP app developer. I don't have the most used app in the store, but it is being used and I would like to track how it is being used and where and when it fails.

The one part I don't understand is how this can be so difficult to support. If you can track unhandled exceptions (crashes), so should be able to track handled exceptions without much effort as they are essentially the same thing.

Also, with the possible backing of Application Insights, I don't really understand why this is such a big issue.

**Comment by MartinRichards23** [comment] 2019-02-22 12:58
This is the only feature you should be working on.

**Comment by AdamSzofran** [comment] 2019-02-28 06:09
Yes please for UWP apps thank you!

**Comment by dpaulino** [comment] 2019-03-06 07:58
I really really really want this feature.

**Comment by winnieli1208** [comment] 2019-03-06 19:25
Thank you for all the feedback. As some of you may know, we are currently tracking feature requests in our App Center repo and are continuously monitoring these requests to help our team prioritize. I've created a [sepearte issue](https://github.com/Microsoft/appcenter/issues/150) and encourage all of you to give it a +1. This will help our team decide which features to work on in our next iteration plan.

Thanks!

**Comment by jrahma** [comment] 2019-08-25 18:16
I am also getting:

**Microsoft.AppCenter.Crashes.TrackError Obselete and not available**

Hope this will be fixed soon

**Comment by winnieli1** [comment] 2019-10-28 21:00
Handled exceptions support for UWP apps was added as part of the SDK release last week. 

You can find docs here: https://docs.microsoft.com/en-us/appcenter/sdk/crashes/uwp#handled-errors

**Closed by winnieli1** 2019-10-28 21:00 UTC
Labels: feature request

**Comment by andrewleader** [comment] 2019-10-31 17:02
Just switched my app from HockeyApp to the new SDK with handled exceptions, it's working great!! Thanks so much App Center team and @winnieli1!

**Comment by asierpn** [comment] 2019-11-07 17:51
@winnieli1 in this blog post you say that you have included crash and error reporting for sideloaded UWP apps, this means that apps deployed through Microsoft Store are not supported?

**Comment by guperrot** [comment] 2019-11-07 20:34
@asierpn we do support Microsoft Store apps as well, it just requires to upload symbols from store.
Here are the instructions how to get the store version symbols: https://docs.microsoft.com/en-us/appcenter/diagnostics/windows-support#symbols-for-applications-published-to-the-microsoft-store.

**Comment by asierpn** [comment] 2019-11-08 09:53
@guperrot thanks for the clarification, We've an issue at this moment causing that UWP errors reported in App Center are not symbolicated, and I was confused after reading that blog post. We have reported this issue through App Center portal.
