### ISSUE TITLE
MAUI .NET8 cannot deploy to remoted iOS Simulator - linker issues

### ISSUE THREAD

**Issue by InquisitorJax** [microsoft/appcenter-sdk-dotnet#1766] opened 2023-11-17 15:28 UTC
### **Description**

Visual Studio for Windows fails to deploy a .NET 8 MAUI application with appcenter nuget references 
Fails with:
"building for iOS Simulator, but linking in object file built for iOS, file '/Caches/Xamarin/mtbs/builds/MauiAppCenter/e24305ae661a16c3ebb22c185a50ddc8895a95ee4077bb074065d392da627c09/obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/AppCenter.a'"

"clang: error: linker command failed with exit code 1 (use -v to see invocation)"

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. On latest VS for Windows - create a new .NET MAUI Applicatio
2. Deploy to a remoted iOS Simulator on a Mac build agent - works
3. Now add the app center Crashes and Analytics nugets (5.0.3)
4. Try and deploy to the simulator again - will fail with above linker error

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - .NET MAUI
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET 8
2. Which SDK version are you using?
    - 5.0.3
5. Which OS version did you experience the issue on?
    - e.g. iOS 15 Simulator

**Comment by DmitriyKirakosyan** [comment] 2023-11-20 07:24
Hi @InquisitorJax , thank you for reaching out! I'm going to close this issue as a duplicate of https://github.com/microsoft/appcenter-sdk-dotnet/issues/1755. For updates and further discussion, please refer to the original thread.

**Closed by DmitriyKirakosyan** 2023-11-20 07:24 UTC
Labels: support
