### ISSUE TITLE
Error while tracking an exception in Release Mode

### ISSUE THREAD

**Issue by DDHSchmidt** [microsoft/appcenter-sdk-dotnet#1617] opened 2022-01-12 14:35 UTC
### **Description**

Hello,
we received feedback about our Xamarin Forms app crashing on testers' machines that we could only reproduce with the Release-builds of our app.
The crashes only occurred for UWP testers

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a Xamarin.Forms app with a UWP target
2. Setup AppCenter Initialization
3. Use Microsoft.AppCenter.AppCenter.Crashes.Crashes.TrackError method with exception & properties parameter
4a. In Debug mode, Appcenter will track/report the error
4b. In Release mode, the TrackError() call will result in an exception

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin Forms 5 (SR 8)
    - AppCenter.Crashes (4.4.0)
    - UWP (Testers' machines usually run Win 10, Version 21H1)
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - We're using .NET standard 2.0.
2. Which SDK version are you using?
    -  4.4.0
4. Which OS version did you experience the issue on?
    - Windows 10, 21H1
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Physical desktop machines
6. What third party libraries are you using? 
    - A lot. Sorry if I can't provide them here, right now. If you think it's relevant, I'll do my best to supply the complete list later

Furthermore, when we wrap the call to TrackError in a try-catch-block, we got the following message/stacktrace:
```
Exception during AppCenter.TrackError|System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1) + 0x9d
   at System.Linq.ImmutableArrayExtensions.First[T](ImmutableArray`1, Func`2) + 0x1ac
   at Microsoft.AppCenter.Crashes.Utils.ErrorLogHelper.ImageToBinary(IntPtr) + 0x1bb
   at Microsoft.AppCenter.Crashes.Utils.ErrorLogHelper.ProcessException(Exception, Exception, Dictionary`2) + 0x703
   at Microsoft.AppCenter.Crashes.Utils.ErrorLogHelper.CreateModelExceptionAndBinaries(Exception) + 0x7a
   at Microsoft.AppCenter.Crashes.Crashes.InstanceTrackError(Exception, IDictionary`2, ErrorAttachmentLog[]) + 0x137
   at Microsoft.AppCenter.Crashes.Crashes.PlatformTrackError(Exception, IDictionary`2, ErrorAttachmentLog[]) + 0x74
   at Microsoft.AppCenter.Crashes.Crashes.TrackError(Exception, IDictionary`2, ErrorAttachmentLog[]) + 0x79
```

On further analysis of the Appcenter SDK's source code we saw that StackTraces for exceptions were scanned for Frames that contained native images and added the following logging for all exceptions that were to be handled by TrackError:
```
var frames = new StackTrace(exception, true).GetFrames();
logger.Info($"LoggingService.Log 3.1) - Frames: {frames?.Length} / NativeImage: {frames[0]?.HasNativeImage()}");
```

Output for exceptions in DebugMode:
`2022-01-12 12:51:20.4628|INFO|LoggingService.cs|LoggingService.Log 3.1) - Frames: 12 / NativeImage: False`
Output for exceptions in ReleaseMode:
`2022-01-12 12:48:46.2581|INFO|LoggingService.cs|LoggingService.Log 3.1) - Frames: 19 / NativeImage: True`

We presume that Appcenter falsely assumes the existence of an image in the exception's first frame and crashes because of that.

**Comment by AnastasiaKubova** [comment] 2022-01-12 17:42
Hi! Thanks for getting in touch with us! I tried to reproduce this issue but for me all work well. Could you please share a sample project where this issue is reproduced?

**Comment by DDHSchmidt** [comment] 2022-01-13 16:58
Thank you for your answer.
I tried to create a simple reproduction project, but as I feared: The error is not reproducible in a simple environment and I presume the complexity of our solution (20+ projects with some dozen NuGet dependencies) heavily factors into this erratic behavior. It also doesn't help that it only occurs when testing a Release build, which begs the question if an optimization runs havoc :/

But I will try to present more information. I extended our logging class with the following code/methods:
```csharp
public async Task Log(Exception exception)
	{
		#region extendedLogging
		var logger = this.GetLogger();
		var serializerSettings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All, TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Full, CheckAdditionalContent = true };
		var serializedEx = JsonConvert.SerializeObject(ex, serializerSettings);
		logger.Info("Exception.Message = " + exception.Message);
		var frameCnt = 0;
		foreach(var frame in new StackTrace(ex, true).GetFrames())
		{
			logger.Info($"Serialized Exception Frame #{frameCnt}= " + JsonConvert.SerializeObject(frame, serializerSettings));
			logger.Info($"Serialized Exception Frame #{frameCnt}.HasNativeImage() = {frame.HasNativeImage()}");
			if(frame.HasNativeImage())
			{
				var nativeImgBase = frame.GetNativeImageBase();
				ImageToBinary(nativeImgBase);
			}
			frameCnt++;
		}
		#endregion
		Crashes.TrackError(ex);
	}
	
	private unsafe void ImageToBinary(IntPtr imageBase)
	{
		var logger = this.GetLogger();
		logger.Info($"ImageToBinary: imageBase = {imageBase.ToInt64()}");
		var imageSize = GetImageSize(imageBase);
		using (var reader = new PEReader((byte*)imageBase.ToPointer(), imageSize, true))
		{
			var debugdir = reader.ReadDebugDirectory();
			logger.Info($"ImageToBinary: debugDir.Length = {debugdir.Length}");
		}
	}
```

The first lines of RELEASE output being:
```
2022-01-13 15:18:24.4569|INFO|LoggingService.cs|Exception.Message = "The request failed: The submitted credentials are invalid."
2022-01-13 15:18:24.4586|INFO|LoggingService.cs|Serialized Exception Frame #0= {"$type":"System.Diagnostics.StackFrame, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}
2022-01-13 15:18:24.4586|INFO|LoggingService.cs|Serialized Exception Frame #0.HasNativeImage() = True
2022-01-13 15:18:24.4586|INFO|LoggingService.cs|ImageToBinary: imageBase = 140706991177728
2022-01-13 15:18:24.4586|INFO|LoggingService.cs|ImageToBinary: debugDir.Length = 0
```

The first lines of DEBUG output being:
```
2022-01-13 15:23:30.0483|INFO|LoggingService.cs|Exception.Message = "The request failed: The submitted credentials are invalid."
2022-01-13 15:23:30.0483|INFO|LoggingService.cs|Serialized Exception Frame #0= {"$type":"System.Diagnostics.StackFrame, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"}
2022-01-13 15:23:30.0483|INFO|LoggingService.cs|Serialized Exception Frame #0.HasNativeImage() = False
```

The new code closely mimics the behaviour in the original class [ErrorLogHelperPart](https://github.com/microsoft/appcenter-sdk-dotnet/blob/1473e01fd4decc901a8211ad739b61c03edc366b/SDK/AppCenterCrashes/Microsoft.AppCenter.Crashes.UWP/Utils/ErrorLogHelperPart.cs) that is referenced in our stacktrace.
The logic there says that the [first StackFrame with HasNativeImage()  = true](https://github.com/microsoft/appcenter-sdk-dotnet/blob/1473e01fd4decc901a8211ad739b61c03edc366b/SDK/AppCenterCrashes/Microsoft.AppCenter.Crashes.UWP/Utils/ErrorLogHelperPart.cs#L76) will be processed by the [ImageToBinary()](https://github.com/microsoft/appcenter-sdk-dotnet/blob/1473e01fd4decc901a8211ad739b61c03edc366b/SDK/AppCenterCrashes/Microsoft.AppCenter.Crashes.UWP/Utils/ErrorLogHelperPart.cs#L108) method which contains the lines:
```csharp
...
using (var reader = new PEReader((byte*)imageBase.ToPointer(), imageSize, true))
            {
                var debugdir = reader.ReadDebugDirectory();
                var codeViewEntry = debugdir.First(entry => entry.Type == DebugDirectoryEntryType.CodeView);
....
```

Comparing this with the log output from our Release binary shows that we do indeed have a StackFrame in our Exception with HasNativeImage() = true but **no** DebugDirectory , so the call to First() results in AppCenter crashing on us.

My suggestion would be to rewrite the lines as following:
```csharp
...
using (var reader = new PEReader((byte*)imageBase.ToPointer(), imageSize, true))
            {
                var debugdir = reader.ReadDebugDirectory();
                if(debugDir.Length == 0)
                {
                    return null;
                }
                var codeViewEntry = debugdir.First(entry => entry.Type == DebugDirectoryEntryType.CodeView);
....
```

Alas, I have no domain knowledge about StackFrames, NativeImages, PEReader and the like and am clueless if that would be a grave sin?
I'm sorry that I was unable to provide a reproduction project but I will help as best as I can to get this resolved.
Thank you.

**Comment by AnastasiaKubova** [comment] 2022-01-14 13:24
Thanks for the details. Could you please also share [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/uwp#adjust-the-log-level)?

**Comment by DDHSchmidt** [comment] 2022-01-14 15:57
Absolutely. This is the output in Release mode:
[AppCenter.log](https://github.com/microsoft/appcenter-sdk-dotnet/files/7871610/AppCenter.log)

**Comment by AnastasiaKubova** [comment] 2022-01-17 06:10
Do you use `Crashes.TrackError` for C++ exceptions in your application?

**Comment by DDHSchmidt** [comment] 2022-01-17 07:47
No, we're only using C# (.Net Standard 2.0) in our Xamarin.Forms application.
If you're refering to the ImageToBinary(IntPtr imageBase) method I mentioned earlier: That's temporary debugging code I inserted to ascertain if the similar code in AppCenter's [ErrorLogHelper class](https://github.com/microsoft/appcenter-sdk-dotnet/blob/1473e01fd4decc901a8211ad739b61c03edc366b/SDK/AppCenterCrashes/Microsoft.AppCenter.Crashes.UWP/Utils/ErrorLogHelperPart.cs) might be at fault.

**Comment by AnastasiaKubova** [comment] 2022-01-17 15:59
Hi! Thanks for the details! I'm trying to reproduce your issue, but for me still all work well.
Could you please clarify which type of exception causes this crash? Or does this issue happen for different exception types? Do you generate this exception manually? Have you a chance to share all data about this exception (in JSON format for example)?

**Comment by DDHSchmidt** [comment] 2022-01-17 18:30
Hello,
the error occurs when a user in our application enters wrong data for a login.
We use System.Net.HttpClient.PostAsJsonAsync to post the credentials to our backend service and if the service responds with anything else than "200 OK", we simply throw an exception that is as simple as: throw new Exception()

> Have you a chance to share all data about this exception (in JSON format for example)?

The [AppCenter.log](https://github.com/microsoft/appcenter-sdk-dotnet/files/7884021/AppCenter.log) file was generated using this code (ex is the variable that contains the Exception in question)
```csharp
var logger = this.GetLogger();
                var serializerSettings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All, TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Full, CheckAdditionalContent = true };
var serializedEx = JsonConvert.SerializeObject(ex, serializerSettings);
logger.Info("Serialized Exception = " + serializedEx);
var frameCnt = 0;
var stacktrace = new StackTrace(ex, true);
var serializedStack = JsonConvert.SerializeObject(stacktrace, serializerSettings);
logger.Info("Serialized Stacktrace = " + serializedStack);
foreach (var frame in stacktrace.GetFrames())
{
    logger.Info($"Serialized Exception Frame #{frameCnt}= " + JsonConvert.SerializeObject(frame, serializerSettings));
    logger.Info($"Serialized Exception Frame #{frameCnt}.HasNativeImage() = {frame.HasNativeImage()}");
    logger.Info($"Serialized Exception Frame #{frameCnt}.GetMethod() = {frame.GetMethod()}");
    logger.Info($"Serialized Exception Frame #{frameCnt}.GetFileName() = {frame.GetFileName()}");
    logger.Info($"Serialized Exception Frame #{frameCnt}.GetFileLineNumber() = {frame.GetFileLineNumber()}");
    logger.Info($"Serialized Exception Frame #{frameCnt}.GetFileColumnNumber() = {frame.GetFileColumnNumber()}");
    logger.Info($"Serialized Exception Frame #{frameCnt}.GetILOffset() = {frame.GetILOffset()}");
    logger.Info($"Serialized Exception Frame #{frameCnt}.GetNativeOffset() = {frame.GetNativeOffset()}");
    if (frame.HasNativeImage())
    {
        var nativeImgBase = frame.GetNativeImageBase();
        ImageToBinary(nativeImgBase);
    }
    frameCnt++;
}

try { Crashes.TrackError(ex, props); } catch (Exception appCenterEx)
{
    logger.Error(appCenterEx, $"Exception during AppCenter.TrackError");
}
```

As usual, all logs were generated with Xamarin.Forms on UWP in Release mode.

**Comment by AnastasiaKubova** [comment] 2022-01-18 05:53
Could you share here the full data of the exception here (for example in JSON)? I just want to compare it to understand how the problematic exception differs from the usual exception.

**Comment by DDHSchmidt** [comment] 2022-01-18 08:02
The previous log contained the result of 
```csharp
var serializerSettings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All, TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Full, CheckAdditionalContent = true };
JsonConvert.SerializeObject(ex, serializerSettings);
```

Kindly advise me what/if I need to change my serializer settings or another way to provide more information.

**Comment by AnastasiaKubova** [comment] 2022-01-19 09:36
Thanks for the code snippets. But I meant to share a model of exception that caused a crash (with stack traces, messages, thread etc. in JSON format for example). I would to see how your exception model differs and to understand what exactly goes wrong since I still cannot reproduce your issue.

**Comment by DDHSchmidt** [comment] 2022-01-21 14:54
Sorry for the late reply.
Since this discussion was going to end in a "Works on my machine, won't fix"-scenario, I pleaded with my manager to grant me more time for a different approach:
I spent the last 2 days stripping down our solution to the bare minimum that still exhibits the problem and renamed several namespaces, classes, etc.

The result is this solution: [CrossplatformTracker.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/7914487/CrossplatformTracker.zip)

Once started on UWP, the solution will show a simple Login where you only need to click on the "Login"-button (All fields are prefilled).
In **DEBUG** mode, all works well and the following 3 popups will follow:
![image](https://user-images.githubusercontent.com/67259411/150547160-2015850d-d13a-46c8-ab39-c854f2fb1137.png)
![image](https://user-images.githubusercontent.com/67259411/150547187-8596f342-81e2-4493-a749-664c5f43a891.png)
![image](https://user-images.githubusercontent.com/67259411/150547210-5d11f8c6-63be-476e-be2b-8e3e814aa0fe.png)

If you start the solution in **RELEASE** mode, only 2 popups will be presented, followed by an unrecoverable error in VisualStudio as soon as Crashes.TrackError() is invoked:
![image](https://user-images.githubusercontent.com/67259411/150547402-a4cd57bc-96e5-4dd2-b364-edb060a11b6c.png)
![image](https://user-images.githubusercontent.com/67259411/150547416-c1509dce-9549-44b6-9113-8fc3239bc076.png)
![image](https://user-images.githubusercontent.com/67259411/150547428-ac205510-9193-4fce-9b96-55ec1a0fc5bc.png)

The second popup will show you the path to a nlog.txt that will contain more info about the Exception that Crashes.TrackError() threw.
If you need more info on how that log is generated I recommend you look at the public void Log(Exception exception, IDictionary<string, string> details = null) method that is part of the LoggingService class in this solution.

**Comment by DmitriyKirakosyan** [comment] 2022-01-25 13:33
Hi @DDHSchmidt, thank you for the demo application with re reproduction steps, it helped a lot!
I was able to reproduce the issue and prepared a [draft fix](https://github.com/microsoft/appcenter-sdk-dotnet/pull/1623).

We will update this thread once the fix is released.

**Comment by DDHSchmidt** [comment] 2022-01-27 08:39
Great news, looking forward to the next release 👍

**Comment by DmitriyKirakosyan** [comment] 2022-04-28 07:46
Hi @DDHSchmidt , DotNet SDK 4.5.1 with this fix included has been successfully released!
Closing the issue.

**Closed by DmitriyKirakosyan** 2022-04-28 07:46 UTC
Labels: bug, next-release
