### ISSUE TITLE
Distribute.ReleaseAvailable callback not working

### ISSUE THREAD

**Issue by AlphaNERD-** [microsoft/appcenter-sdk-dotnet#1510] opened 2021-04-12 14:57 UTC
### **Description**

I wish to use a custom dialogue to show that a new version of my app is available. I want to do this to get access to the property `ReleaseNotesUrl` to check whether our customers phone is supposed to get an update (more on that here: #1508). Anyway the callback method i set doesn't get called. It doesn't matter whether i set it before or after using `AppCenter.Start()` and it doesn't matter whether i set it in my app's main menu or the launch activity.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create callback method
2. Set breakpoint in callback method
3. Set 'Distribute.ReleaseAvailable' callback to aforementioned callback method
4. Watch as your breakpoint is never hit...

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
Xamarin.Android

2. Which SDK version are you using?
11.1.0.17

4. Which OS version did you experience the issue on?
Android 11

5. What device version did you see this error on?  Were you using an emulator or a physical device?
Samsung Galaxy S20 FE

6. What third party libraries are you using?
Microsoft.AppCenter.Crashes 4.2.0
Microsoft.AppCenter.Distribute 4.2.0
Microsoft.NETCore.Platforms 1.1.0
NETStandard.Library 2.0.0
Xamarin.AndroidX.Activity 1.2.0.1
Xamarin.AndroidX.Annotation 1.1.0.9
Xamarin.AndroidX.Annotation.Experimental 1.0.0.9
Xamarin.AndroidX.Arch.Core.Common 2.1.0.8
Xamarin.AndroidX.Arch.Core.Runtime 2.1.0.8
Xamarin.AndroidX.Collection 1.1.0.7
Xamarin.AndroidX.Core 1.3.2.3
Xamarin.AndroidX.CustomView 1.1.0.6
Xamarin.AndroidX.DocumentFile 1.0.1.7
Xamarin.AndroidX.Fragment 1.3.0.1
Xamarin.AndroidX.Lifecycle.Common 2.3.0.1
Xamarin.AndroidX.Lifecycle.LiveData.Core 2.3.0.1
Xamarin.AndroidX.Lifecycle.Runtime 2.3.0.1
Xamarin.AndroidX.Lifecycle.ViewModel 2.3.0.1
Xamarin.AndroidX.Lifecycle.ViewModelSavedState 2.3.0.1
Xamarin.AndroidX.Loader 1.1.0.7
Xamarin.AndroidX.Migration 1.0.8
Xamarin.AndroidX.MultiDex 2.0.1.7
Xamarin.AndroidX.SavedState 1.1.0.1
Xamarin.AndroidX.VersionedParcelable 1.1.1.7
Xamarin.AndroidX.ViewPager 1.0.0.7
ZXing.Net 0.16.6
ZXing.Net.Bindings.Android 0.16.6

7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
4-12 16:54:17.421 V/AppCenter(10177): HTTP response status=200 payload={"app_name":"OwiGo-Android","app_display_name":"OwiGo Android","app_os":"Android","app_icon_url":"https://appcenter-filemanagement-distrib1ede6f06e.azureedge.net/2a2a84ec-bd55-4cd4-b8bd-fb632ac4413c/ic_launcher.png?sv=2019-02-02&sr=c&sig=RAeUy3geyavDUCZj%2FBAMkrn46e9WlTMdnbvXHK3TxP4%3D&se=2021-04-14T09%3A07%3A42Z&sp=r","release_notes_url":"https://install.appcenter.ms/orgs/S-R-Data-Service-GmbH/apps/OwiGo-Android/distribution_groups/Eastrella","owner":{"name":"S-R-Data-Service-GmbH","display_name":"S+R Data-Service GmbH"},"is_external_build":false,"origin":"appcenter","id":10,"version":"42","short_version":"1.9.11.20","size":16145725,"min_os":"4.1","android_min_api_level":"16","device_family":null,"bundle_identifier":"de.owigo.smart","fingerprint":"2579454ecb74462dead6ec503f80e184","uploaded_at":"2021-03-24T08:49:51.892Z","download_url":"https://appcenter-filemanagement-distrib3ede6f06e.azureedge.net/8fecfd39-5088-4d10-9294-df2fe55013d5/de.owigo.smart.apk?sv=2019-02-02&sr=c&sig=n96aylLrX5pzwOXnhc7p%2BT9pj0Cd5HNruJdj7stlYDg%3D&se=2021-04-13T14%3A54%3A15Z&sp=r","install_url":"https://appcenter-filemanagement-distrib3ede6f06e.azureedge.net/8fecfd39-5088-4d10-9294-df2fe55013d5/de.owigo.smart.apk?sv=2019-02-02&sr=c&sig=n96aylLrX5pzwOXnhc7p%2BT9pj0Cd5HNruJdj7stlYDg%3D&se=2021-04-13T14%3A54%3A15Z&sp=r","mandatory_update":false,"enabled":true,"is_latest":true,"release_notes":"﻿# Release notes for build OwiGo-Smart Android
**Build Number**  : 20210319.1 20210324.1

### Changes
* **ID 71724a3867dad89c7eac4dd50c35511c615ac884** CI-Projekt auf PackageReference umgestellt
* **ID 0ddd8da2f637fb03909751a2e522d9a8da139396** Versionsnummer erhöht
\r
","can_resign":null,"package_hashes":["ed5db0b71574084e4c3e321d8b73a96e080b9c61c9b732055dd7321c3c31973f"],"destination_type":"group","status":"available","distribution_group_id":"588c11a5-67c7-45c6-b995-0023fd219be6","distribution_groups":[{"id":"588c11a5-67c7-45c6-b995-0023fd219be6","name":"Eastrella","origin":"appcenter","display_name":"Eastrella","is_public":true}]}
04-12 16:54:17.423 D/AppCenterDistribute(10177): Check if latest release is more recent.
04-12 16:54:17.424 D/AppCenterDistribute(10177): Latest release more recent=true
04-12 16:54:17.430 D/AppCenterDistribute(10177): Optional updates are postponed until Tue Apr 13 14:02:29 GMT+02:00 2021
04-12 16:54:18.291 D/AppCenter(10177): triggerIngestion(group_core) pendingLogCount=1
04-12 16:54:18.292 D/AppCenter(10177): Trying to get 1 logs from the Persistence database for group_core
04-12 16:54:18.299 D/AppCenter(10177): Returning 1 log(s) with an ID, d113ea02-2cdc-4360-9ca0-f2edb91e5f80
04-12 16:54:18.300 D/AppCenter(10177): The SID/ID pairs for returning log(s) is/are:
04-12 16:54:18.300 D/AppCenter(10177): 	null / 35
04-12 16:54:18.300 D/AppCenter(10177): ingestLogs(group_core,d113ea02-2cdc-4360-9ca0-f2edb91e5f80) pendingLogCount=0
04-12 16:54:18.303 D/AppCenter(10177): checkPendingLogs(group_core) pendingLogCount=0 batchTimeInterval=3000
04-12 16:54:18.306 V/AppCenter(10177): Calling https://in.appcenter.ms/logs?api-version=1.0.0...
04-12 16:54:18.306 V/AppCenter(10177): Headers: {Install-ID=25151406-fb55-49b6-9509-824327a870cb, App-Secret=****************************e3559322, Content-Type=application/json}
04-12 16:54:18.307 V/AppCenter(10177): {
04-12 16:54:18.307 V/AppCenter(10177):   "logs": [
04-12 16:54:18.307 V/AppCenter(10177):     {
04-12 16:54:18.307 V/AppCenter(10177):       "type": "startService",
04-12 16:54:18.307 V/AppCenter(10177):       "timestamp": "2021-04-12T14:54:15.280Z",
04-12 16:54:18.307 V/AppCenter(10177):       "distributionGroupId": "588c11a5-67c7-45c6-b995-0023fd219be6",
04-12 16:54:18.307 V/AppCenter(10177):       "device": {
04-12 16:54:18.307 V/AppCenter(10177):         "wrapperSdkVersion": "4.2.0",
04-12 16:54:18.307 V/AppCenter(10177):         "wrapperSdkName": "appcenter.xamarin",
04-12 16:54:18.307 V/AppCenter(10177):         "wrapperRuntimeVersion": "11.1.0.17",
04-12 16:54:18.307 V/AppCenter(10177):         "sdkName": "appcenter.android",
04-12 16:54:18.307 V/AppCenter(10177):         "sdkVersion": "4.1.1",
04-12 16:54:18.307 V/AppCenter(10177):         "model": "SM-G780F",
04-12 16:54:18.307 V/AppCenter(10177):         "oemName": "samsung",
04-12 16:54:18.307 V/AppCenter(10177):         "osName": "Android",
04-12 16:54:18.307 V/AppCenter(10177):         "osVersion": "11",
04-12 16:54:18.307 V/AppCenter(10177):         "osBuild": "RP1A.200720.012",
04-12 16:54:18.307 V/AppCenter(10177):         "osApiLevel": 30,
04-12 16:54:18.307 V/AppCenter(10177):         "locale": "de_DE",
04-12 16:54:18.307 V/AppCenter(10177):         "timeZoneOffset": 120,
04-12 16:54:18.307 V/AppCenter(10177):         "screenSize": "1080x2186",
04-12 16:54:18.307 V/AppCenter(10177):         "appVersion": "1.9.11.0",
04-12 16:54:18.307 V/AppCenter(10177):         "carrierName": "o2 - de+",
04-12 16:54:18.307 V/AppCenter(10177):         "carrierCountry": "de",
04-12 16:54:18.307 V/AppCenter(10177):         "appBuild": "42",
04-12 16:54:18.307 V/AppCenter(10177):         "appNamespace": "de.owigo.smart"
04-12 16:54:18.307 V/AppCenter(10177):       },
04-12 16:54:18.307 V/AppCenter(10177):       "services": [
04-12 16:54:18.307 V/AppCenter(10177):         "Crashes",
04-12 16:54:18.307 V/AppCenter(10177):         "Distribute"
04-12 16:54:18.307 V/AppCenter(10177):       ]
04-12 16:54:18.307 V/AppCenter(10177):     }
04-12 16:54:18.307 V/AppCenter(10177):   ]
04-12 16:54:18.307 V/AppCenter(10177): }
04-12 16:54:18.309 I/System.out(10177): (HTTPLog)-Static: isSBSettingEnabled false
04-12 16:54:18.309 I/System.out(10177): (HTTPLog)-Static: isSBSettingEnabled false
04-12 16:54:20.504 V/AppCenter(10177): HTTP response status=200 payload={"status":"Success","validDiagnosticsIds":[],"throttledDiagnosticsIds":[],"correlationId":"9eecce96-1551-48b3-a49f-06a68f26778e"}
04-12 16:54:20.505 D/AppCenter(10177): Deleting logs from the Persistence database for group_core with d113ea02-2cdc-4360-9ca0-f2edb91e5f80
04-12 16:54:20.505 D/AppCenter(10177): The IDs for deleting log(s) is/are:
04-12 16:54:20.505 D/AppCenter(10177): 	35
04-12 16:54:20.509 D/AppCenter(10177): checkPendingLogs(group_core) pendingLogCount=0 batchTimeInterval=3000

**Comment by AnastasiaKubova** [comment] 2021-04-15 13:01
Hi, @AlphaNERD- ! Thanks for getting in touch with us! 
If you ran your app in debug mode you have to use [this method](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#xamarinforms) in the `MainActivity.cs`:
`Distribute.SetEnabledForDebuggableBuild(true);`

Also, please make sure that you register [Distribute.NoReleaseAvailable callback](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#3-execute-code-if-no-updates-are-found) before calling `AppCenter.Start`.

**Comment by AlphaNERD-** [comment] 2021-04-15 15:30
Thank you for your response. As a matter of fact i did set the property `Distribute.SetEnabledForDebuggableBuild(true);` and i set both callbacks before `AppCenter.Start`. If i do not set them, i get the update dialog. But i want my own update dialog and i can't work on that because the callback methods do not get called for some reason.

**Comment by AnastasiaKubova** [comment] 2021-04-16 05:36
Please make sure that you have the right [distribution group](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#use-private-distribution-group). By default App Center SDK uses a public distribution group. You can check the type of your group on the portal (if the group is public it should have the label `public` in the list of groups).

**Comment by AlphaNERD-** [comment] 2021-04-16 08:43
I have multiple public distribution groups. And they do work. If i do not set the callbacks, i do get an update message. However i have two problems:

1. I cannot set a distribution group within the SDK itself, which is why i wanted to use the callbacks in the first place.
2. My callback methods do not get called. I set the return value correctly but it doesn't work because my callback method simply does not get called in the first place. The breakpoint inside the method never gets hit.

Setting the `UpdateTrack` property does not give me sufficient control over who gets which update unless i force every single user to create an MS account and assign them to the corresponding group.

**Comment by Jamminroot** [comment] 2021-04-16 12:08
Hey, @AlphaNERD-, let me join the thread.

If I understand correctly, the problem is that you want to separate user groups via release details text field, but for some reason ReleaseAvailable callback won't hit, yet there IS a release available on the portal.

Feature request to be able to specify distribution groups explicitly in the code (like, select between public 2 DGs "public-1" and "public-2") is already filed.

What I wanted to clarify is:
Do you call either 
`Distribute.NotifyUpdateAction(UpdateAction.UPDATE);` or `Distribute.NotifyUpdateAction(UpdateAction.POSTPONE);` in the callback method (if you are returning "true"?
More on this [in the documentation](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#2-customize-the-update-dialog):

>Implementation notes for Xamarin.Android:
>
>As shown in the example, you must either call `Distribute.NotifyUpdateAction(UpdateAction.UPDATE);` or `Distribute.NotifyUpdateAction(UpdateAction.POSTPONE);` if your callback returns true.

Also, having a peek look at verbose logging output would really help us understand what's going on.

Can you turn verbose logging on, and, at the moment SDK checks for updates, gather logging output and paste it here?

Thanks in advance

**Comment by Jamminroot** [comment] 2021-04-20 16:26
Is the problem still relevant?
I'm closing the issue for now, but please feel free to reopen if the problem is not resolved yet.

**Closed by Jamminroot** 2021-04-20 16:26 UTC
Labels: support
