### ISSUE TITLE
AppCenter does not log the stacktrace of Windows exceptions since version 5.0.0

### ISSUE THREAD

**Issue by asierpn** [microsoft/appcenter-sdk-dotnet#1724] opened 2023-01-09 15:15 UTC
### **Description**

After upgrading to AppCenter 5.0.1 the stacktrace of the exceptions is not being logged for a Windows App SDK 1.2 app, with AppCenter 4.5.3 all works fine.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a Windows App SDK 1.2 app
2. Add AppCenter 5.0.0 nuget and configure the app to log crashes
3. Throw an exception

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Windows App SDK 1.2
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET 6
2. Which SDK version are you using?
    - 5.0.1
4. Which OS version did you experience the issue on?
    - Windows 10
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Physical
6. What third party libraries are you using? 
    - Windows App SDK

**Comment by DmitriyKirakosyan** [comment] 2023-01-10 03:45
Hi @asierpn , thank you for getting in touch!

You are creating an UWP application on the App Center Portal, right? Is it possible for you to create a WPF app as a workaround? The stacktrace should work for WPF. The problem is backend doesn't recognize the stacktrace as a UWP's stacktrace.
At this moment we don't have a dedicated MAUI Windows application.

Similar report:
https://github.com/microsoft/appcenter-sdk-dotnet/issues/1688#issuecomment-1283451272

**Comment by asierpn** [comment] 2023-01-10 08:26
Hi @DmitriyKirakosyan, yes, we use an UWP application on the App Center Portal, I tried to create a WPF app but it doesn't work either when using App Center 5.0.1. With App Center 4.5.3 it is correctly registered in both type of App Center's apps.

**Comment by DmitriyKirakosyan** [comment] 2023-01-16 05:55
@asierpn , you are right, sorry for the confusion.

We are working on the fix. I will update you on the progress.

**Comment by AnatolyPristensky** [comment] 2023-03-02 10:18
Hello @asierpn, 
The issue should be fixed now, please reopen if u still facing it.

**Closed by AnatolyPristensky** 2023-03-02 10:18 UTC
Labels: bug
