### ISSUE TITLE
WinForms apps are prevented from crashing

### ISSUE THREAD

**Issue by danAtAllworx** [microsoft/appcenter-sdk-dotnet#1104] opened 2019-08-30 13:44 UTC
### **Description**

When AppCenter is installed into a WinForms application, an unhandled exception that would have previously caused a crash will no longer crash the application. This can leave the application running in an unstable state. This is especially dangerous because there is no way for the application code to know that this has happened (see #1103) so it can't intelligently respond to the situation.

### **Repro Steps**

Using this code:

    internal class Form1 : Form
    {
        [STAThread]
        static void Main()
        {
            AppCenter.Start("id", typeof(Crashes));

            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
        }

        public Form1()
        {
            var button = new Button {Text = @"CRASH!"};
            button.Click += (sender, args) => throw new NotImplementedException();
            Controls.Add(button);
        }
    }

If the `AppCenter.Start()` is commented out, then clicking the button will cause the application to crash. With the `AppCenter.Start()` there, clicking the button seems to do nothing. The application continues to run normally.

Even more confusing is that (because of the way AppCenter works) no crash report is sent until the application is manually restarted. This could result in multiple crash reports being queued up for different crashes over an arbitrarily long period of time (days??) before the application is finally restarted, at which point there will be multiple days worth of "crash" data waiting to be sent.

### **Details**

Platform: WinForms, .NET Framework 4.5.1
SDK Version: 2.3.0
OS: Windows 10

**Comment by russelarms** [comment] 2019-09-06 09:13
Hi @danAtAllworx! Thanks for reporting that, we'll look into it.

**Comment by achocron** [comment] 2019-09-06 18:56
Hey @danAtAllworx. Thank you again for bringing this up; we've been able to reproduce the issue and are working on a fix.

For your second question about crash reports not being sent until restart, this is indeed the intended behavior. In general, if the application is in a corrupted state, or crashing at all, the app won't necessarily be able to send reports properly, since the network code can take much longer than simply storing information to disk. Thus, the crashes are saved and then sent on startup.

**Comment by guperrot** [comment] 2019-09-16 22:06
Hi, we needed to change the behavior to avoid this issue.
Now our SDK will no longer subscribe to ThreadException as it has side effects on the application.
This is the documentation change that will be in the next release:

```
## Unhandled exceptions on WinForms applications

> [!NOTE]
> This section and following sub sections apply only to WinForms. You can skip this section if you are integrating the SDK on WPF.

By default, an unhandled exception in a WinForms application does not trigger a crash (the application does not exit) if the debugger is not attached.

Instead, Windows shows a dialog to the user the option to continue or quit app execution. Consequently, the App Center SDK is unable to automatically capture these exceptions (even if the user clicks on the **Quit** button).

Crashes are collected on App Center only if it causes the application to exit automatically. App Center supports only one crash per session.

There are two ways to report unhandled exceptions in WinForms. The application can be configured to crash on unhandled exceptions, or continue running but report unhandled exceptions as runtime errors.

### Configure the application to exit on crash

This is the only way to report the unhandled exception as a **crash** on App Center, make the application exit on unhandled exceptions.

To do that, simply call a Windows method before initializing the SDK:

```csharp
Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException);
AppCenter.Start(...);
```

If this option is not acceptable in your application, you can report the unhandled exception as a runtime error (described below).

### Report the unhandled exception as a runtime error

If your application must keep running after an unhandled exception, you cannot report the exception as a **crash** in App Center but you can instead report it as an **error**.

To do that, you can use the following code sample:

```csharp
Application.ThreadException += (sender, args) =>
{
    Crashes.TrackError(arg.Exception);
};
AppCenter.Start(...);
```

> [!NOTE]
> When the debugger is attached, unhandled exceptions will cause application to exit (crashes) **unless** a handler is attached to `Application.ThreadException`.
```

**Comment by guperrot** [comment] 2019-09-26 18:58
This change is now live on 2.4.0-preview.

**Closed by guperrot** 2019-09-26 18:58 UTC
Labels: bug
