### ISSUE TITLE
[macOS] "Malformed Framework" error when submitting to App Store

### ISSUE THREAD

**Issue by tipa** [microsoft/appcenter-sdk-dotnet#1620] opened 2022-01-17 07:02 UTC
First, thanks for adding macOS Support with v4.5.0 - waited for this a long time!

However, my app is now automatically rejected by the app store with the message below:

```
ITMS-90291: Malformed Framework - The framework bundle AppCenter (MyApp.app/Contents/Frameworks/AppCenter.framework) must contain a symbolic link 'AppCenter' -> 'Versions/Current/AppCenter'. Refer to the Anatomy of Framework Bundles for more information. 
ITMS-90291: Malformed Framework - The framework bundle AppCenter (MyApp.app/Contents/Frameworks/AppCenter.framework) must contain a symbolic link 'Resources' -> 'Versions/Current/Resources'. Refer to the Anatomy of Framework Bundles for more information. 
ITMS-90292: Malformed Framework - The framework bundle AppCenter (MyApp.app/Contents/Frameworks/AppCenter.framework) 'Versions' directory must contain a symbolic link 'Current' resolving to a specific version directory. Resolved link target: '${linkTarget}'. Refer to the Anatomy of Framework Bundles for more information. 
ITMS-90291: Malformed Framework - The framework bundle AppCenterAnalytics (MyApp.app/Contents/Frameworks/AppCenterAnalytics.framework) must contain a symbolic link 'AppCenterAnalytics' -> 'Versions/Current/AppCenterAnalytics'. Refer to the Anatomy of Framework Bundles for more information. 
ITMS-90291: Malformed Framework - The framework bundle AppCenterAnalytics (MyApp.app/Contents/Frameworks/AppCenterAnalytics.framework) must contain a symbolic link 'Resources' -> 'Versions/Current/Resources'. Refer to the Anatomy of Framework Bundles for more information. 
ITMS-90292: Malformed Framework - The framework bundle AppCenterAnalytics (MyApp.app/Contents/Frameworks/AppCenterAnalytics.framework) 'Versions' directory must contain a symbolic link 'Current' resolving to a specific version directory. Resolved link target: '${linkTarget}'. Refer to the Anatomy of Framework Bundles for more information. 
ITMS-90291: Malformed Framework - The framework bundle AppCenterCrashes (MyApp.app/Contents/Frameworks/AppCenterCrashes.framework) must contain a symbolic link 'AppCenterCrashes' -> 'Versions/Current/AppCenterCrashes'. Refer to the Anatomy of Framework Bundles for more information. 
ITMS-90291: Malformed Framework - The framework bundle AppCenterCrashes (MyApp.app/Contents/Frameworks/AppCenterCrashes.framework) must contain a symbolic link 'Resources' -> 'Versions/Current/Resources'. Refer to the Anatomy of Framework Bundles for more information. 
ITMS-90292: Malformed Framework - The framework bundle AppCenterCrashes (MyApp.app/Contents/Frameworks/AppCenterCrashes.framework) 'Versions' directory must contain a symbolic link 'Current' resolving to a specific version directory. Resolved link target: '${linkTarget}'. Refer to the Anatomy of Framework Bundles for more information. 
```

**Comment by AnastasiaKubova** [comment] 2022-01-17 15:25
Hi! Thanks for getting in touch with us!
I will create a bug on our board.

**Comment by AnastasiaKubova** [comment] 2022-01-19 10:11
Copied from #1622:

**Description**

When I create the build for the App Store and submit it with Transporter, I get those errors:

```
ERROR ITMS-90260: "Bad Bundle Executable. You must include a valid CFBundleExecutable key in the nested bundle AppCenter [com.labsii.speechcentralmac.pkg/Payload/SpeechCentral.app/Contents/Frameworks/AppCenter.framework] property list file."

ERROR ITMS-90260: "Bad Bundle Executable. You must include a valid CFBundleExecutable key in the nested bundle AppCenterAnalytics [com.labsii.speechcentralmac.pkg/Payload/SpeechCentral.app/Contents/Frameworks/AppCenterAnalytics.framework] property list file."

ERROR ITMS-90260: "Bad Bundle Executable. You must include a valid CFBundleExecutable key in the nested bundle AppCenterCrashes [com.labsii.speechcentralmac.pkg/Payload/SpeechCentral.app/Contents/Frameworks/AppCenterCrashes.framework] property list file."

ERROR ITMS-90261: "Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle AppCenter [com.labsii.speechcentralmac.pkg/Payload/SpeechCentral.app/Contents/Frameworks/AppCenter.framework] property list file."

ERROR ITMS-90261: "Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle AppCenterAnalytics [com.labsii.speechcentralmac.pkg/Payload/SpeechCentral.app/Contents/Frameworks/AppCenterAnalytics.framework] property list file."

ERROR ITMS-90261: "Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle AppCenterCrashes [com.labsii.speechcentralmac.pkg/Payload/SpeechCentral.app/Contents/Frameworks/AppCenterCrashes.framework] property list file."
```

**Repro Steps**

Just build any Xamarin.Mac project for the App Store and submit it with Transporter.

**Comment by kevcrooks** [comment] 2022-01-20 14:16
We're having the same "Bad Bundle Executable" errors as well, when publishing using `fastlane` via Azure DevOps (the Apple App Store Release task) - is there a known workaround yet that will still allow us to have the new AppCenter functionality for MacOS?

**Comment by Sevenish** [comment] 2022-02-03 19:15
Same issue when submitting a build with Transporter. This is now completely blocking our release.

ERROR ITMS-90260: "Bad Bundle Executable. You must include a valid CFBundleExecutable key in the nested bundle AppCenter [theapp.pkg/Payload/theapp.app/Contents/Frameworks/AppCenter.framework] property list file."

ERROR ITMS-90260: "Bad Bundle Executable. You must include a valid CFBundleExecutable key in the nested bundle AppCenterAnalytics [theapp.pkg/Payload/theapp.app/Contents/Frameworks/AppCenterAnalytics.framework] property list file."

ERROR ITMS-90260: "Bad Bundle Executable. You must include a valid CFBundleExecutable key in the nested bundle AppCenterCrashes [theapp.pkg/Payload/theapp.app/Contents/Frameworks/AppCenterCrashes.framework] property list file."

ERROR ITMS-90261: "Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle AppCenter [theapp.pkg/Payload/theapp.app/Contents/Frameworks/AppCenter.framework] property list file."

ERROR ITMS-90261: "Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle AppCenterAnalytics [theapp.pkg/Payload/theapp.app/Contents/Frameworks/AppCenterAnalytics.framework] property list file."

ERROR ITMS-90261: "Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle AppCenterCrashes [theapp.pkg/Payload/theapp.app/Contents/Frameworks/AppCenterCrashes.framework] property list file."

**Comment by AnastasiaKubova** [comment] 2022-02-04 05:58
Hi! Thanks for getting in touch with us! We are working on this issue and notify you when the issue will be resolved.

**Comment by MrAsterisco** [comment] 2022-02-13 13:30
Hello, I'm bringing up this issue again, as it looks like there hasn't been any recent activity. At the moment, it is impossible to use the AppCenter SDK in a macOS app that needs to be uploaded to the App Store.

These are the errors I get while uploading, same as the ones reported by @Sevenish:

```
ERROR ITMS-90260: "Bad Bundle Executable. You must include a valid CFBundleExecutable key in the nested bundle AppCenter [myapp.pkg/Payload/myapp.app/Contents/Frameworks/AppCenter.framework] property list file."

ERROR ITMS-90260: "Bad Bundle Executable. You must include a valid CFBundleExecutable key in the nested bundle AppCenterAnalytics [myapp.pkg/Payload/myapp.app/Contents/Frameworks/AppCenterAnalytics.framework] property list file."

ERROR ITMS-90260: "Bad Bundle Executable. You must include a valid CFBundleExecutable key in the nested bundle AppCenterCrashes [myapp.pkg/Payload/myapp.app/Contents/Frameworks/AppCenterCrashes.framework] property list file."

ERROR ITMS-90261: "Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle AppCenter [myapp.pkg/Payload/myapp.app/Contents/Frameworks/AppCenter.framework] property list file."

ERROR ITMS-90261: "Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle AppCenterAnalytics [myapp.pkg/Payload/myapp.app/Contents/Frameworks/AppCenterAnalytics.framework] property list file."

ERROR ITMS-90261: "Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle AppCenterCrashes [myapp.pkg/Payload/myapp.app/Contents/Frameworks/AppCenterCrashes.framework] property list file."
```

As this issue is completely blocking our release, I believe it should be highlighted somewhere that, while there is an SDK for Xamarin.Mac apps, **it is currently not compatible with apps distributed via the App Store**.

Also, would be great to get an ETA on when this issue might be fixed.

**Comment by DmitriyKirakosyan** [comment] 2022-02-14 07:29
Hi @MrAsterisco , we are still working on this issue. We're planning to release the fix as part of the whole dotnet sdk release at the end of this quarter.

**Comment by MrAsterisco** [comment] 2022-02-17 08:00
Thanks @DmitriyKirakosyan for updating on this. I think it'd be valuable to have this information somewhere on the AppCenter Docs, so people don't spend time implementing the SDK on apps that are targeted for the App Store.

**Comment by DmitriyKirakosyan** [comment] 2022-02-17 13:37
Hi folks, can anyone please try these nugets and verify that it works and passes the app store validation?
[AppCenterAnalyticsXamMacTest.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/8088943/AppCenterAnalyticsXamMacTest.zip)
[AppCenterCrashesXamMacTest.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/8088947/AppCenterCrashesXamMacTest.zip)

Unpack and place nugets in a single folder, then setup nuget source in Visual Studio (Preferences -> NuGet -> Sources -> Add), and install App Center Analytics and Crashes dependencies for your Xamarin Mac project from that source. The version should be `4.5.1-SNAPSHOT`.

I'll prepare a draft PR a bit later.

**Comment by Sevenish** [comment] 2022-02-17 14:40
Hi @DmitriyKirakosyan 

Unfortunately these nugets do not solve the problem. I installed them per your instructions. Cleaned the build, increased the bundle version and rebuild. Upon submitting with transporter I get the exact same validation errors from app store connect

**Comment by DmitriyKirakosyan** [comment] 2022-02-21 22:24
Hi guys, I was finally able to reproduce the bug and test the fix. Using an existing public nugets ends up with a validation error indeed, as it was reported in first comment:
```
ITMS-90291: Malformed Framework - The framework bundle AppCenter (MyApp.app/Contents/Frameworks/AppCenter.framework) must contain a symbolic link 'AppCenter' -> 'Versions/Current/AppCenter'. Refer to the Anatomy of Framework Bundles for more information. 
...
```

However, it worked for me with the fixed Nugets which I posted [above](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1620#issuecomment-1042957488). The App Store Connect validation passes successfully.

I created a sample project [Here](https://github.com/dmitriykirakosyan/testxm). Please try using it as a sample and let me know if it works for you. You will need to change the Signing information and restore Nugets using the packages I provided earlier. Let me know if you want me to push the ready-to-use packages into the sample repository.

@Sevenish If you still experience the issue with my sample, could you please share the error message and the Transporter logs please?

Thanks.

**Comment by Sevenish** [comment] 2022-02-21 23:16
I've used the test project. Put in my own apps signing details and bundle ID and tried to upload but got the exact same errors I posted before. Note that they are different error messages than the 'must contain a symbolic link' error you are mentioning. Maybe these are completely different issues? Maybe something is different in the build environment. I'm building with VS studio for mac 8.10.19 on  macOS big sur

**Comment by Sevenish** [comment] 2022-02-21 23:23
I am getting some warnings compiling the sample project:
```
/Users/sjoerd/GitRepos/testxm/TestXM/MMP: Warning MM2108: /Users/sjoerd/GitRepos/testxm/TestXM/obj/Release/mmp-cache/AppCenter.framework was stripped of architectures except x86_64 to comply with App Store restrictions. This could break existing codesigning signatures. Consider stripping the library with lipo or disabling with --optimize=-trim-architectures (MM2108) (TestXM)
/Users/sjoerd/GitRepos/testxm/TestXM/MMP: Warning MM2108: /Users/sjoerd/GitRepos/testxm/TestXM/obj/Release/mmp-cache/AppCenterCrashes.framework was stripped of architectures except x86_64 to comply with App Store restrictions. This could break existing codesigning signatures. Consider stripping the library with lipo or disabling with --optimize=-trim-architectures (MM2108) (TestXM)
/Users/sjoerd/GitRepos/testxm/TestXM/MMP: Warning MM2108: /Users/sjoerd/GitRepos/testxm/TestXM/obj/Release/mmp-cache/AppCenterAnalytics.framework was stripped of architectures except x86_64 to comply with App Store restrictions. This could break existing codesigning signatures. Consider stripping the library with lipo or disabling with --optimize=-trim-architectures (MM2108) (TestXM)
```

**Comment by Sevenish** [comment] 2022-02-22 00:14
That it! adding 
--optimize=-trim-architectures
to additional mmp arguments, recompiled and then it delivered to app store connect without errors. 
In think it was mmp stripping out m1 Architecture. although the xamarin.mac app does not ship m1 architecture. stripping it breaks the binded framework somehow

**Comment by MrAsterisco** [comment] 2022-02-22 08:13
I also got the same warnings as @Sevenish . Where did you put the `--optimize=-trim-architectures`?

**Comment by Sevenish** [comment] 2022-02-22 08:28
@MrAsterisco In the project options under 'Mac build' -> 'Additional mmp arguments'

Or you can edit the project file manually. Put in your release config:
`<MonoBundlingExtraArgs>--optimize=-trim-architectures</MonoBundlingExtraArgs>`

**Comment by DmitriyKirakosyan** [comment] 2022-02-22 09:50
@Sevenish thank you for this info. Also found this [recommendation](https://docs.microsoft.com/en-us/xamarin/mac/troubleshooting/mmp-errors#mm2108-0-was-stripped-of-architectures-except-1-to-comply-with-app-store-restrictions-this-could-break-exisiting-codesigning-signatures-consider-stripping-the-library-with-lipo-or-disabling-with---optimize-trim-architectures).
I'm wondering now what is the proper fix of this issue, whether it is normal to fix that on the app side using the flag `-trim-architectures` like you did, or we should fix this on the SDK side preventing including unwanted archs.

I'm also thinking if moving to using xcframeworks can fix the issue.

**Comment by Sevenish** [comment] 2022-02-24 08:02
I do not have much insight in how frameworks or xcframeworks work. But the build proces should not strip archs if that breaks codesiging. The whole reason this was introduced seems to be 32-bit code in the framework which also caused app store rejections. But I think the time is now that 32-bit code should probably be dropped from new framework releases anyway

**Comment by MrAsterisco** [comment] 2022-02-24 08:04
I do have quite some experience with XCFrameworks and generally, they allow you to include all the archs you want. As @Sevenish said, though, I'm not sure if they support 32bit. I tried to search a bit online, but couldn't find any reference. I guess both macOS and iOS have dropped support 32bit anymore for quite some time now, so maybe AppCenter could do the same...?

**Comment by DmitriyKirakosyan** [comment] 2022-02-24 12:17
I tried to build, archive and publish my sample app on m1 machine and managed to do it without any changes, such as using `-trim-architectures`. It just worked for me.
macOS: 12.2.1
VSfMac: 17.0 Preview
Xamarin.Mac: 8.6.0.3

@Sevenish Can you try to archive with VS for Mac preview and check if it works for you?

**Comment by Sevenish** [comment] 2022-02-24 12:39
@DmitriyKirakosyan I'm sorry, I cannot do that. I'm an indie developer with only one old slow intel mac available at the moment. (Big sur, no VS preview). Don't want to mess with my environment at this time. I will get the 2nd generation m1pro?/m2? mac mini as soon as it comes out (hopefully next month, fingers crossed) before I start experimenting with the preview

**Comment by DmitriyKirakosyan** [comment] 2022-02-25 07:23
Great news :) However, I would not recommend using SNAPSHOT version, as it is based on develop. We will notify the thread once the feature is released to the public Nugets later this quarter.

**Comment by Mephisztoe** [comment] 2022-03-03 11:19
Does this issue also affect .NET MAUI apps targetting iOS?

**Comment by AnastasiaKubova** [comment] 2022-03-03 11:52
Hi, @Mephisztoe! No, this issue affects only Xamarin Mac applications.

**Comment by mnxamdev** [comment] 2022-03-24 18:49
Hi, we are having these issues as well and is blocking a crucial update for our macOS app. Looking forward to the fix.

**Comment by mnxamdev** [comment] 2022-04-20 14:57
Any thoughts on when this will be released? @DmitriyKirakosyan said "released to the public Nugets later this quarter" on Feb 25th so I'm assuming that meant a release around March 31st but it's 3 weeks past that date now.

**Comment by DmitriyKirakosyan** [comment] 2022-04-21 05:27
@mnxamdev , We are currently working on final testing of the changes included in the release. The delay was caused by CI/CD issues.
The release should be available next week.
Thank you for you patience!

**Comment by DmitriyKirakosyan** [comment] 2022-04-28 07:42
Hi folks, DotNet SDK 4.5.1 has been successfully released!
Closing the issue.

**Comment by kevcrooks** [comment] 2022-04-28 10:33
We've confirmed this releases to TestFlight with v 4.5.1, however we also needed to add `<MonoBundlingExtraArgs>--optimize=-trim-architectures</MonoBundlingExtraArgs>` as discussed above, to avoid the `Bad CFBundleExecutable` errors when uploading with `fastlane`

**Comment by mnxamdev** [comment] 2022-04-28 22:07
Thank you for the update @DmitriyKirakosyan . Unfortunately now I get the following when trying to build from Visual Studio Mac. Didn't have this on previous version of AppCenter:

`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Shared.targets(2374,3) : error: dsymutil exited with code 1`

**Comment by tipa** [comment] 2022-04-29 10:02
@kevcrooks I was able to build & submit a build without using custom arguments (manually via VS and Transporter App) and the app successfully passed certification, however,
- the build is stuck at "processing" in the TestFlight overview
- no crashes are being logged, even when using `Crashes.CreateTestCrash()`

**Comment by kevcrooks** [comment] 2022-04-29 10:08
@tipa I also didn't get a crash using this method. I assumed at the time, that this was compiled out or ignored in release mode, but wasn't sure. However I edited the app to manually throw an exception/crash and this was correctly sent to AppCenter when testing with Test flight.

I did notice that the validation "processing" step took quite a while longer yesterday for our Mac app (maybe 5 hours or so), but it did eventually go through.

**Comment by aleksandr-dorofeev** [comment] 2022-05-02 18:07
Hi @mnxamdev 
Could you reproduce this issue on an empty project and share a test case?

**Comment by Suplanus** [comment] 2022-06-09 12:22
FYI
4.5.1 only works if I set the `--optimize=-trim-architectures`

**Comment by mnxamdev** [comment] 2022-06-09 14:09
@aleksandr-dorofeev we decided to ship without AppCenter so we ripped it out. I recall trying to recreate the issue in an empty project with the same nuget packages but recall seeing other issues and I had to move on.

Thanks @Suplanus. I had read the following line in the Microsoft MMP documentation and thought it was not ok to use this for publishing apps to the App Store:

> If the application is not being published to the App Store, this removal can be disabled by passing --optimize=-trim-architectures as Additional MMP Arguments.

Can someone explain this and let me know if --optimize=-trim-architectures is ok to use for a production app published in the App Store?

**Comment by Nick-Hughes-github** [comment] 2022-08-05 11:47
I am using the 'Transporter App' to deploy my Xamarin.Mac app to app store.  The only thing that is blocking me from doing so is the following error:

Asset validation failed (90261)
Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle AppCenter [com.XX.XXXX.pkg/Payload/XXXX.app/Contents/Frameworks/AppCenter.framework] property list file. (ID: 5f6f1f56-0e14-4201-8b6a-f8cc0982ab0b)

Despite following the instructions above, upgrading the AppCenter related NUGET packages to 4.5.1, made no difference.  Is there any other solution to resolving this issue?

Any help would be much appreciated.

**Comment by AlexeyBudynkov** [comment] 2022-08-09 14:29
@Nick-Hughes-github Hello. Have you also set the --optimize=-trim-architectures ?
Also a question, did it happen with previous versions of AppCenter nuget packages?

**Comment by Nick-Hughes-github** [comment] 2022-08-10 13:56
Hi, I was able to resolve this by uninstalling the AppCenter related NUGET packages (Manage NUGET packages...) before downloading the zip file and following the instructions detailed by @DmitriyKirakosyan, above, to manually add these packages on Visual Studio for Mac.  Strange why the the 4.5.1 version from the NuGET store doesn't behave as it should for me.

**Closed** 2022-08-11 11:17 UTC
Labels: bug, next-release
