### ISSUE TITLE
Request: Ability to use custom HttpClient

### ISSUE THREAD

**Issue by jantanis** [microsoft/appcenter-sdk-dotnet#1592] opened 2021-11-11 14:13 UTC
**Is your feature request related to a problem? Please describe.**
Unable to use a custom HttpClient right now. We are using a custom HttpClient in the app because we like to pin to SSL certificates.

**Describe the solution you'd like**
The ability to start AppCenter SDK using an already instantiated HttpClient.

**Describe alternatives you've considered**
An alternative solution would be implementing certificate pinning in the SDK itself.

**Comment by AnastasiaKubova** [comment] 2021-11-11 14:23
Could you please clarify what version of App Center SDK do you use? We added changes in the [latest release](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.4.0) related to the TLS configuration.  Do these changes solve your problem?

**Comment by jantanis** [comment] 2021-11-15 07:17
We are on 4.1.0. But I can't find what changed in 4.4.0 that would benefit us.

**Comment by AnastasiaKubova** [comment] 2021-11-15 08:36
In the previous version of App Center SDK was used the `ServicePointManager` API which hardcoded using the `TLS1.2` for network connections and did not allow to install other TLS protocols in customers' applications ([see issue](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1531)). It was fixed in the[ latest version](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.4.0) of App Center SDK. Do you have a similar issue? If no please describe your issue in more detail (with reproducing steps and code snippets if possible).

**Comment by jantanis** [comment] 2021-11-15 09:11
No, this doesn't work for us. We want to pass an instance of a HttpClient to the AppCenter SDK.

**Comment by AnastasiaKubova** [comment] 2021-11-15 09:17
Could you please describe your issue in more detail (with reproducing steps and code snippets if possible)?

**Comment by jantanis** [comment] 2021-11-15 09:30
This describes the required functionality:

```c#
public App()
        {
            InitializeComponent();
            Microsoft.AppCenter.AppCenter.LogLevel = Microsoft.AppCenter.LogLevel.Verbose;
            Microsoft.AppCenter.AppCenter.HttpClient = new System.Net.Http.HttpClient(new CustomHandler());
            Microsoft.AppCenter.AppCenter.Start("{Your App Secret}", typeof(Microsoft.AppCenter.Crashes.Crashes));
            MainPage = new MainPage();
        }
```

**Comment by AnastasiaKubova** [comment] 2021-11-15 09:57
It is not very clear to me in which case this API will be useful. Could you describe the practical application of this feature in more detail?

**Comment by jantanis** [comment] 2021-11-15 10:00
We have a requirement that all HTTPS traffic should be pinned to a certificate. So we have implemented that in a custom HttpClient. However, we cannot use that HttpClient with AppCenter SDK right now. So AppCenter traffic is not pinned to the certificate. Allowing a custom HttpClient would fix this requirement for us.

**Comment by AnastasiaKubova** [comment] 2021-11-15 10:12
Thanks for the clarification. I will add this feature request to our backlog list.

**Comment by Appiekap** [comment] 2022-10-18 12:17
Is there any update on this?

**Comment by DmitriyKirakosyan** [comment] 2022-10-19 03:05
Hi @Appiekap , no ETA for this feature because of other priorities.

**Comment by DmitriyKirakosyan** [comment] 2023-09-22 06:32
As we do not have plans to add support for this feature in the next year, I'm closing the issue.

**Closed by DmitriyKirakosyan** 2023-09-22 06:32 UTC
Labels: feature request
