### ISSUE TITLE
AppCenter.Start throws System.TypeInitializationException on MAUI Windows unpackaged app

### ISSUE THREAD

**Issue by rogerbriggen** [microsoft/appcenter-sdk-dotnet#1693] opened 2022-10-24 07:29 UTC
### **Description**

If I want to use AppCenter SDK with a MAUI unpackaged app on Windows, AppCenter.Start throws a System.TypeInitializationException

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Get https://github.com/rogerbriggen/app_center_dotnet_maui/tree/appstart_crashes_windows_upackaged_app and follow README.md

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - MAUI on Windows as unpackaged app
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - dotnet 6
2. Which SDK version are you using?
    - 5.0.0 Preview 1
4. Which OS version did you experience the issue on?
    - Windows 10
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - PC
6. What third party libraries are you using? 
    - None
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

System.TypeInitializationException
  HResult=0x80131534
  Nachricht = The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop' threw an exception.
  Quelle = Microsoft.AppCenter
  Stapelüberwachung:
   bei Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop..ctor()
   bei Microsoft.AppCenter.ApplicationLifecycleHelper.get_Instance()
   bei Microsoft.AppCenter.AppCenter..ctor()
   bei Microsoft.AppCenter.AppCenter.get_Instance()
   bei Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)
   bei app_center_dotnet_maui.App.SetupMsAppCenter() in O:\DatenP\Programmieren\repos\app_center_dotnet_maui\app_center_dotnet_maui\App.xaml.cs: Zeile33
   bei app_center_dotnet_maui.App.OnStart() in O:\DatenP\Programmieren\repos\app_center_dotnet_maui\app_center_dotnet_maui\App.xaml.cs: Zeile20
   bei Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[TDelegate](IServiceProvider services, Action`1 action)
   bei Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Application platformApplication, IApplication application, OpenWindowRequest args)
   bei Microsoft.Maui.MauiWinUIApplication.OnLaunched(LaunchActivatedEventArgs args)
   bei ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)

  Diese Ausnahme wurde ursprünglich von dieser Aufrufliste ausgelöst:

Innere Ausnahme 1:
FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Das System kann die angegebene Datei nicht finden.

**Comment by AnatolyPristensky** [comment] 2022-10-25 09:54
Hello @rogerbriggen, 
The bug is confirmed. I've created an item on our internal dashboard, will update this ticket once bug is fixed.

**Comment by dhindrik** [comment] 2022-11-15 07:43
Will the PR fix so that it works on macOS too? Because I get the same error there too. 

Is there a nightly NuGet feed so i can try it out?

**Comment by aleksandr-dorofeev** [comment] 2022-11-15 09:46
Hello @dhindrik, thanks for getting in touch with us!
Unfortunately this PR only targets windows.
Could you share the [verbose logs](https://learn.microsoft.com/en-gb/appcenter/sdk/other-apis/macos#adjust-the-log-level) and the version of macOS you are using?

**Comment by dhindrik** [comment] 2022-11-21 08:46
Attached is the output in the Application Log and info about my environment.
I have macOS 13.0.

[log.txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/10054837/log.txt)
[Visual Studio Enterprise 2022 for Mac Pr.txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/10054850/Visual.Studio.Enterprise.2022.for.Mac.Pr.txt)

**Comment by DmitriyKirakosyan** [comment] 2022-11-24 06:07
@dhindrik the original issue happening on MAUI Windows is fixed now. For the sake of clarity, may I ask you to create a separate issue for mac catalyst?

**Comment by dhindrik** [comment] 2022-11-24 06:59
I have now created #1702.

**Comment by DmitriyKirakosyan** [comment] 2022-11-24 07:24
Closing this as fixed in release 5.0.0.

**Closed by DmitriyKirakosyan** 2022-11-24 07:24 UTC
Labels: bug, next-release
