### ISSUE TITLE
Please fix your UI for exceptions and crashes

### ISSUE THREAD

**Issue by EmilAlipiev** [microsoft/appcenter-sdk-dotnet#629] opened 2018-03-31 14:00 UTC
I have been reporting such problems using button in the portal but there is no action happening. it is really painful to use app center UI comparing to xamarin insights or hockey app. I am summarizing them below once again

**Exceptions Only**:
- UI doest work on small screens like 14 inch or lower. 
- Exception properties are truncated. why should we use exception tracking if you truncate exception properties after 20 chars. Apps are running on release mode mostly without debug files and we dont get enough information. this is the only way to track down the exceptions.

- Filters resets anytime coming back to list. I want to mostly see the "Open" exceptions not "All", I filter once and if I open exception details and coming back to the list, filter is reset to "All".  
- xamarin insights shows exception with all details with 1 click, in order to see details with properties I must click 3 times on app center. Click 1: open an exception Click:2 Reports tab Click 3: See the details of exception Click 4 optional: Expand details. It might looks small problem for you but if you have dozens of exceptions, it causes you time.
 
- Exception Grouping mostly doesnt work.

**Exceptions and Crashes**

- no search within exceptions like xamarin insights has

**Comment by guperrot** [comment] 2018-04-02 19:14
Hi, thanks for your feedback. However this repository is used only to track SDK issues only but this feedback is mostly about portal experience. For non SDK issues, please create a support ticket using the blue chat button on any page of https://appcenter.ms portal next time. For this time I will forward the feedbacks to the right team.

**Comment by blparr** [comment] 2018-04-02 22:29
Hello @EmilAlipiev , thanks for your feedback. I opened up some items to improve some of your points above.

Regarding your second point, we are working right now on adding more characters for the properties, so you should see that taken care of in the next SDK release.

About "Exception Grouping mostly doesnt work." -> Can you please elaborate? What makes you think the grouping is not working properly? Can you provide detailed examples? Also, it'd be great if you open up a support item in the App Center portal with these (blue button on the right corner in the portal). That way it'll be much easier to follow up with this and involve the right folks.

Thank you,
Blanca

**Comment by EmilAlipiev** [comment] 2018-05-05 14:30
This is so disappointing. I have reported this issue probably more than 3 months a go and that it is most crucial problem we have using exception reporting but even using the latest package. you still didnt fix this. you are still truncating the error properties? how hard is to extend your database or your code. 

> Exception properties are truncated. why should we use exception tracking if you truncate exception properties after 20 chars. Apps are running on release mode mostly without debug files and we dont get enough information. this is the only way to track down the exceptions.

**Comment by blparr** [comment] 2018-05-05 18:44
@EmilAlipiev In our last SDK release, we extended the number of characters in all the properties (both custom events and error properties). Please see April 25th's update on the changelog: https://docs.microsoft.com/en-us/appcenter/general/changelog.

Best,
Blanca

**Comment by EmilAlipiev** [comment] 2018-05-06 00:38
Ok, I counted 115 chars not 125 even it is 125. I dont believe that this is sufficient amount. using xamarin forms, i was able to send entire object as json. Purpose of properties are; mobile apps are mostly without debug symbolys stacktrace information is not really helpful. so we need to pass the executing model object to unit test the function. in some cases ( even in most cases), it will be more than 125 chars. I can understand that you offer free service comparing to xamarin insights (even though it had also some free usage i believe) but you can offer something optional if anybody want to buy more storage or just connect to their own azure database etc.

**Comment by blparr** [comment] 2018-05-15 21:31
If you're seeing 115, and not 125, please reach out to us via portal support (blue button in the bottom right hand side) and we will look into it, as that is not the expected behavior.

Thanks for your feedback. For now, we increased our limits based on Xamarin Insights capabilities. We will take your feedback and take into account for future consideration.

Thanks!
Blanca

**Comment by guperrot** [comment] 2018-07-19 18:54
The SDK is truncating to 125, so this is a server issue truncating while ingesting logs or processing them. For non SDK issues please use the support portal on https://appcenter.ms via the chat button.

**Comment by guperrot** [comment] 2018-07-19 19:02
(Issue was broader than last comment so reopening based on original issue and not latest comment)

**Comment by nathanielcook** [comment] 2018-07-30 23:02
I can confirm that version 1.8 of the SDK is now letting through 125 characters instead of the previous 64, so thank you for that. 

@guperrot I think you misunderstood what I was saying. I wasn't commenting on the portal; for me the portal is correctly displaying the data is has. I was commenting on the fact that the 125 characters the SDK sends is still quite short in my opinion. For example, we have a case where we want to log a SQL query as a property in a handled exception. For that case 125 characters is still a bit short. If we could increase the max to say 500 or even 1000 characters that would be great. Obviously one would need to be careful to not abuse that. (With great power comes great responsibility.) But occasionally one needs to log something a bit lengthy.

**Comment by EmilAlipiev** [comment] 2018-07-30 23:12
@nathanielcook I agree with that. I am working with json data and mostly my json data is more than 125 chars. It was quite big help for me to analyze exceptions logging those jsons in xamarin insights. I was able to get entire log there and if i am not mistaken, hockeyapp allowed us also.

**Comment by EmilAlipiev** [comment] 2018-07-30 23:14
One point on this issue is the most important one I believe that we need a search options. most of the exceptions are not grouped for some reason although they share same stacktrace. yesterday i closed many duplicated exceptions one by one. i wish to have a simple text search and i can filter similar exceptions and close them all at once.

**Comment by DmitriyKirakosyan** [comment] 2021-12-01 14:33
Based on the message https://github.com/microsoft/appcenter-sdk-dotnet/issues/629#issuecomment-409039928, this feature is a duplicate of https://github.com/microsoft/appcenter/issues/179, so I'm going to close it now. Please track the progress in the main repo's issue.

Please feel free to reopen if you have additional questions.

**Closed by DmitriyKirakosyan** 2021-12-01 14:33 UTC
Labels: feature request
