### ISSUE TITLE
Error that my app contains a Virus when using AppCenter v. 3.4.3 with Huawei Devices & Android 8

### ISSUE THREAD

**Issue by KevinDinh97** [microsoft/appcenter-sdk-dotnet#1462] opened 2020-11-11 16:12 UTC
### **Description**

I have an app written with Xamarin Forms. When i try to install my app on a Huawei Device with Android 8 using an .apk i get the following error message:

![IMG_20201111_164630](https://user-images.githubusercontent.com/57288938/98832827-979a2a00-243d-11eb-8ceb-e1804edc548f.jpg)

This seems to be the case for all Huawei Devices with Android 8. (Tested on multiple devices)

The error message appears with AppCenter Version 3.3.0 and onwards. 
AppCenter Version 3.2.0 and downwards the error message does not appear.

### **Repro Steps**

1. Create an app with Xamarin Forms
2. Install Microsoft.AppCenter v.3.4.3 nuget package
3. Publish .apk
4. Install .apk on a Huawei Device with Android 8

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Android
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET standard 2.0.
2. Which SDK version are you using?
    - 3.4.3
4. Which OS version did you experience the issue on?
    - Android 8
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Huawei P8 Lite 2017 physical device (but errors appears on multiple Huawei Devices with Android 8 all were physical)
6. What third party libraries are you using? 
    - /
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

"logs": [
        {
          "type": "startService",
          "timestamp": "2020-11-11T16:06:46.431Z",
          "device": {
            "wrapperSdkVersion": "3.4.3",
            "wrapperSdkName": "appcenter.xamarin",
            "wrapperRuntimeVersion": "11.0.2.0",
            "sdkName": "appcenter.android",
            "sdkVersion": "3.3.1",
            "model": "PRA-LX1",
            "oemName": "HUAWEI",
            "osName": "Android",
            "osVersion": "8.0.0",
            "osBuild": "HUAWEIPRA-LX1",
            "osApiLevel": 26,
            "locale": "en_DE",
            "timeZoneOffset": 60,
            "screenSize": "1080x1794"
          },
          "services": [
            "Analytics",
            "Crashes"
          ]
        }

**Comment by Jamminroot** [comment] 2020-11-12 07:16
Hey! Thanks for bringing this to our sight. 
Can you please check if that's reproduced on 3.2.2? 3.2.1 and 3.2.2 are versions not mentioned in your report, and that would help to narrow down the cause of the problem.

**Comment by Jamminroot** [comment] 2020-11-12 07:30
Also - does that reproduce on a sample project when sideloading an apk? (Installing it via file browser on android). If so - does it reproduce on a sample project?

**Comment by KevinDinh97** [comment] 2020-11-12 10:59
Hey! Thanks for the quick reply.

The error does not appear with version 3.2.1 and 3.2.2.

On my app the error appears when i install via the file browser or the play store.

I just tried reproducing the error with a fresh sample project and it seems like i cant reproduce it there.

**Comment by Jamminroot** [comment] 2020-11-12 13:14
Ok, I see. What are the nugets you are using?

I see that you are starting the SDK with Crashes and Analytics only, but do you have Distribute module installed?

Sorry for asking so many questions, but this problem seem a bit tricky to investigate, and clear understanding of what's going on on your side would really help us shed some light onto the problem with the SDK.

**Comment by KevinDinh97** [comment] 2020-11-12 15:27
No need to apologize, im glad your helping.

I dont have the Distribute module installed.

I will have to check with a coworker if its ok to share the nugets we are using and i will get back to you then.

Thanksalot !

**Comment by Jamminroot** [comment] 2020-11-13 06:58
Sure, waiting to hear from you.

**Comment by Jamminroot** [comment] 2020-11-13 06:59
Also, there will soon be a release available, can you check if the problem is resolved with the new version?

**Comment by MatkovIvan** [comment] 2020-11-16 08:24
Hi @KevinDinh97,
Thanks for collaborating on this! I just want to emphasize that this is false-positive detection of your antivirus and currently it's not clear what the cause exactly. So, if you have any additional info (system logs etc) feel free to add it to this thread. Thanks.

**Comment by KevinDinh97** [comment] 2020-11-16 14:23
Hey Guys,

thanks again for your help.

Here the list of Nugets we are currently using in our app:

- AsyncAwaitBestPractices.MVVM
- CarouselView.FormsPlugin
- Forms9Patch
- Microsoft.AppCenter
- Microsoft.AppCenter.Analytics
- Microsoft.AppCenter.Crashes
- Microsoft.AspNetCore.WebUtilities
- Microsoft.Extensions.Hosting
- Microsoft.Extensions.Http
- Mobile.BuildTools
- Plugin.CurrentActivity
- Plugin.Fingerprint
- Plugin.FirebasePushNotification
- PropertyChanged.Fody 
- Rg.Plugins.Popup
- Sharpnado.Presentation.Forms
- Sharpnado.Shadows
- West.Extensions.Logging.AppCenter
- XFPINView
- Xam.Plugin.Iconize.Material 
- Xam.Plugin.TabView
- Xamarin.Android.Support.Compat 
- Xamarin.Android.Support.Core.UI 
- Xamarin.Android.Support.Core.Utils
- Xamarin.Android.Support.Fragment
- Xamarin.Android.Support.v7.AppCompat
- Xamarin.Essentials
- Xamarin.Essentials.Interfaces
- Xamarin.FFImageLoading.Forms
- Xamarin.Firebase.Messaging
- Xamarin.Forms
- ZXing.Net.Mobile.Forms

I havent checked yet if the problem is resolved with the new release, but i will try it soon and give an update then.

**Comment by russelarms** [comment] 2020-11-25 09:15
Hi @KevinDinh97, do you have any updates on the issue?

**Comment by Jamminroot** [comment] 2020-12-03 14:39
I'm closing the issue for now - since the trigger is false-positive. Need you further assistance - please reopen it

**Closed by Jamminroot** 2020-12-03 14:39 UTC
Labels: support
