### ISSUE TITLE
Unit Testing a .NET Standard 2.1 lib now requires creating mocks for the SDK

### ISSUE THREAD

**Issue by nmilcoff** [microsoft/appcenter-sdk-dotnet#1439] opened 2020-09-15 12:18 UTC
### **Description**

I have a .NET Standard 2.1 library which uses the AppCenter SDK. My app targets Xamarin.iOS at the moment, and I run VS for Mac. And I'm using NUnit for my unit tests. 

According to [the .NET Standard docs](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), if I want to use .NET Standard 2.1, then I have to set the target framework for my testing project to .NET Core 3. But when I do that, my tests fail with the exception:

```
{System.TypeInitializationException: The type initializer for 'Microsoft.AppCenter.Utils.ApplicationLifecycleHelper' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   --- End of inner exception stack trace ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.get_Instance()
   at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformGetInstallIdAsync()
   at Microsoft.AppCenter.AppCenter.GetInstallIdAsync()
   at MyApp.ViewModels.MyViewModel.MyMethod() in /Users/nmilcoff/Development/AzureDevOps/MyApp/MyApp.Core/ViewModels/MyViewModel.cs:line 195
   at MyApp.Core.ViewModels.MyViewModel.MyFirstMethod() in /Users/nmilcoff/Development/AzureDevOps/MyApp/MyApp.Core/ViewModels/MyViewModel.cs:line 224}
```

I guess that it is expected that WinForms is running. This exception is raised when a call to `AppCenter.GetInstallIdAsync()` is made.

**So then my question is: Is this expected? Am I missing something? Is my only alternative to create an interface and mock the implementation? If that's the case, some documentation around the topic could be very helpful 🙂.**

Note: I'm upgrading from the SDK versions v1.5, I didn't have this issue before this.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Using VS for Mac, create a new Xamarin app and install AppCenter
2. Set the target framework of the Core project to .NET Standard 2.1
3. Add a Unit Test project, set the target framework to netcoreapp3.1
4. install NUnit and add a reference to the Core project
5. Write any method that calls `AppCenter.GetInstallIdAsync()`, in Core
6. Write a unit test for that method
7. The method should fail with a similar exception

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.iOS, but there's also a Unit Test project
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - I intend to use .NET standard 2.1.
2. Which SDK version are you using?
    - Latest and greatest for everything. AppCenter SDK 3.4.1
4. Which OS version did you experience the issue on?
    - I guess .NET Core 3.1
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Test runner :)
6. What third party libraries are you using? 
    - NUnit 3
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:
I can do this if needed.

**Comment by AnastasiaKubova** [comment] 2020-09-15 13:47
Hi! Thanks for getting in touch with us. 
It may be related to the cache issue. Could you please try to remove App Center dependencies, clean the cache and re-install  App Center dependencies again. 
Please let me know about the results.

**Comment by nmilcoff** [comment] 2020-09-15 14:11
Hi Anastasia, thanks for the quick response.

I tried the following:
- Remove the AppCenter packages
- Close VS4Mac
- Clean NuGet cache by running `dotnet nuget locals all --clear`
- Reopen VS4Mac, restore packages
- Install AppCenter packages

And unfortunately I get the same result.

**Comment by AnastasiaKubova** [comment] 2020-09-16 08:41
I tried to reproduce it, but for me it works as expected. Could you please share a sample project or a code snippet with reproducing this issue?

**Comment by nmilcoff** [comment] 2020-09-16 13:47
Yes, of course, thanks for taking the time to look into this. [Here's a sample repo](https://github.com/nmilcoff/AppCenterIssueNUnitMacOS). If you run the only test that there is from VS4Mac, you should be able to reproduce it.

This is what the test results pannel looks like for me:
![imagen](https://user-images.githubusercontent.com/12127846/93346069-f2caea00-f809-11ea-8a21-ebc85f23c82c.png)

**Comment by AnastasiaKubova** [comment] 2020-09-17 05:59
Thanks for the sample project, I took a look at it.
For now, we support `.NET Core` only for the Windows platforms. An alternative way for your issue is to use `.NET Standard` in your test project since for it we have mock implementation for cross-platform projects.

**Comment by nmilcoff** [comment] 2020-09-17 12:44
Unfortunately I cannot set .NET Standard as a target framework for the tests. Neither NUnit ([ref](https://docs.nunit.org/articles/nunit/getting-started/dotnet-core-and-dotnet-standard.html#why-cant-my-tests-target-net-standard)) or xUnit ([ref](https://xunit.net/docs/why-no-netstandard)) support running tests in a library. 

You can also check that in the sample repo:

![imagen](https://user-images.githubusercontent.com/12127846/93471861-4c92e900-f8ca-11ea-878c-4a66a3f2fafc.png)

**Comment by AnastasiaKubova** [comment] 2020-09-18 05:14
Could you please try to follow [this guideline](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/touch.unit) about creating unit tests.
I checked it and it should work on your project.

**Comment by Jamminroot** [comment] 2020-09-21 14:13
Hey, @nmilcoff, thanks for sharing a sample project. Please let me some time, I'll have a look

**Comment by Jamminroot** [comment] 2020-09-23 16:55
Hey again!

We've spend some time understanding the problem with the sample project (again - that really helped speed things up, thanks).

Currently, we only support .netcoreapp for libraries only for Windows assemblies.

**Comment by MatkovIvan** [comment] 2020-09-24 08:40
Let me share a bit more details here:
Our nuget package contains multiple binaries for various target frameworks.
- .NET Core 3.0 one was added to be used with Windows Desktop only (it's added in 2.3.0).
- For shared Xamarin project we have .NETStandard 1.0 binary in the package.

In your case, NuGet picks up the binary that has Windows references, that's why it crashes.

So, changing target framework for the project or mocking this is the right way to go.

**Comment by nmilcoff** [comment] 2020-09-25 11:56
Thank you for your answers 👍. I can also confirm that mocking the SDK works perfectly fine. Is it a good idea to document this somewhere? Because the exception being raised is a bit confusing at a first glance :) 

> "Could not load file or assembly 'System.Windows.Forms'

**Comment by Jamminroot** [comment] 2020-09-25 16:12
That's probably a good point. I'll file a ticket for this to be handled.
I'm closing this conversation now, but need you further assistance on this - please feel free to reopen.

**Closed by Jamminroot** 2020-09-25 16:12 UTC
Labels: support
