### ISSUE TITLE
Not all native crashes show up in the AppCenter issues dashboard

### ISSUE THREAD

**Issue by Tommigun1980** [microsoft/appcenter-sdk-dotnet#1533] opened 2021-06-04 01:08 UTC
### **Description**

I have a Xamarin.Forms application that runs on iOS and Android. I have set up the AppCenter.Crashes package correctly, it resides both on the native side and in the platform independent project. AppDelegate.cs has the appropriate `AppCenter.Start(appSettings.AppCenterAPIKey, typeof(Crashes), typeof(Analytics));` line.

Most native crashes show up in the AppCenter issues dashboard but not all.
The SignalR client introduced an issue that crashes the app when linking is enabled ("`System.InvalidOperationException: A suitable constructor for type 'Microsoft.Extensions.Options.UnnamedOptionsManager... could not be located."`), but this crash just doesn't show up on the AppCenter issues dashboard. This issue is thrown from the platform dependent project and propagates into a native crash.

Could the AppCenter.Crashes SDK be fixed so that **all** crashes are recorded? Thank you.

### **Repro Steps**

1. Add the AppCenter.Crashes SDK (and all dependencies) to a Xamarin.Forms project, both on the native side (iOS) and on the platform independent side.
2. Initialize the SDK in AppDelegate.cs by calling `AppCenter.Start("MyAPIKEY" typeof(Crashes), typeof(Analytics));`
3. Install the latest version of Visual Studio for Mac (8.10) and add the SignalR.Client library 6.0.0-preview4 to your project.
4. Turn on linking in the project ("Link SDKs").
4. Call Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder.Build() -- this will result in a crash ("`System.InvalidOperationException: A suitable constructor for type 'Microsoft.Extensions.Options.UnnamedOptionsManager... could not be located.`") due to a bug in the SignalR client library. This is of course just one way of getting a crash to happen, feel free to try other ways (but some of them are caught properly).
5. When it crashes it will never show up in the issues section of the AppCenter dashboard. This is a major problem as native crashes invoked from the managed side **must** be caught in order for AppCenter.Crashes library to be useful.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Forms, Xamarin.iOS
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - .NET Standard 2.1
2. Which SDK version are you using?
    - 4.2.0
4. Which OS version did you experience the issue on?
    - iOS 14.5
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone X physical device

**Comment by AnastasiaKubova** [comment] 2021-06-04 07:14
Hi! Thanks for getting in touch with us!
I was able to reproduce this crash and I got all crash reports with this exception on the portal. 
Please make sure that the crash happens after the full start of App Center Crashes module. If crash happens before start of App Center Crashes then crash will not be catch.

**Comment by Tommigun1980** [comment] 2021-06-04 08:03
> Hi! Thanks for getting in touch with us!
> I was able to reproduce this crash and I got all crash reports with this exception on the portal.
> Please make sure that the crash happens after the full start of App Center Crashes module. If crash happens before start of App Center Crashes then crash will not be catch.

Hi and thanks for the reply! The crash does happen well after the app has inited.

My iOS AppDelegate initialises the AppCenter SDK at boot (as the first thing that happens). The managed part of my project invokes the SDK that now happens to crash. This happens after the user logs in, so the app has been working for a while before the crash happens.

I have historically gotten all other types of crashes, but this one just doesn't show up for me.

Can you think of any way to dig into this to see why they are not showing up?

Thank you so much!

**Comment by AnastasiaKubova** [comment] 2021-06-04 10:23
Could you please share the [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#adjust-the-log-level) with reproducing this issue?

**Comment by AnastasiaKubova** [comment] 2021-06-10 07:06
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Comment by Tommigun1980** [comment] 2021-06-16 02:18
@AnastasiaKubova Apologies for the belated reply. Please find the enclosed log here:
[AppCenterCrash.txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/6659784/AppCenterCrash.txt)

Could the error be that if the app is in a crash loop near the boot, it doesn't have enough time to upload the reports? When exactly does the SDK upload the reports, does `AppCenter.Start` start some asynchronous uploader?

Thank you.

**Comment by AnastasiaKubova** [comment] 2021-06-16 06:14
Hi, @Tommigun1980 ! Thanks for the additional info!
Based on your logs I see that the App Center SDK successfully saved the crash report, but the crash report will be sent only in the next start session. Could you please share logs after the crash also?

**Comment by Tommigun1980** [comment] 2021-06-16 06:22
> Hi, @Tommigun1980 ! Thanks for the additional info!
> Based on your logs I see that the App Center SDK successfully saved the crash report, but the crash report will be sent only in the next start session. Could you please share logs after the crash also?

That report is actually the "next" report, as the previous session ended with an identical crash (as the crash happens close to boot). In other words that particular log contains an identical crash report from the previous session.

Thank you.

**Comment by AnastasiaKubova** [comment] 2021-06-16 07:21
Looks like the App Center SDK doesn't have enough time for sending crash reports. Could you please try to crash your app in other place (for example via button, not immediately after App Center start) and let me know about the results?

**Comment by AnastasiaKubova** [comment] 2021-06-21 08:19
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.

**Closed by AnastasiaKubova** 2021-06-21 08:19 UTC
Labels: support
