### ISSUE TITLE
Xamarin.Mac is not compatible with App Store

### ISSUE THREAD

**Issue by ivanicin** [microsoft/appcenter-sdk-dotnet#1622] opened 2022-01-18 13:06 UTC
### **Description**

When I create the build for the App Store and submit it with Transporter, I get those errors:

```
ERROR ITMS-90260: "Bad Bundle Executable. You must include a valid CFBundleExecutable key in the nested bundle AppCenter [com.labsii.speechcentralmac.pkg/Payload/SpeechCentral.app/Contents/Frameworks/AppCenter.framework] property list file."

ERROR ITMS-90260: "Bad Bundle Executable. You must include a valid CFBundleExecutable key in the nested bundle AppCenterAnalytics [com.labsii.speechcentralmac.pkg/Payload/SpeechCentral.app/Contents/Frameworks/AppCenterAnalytics.framework] property list file."

ERROR ITMS-90260: "Bad Bundle Executable. You must include a valid CFBundleExecutable key in the nested bundle AppCenterCrashes [com.labsii.speechcentralmac.pkg/Payload/SpeechCentral.app/Contents/Frameworks/AppCenterCrashes.framework] property list file."

ERROR ITMS-90261: "Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle AppCenter [com.labsii.speechcentralmac.pkg/Payload/SpeechCentral.app/Contents/Frameworks/AppCenter.framework] property list file."

ERROR ITMS-90261: "Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle AppCenterAnalytics [com.labsii.speechcentralmac.pkg/Payload/SpeechCentral.app/Contents/Frameworks/AppCenterAnalytics.framework] property list file."

ERROR ITMS-90261: "Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle AppCenterCrashes [com.labsii.speechcentralmac.pkg/Payload/SpeechCentral.app/Contents/Frameworks/AppCenterCrashes.framework] property list file."
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Just build any Xamarin.Mac project for the App Store and submit it with Transporter
2.

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Mac
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - e.g. .NET standard 2.0.
2. Which SDK version are you using?
    - e.g. 4.5.0
4. Which OS version did you experience the issue on?
    - e.g. macOS 12.2
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. Mac Mini
6. What third party libraries are you using? 
    - example
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

**Comment by DmitriyKirakosyan** [comment] 2022-01-19 07:46
Hi @ivanicin , thank you for reporting this issue! Looks like a duplicate of https://github.com/microsoft/appcenter-sdk-dotnet/issues/1620.

**Comment by ivanicin** [comment] 2022-01-19 09:11
> Hi @ivanicin , thank you for reporting this issue! Looks like a duplicate of #1620.

This could be a duplicate but that issue has almost no info on how to reproduce and errors are different. 

Either way you have to test submitting to the App Store.

**Comment by AnastasiaKubova** [comment] 2022-01-19 10:10
Thanks for the clarification. Let's keep the discussion about this issue in one thread #1620. 
I'm closing the issue as a duplicate.

**Closed by AnastasiaKubova** 2022-01-19 10:10 UTC
Labels: support
