### ISSUE TITLE
Push does not work on some devices

### ISSUE THREAD

**Issue by JaeWLee** [Microsoft/AppCenter-SDK-DotNet#681] opened 2018-05-27 15:02 UTC
### **Description**

GetInstallIdAsync is working properly??

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.            if (AppCenter.GetInstallIdAsync().Result.HasValue)
                {
                    AppSettings.InstallId = AppCenter.GetInstallIdAsync().Result.Value;
                }

    First of all, this is my code and is working properly and is in Start method in App.cs
    and I got 'deviceId' like **"23f079b8-dba9-42d5-b31b-4bdcecfa7832"**
2. But when I send push through 'App Center Websites' for specif device,
   always say **"No Target"**

3. and **But, When I target all device, I can recieve push**

### **Details**

1. What is your app platform (Xamarin.Android or Xamarin.iOS or UWP)?
    - Xamarin.Forms on 2 platforms (Android, iOS).
2. If using Xamarin.Forms or if using portable/shared code to call our SDK APIs, are you using shared project, PCL code or .NET standard code for the application? Which .NET standard version or which PCL profile?
    - NET standard 2.0.
2. Which SDK version are you using?
    - 1.6.1
4. Which OS version did you experience the issue on?
    - Android 7.0
5. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Samsung A5 2016

**Comment by guperrot** [comment] 2018-05-29 21:36
Can you do the following:

* AppCenter.LogLevel = LogLevel.Verbose; // Before AppCenter.Start
* Print your own log with installId right after AppCenter.Start
* Launch app and extract all AppCenter logs and your own log and attach to this ticket.

**Comment by guperrot** [comment] 2018-06-04 18:18
Hey! 

We haven’t heard from you in a while, so I am going to go ahead and close this ticket. Should you still have any questions, you can write a message here & that will reopen the ticket; or if you prefer you can create a new ticket. Please don’t hesitate to contact us again.

Thanks for using App Center!

**Comment by jwallra** [comment] 2019-01-26 00:09
Hi @z0lberg - we'll need the same information from you that Guillaume requested [above](https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/681/#issuecomment-392953947).  Provide that information and we'd be happy to give you a hand!

**Comment by z0lberg** [comment] 2019-01-29 10:17
Hi! Here logs that you asked for (i hope so):
AppCenterID 0418d7b0-78fb-4bbd-8a80-7b4c7097a597
[logs.v1.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/2807151/logs.v1.txt)

**Comment by guperrot** [comment] 2019-01-29 19:11
Hi, there has been a confusion on what logs we were asking.
The AppCenter SDK logs its own messages to the Android debug console (Android logcat) with log tags starting with "AppCenter".

A typical SDK log session (when log level increased to verbose) looks like this:

```
```

**Comment by z0lberg** [comment] 2019-01-30 07:43
Hi! Here are yours new logs:
AppCenterID: 93e9e89f-fa27-41ff-80a4-2a78314ab0cf
[StartLog.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/2811397/StartLog.txt)

**Comment by guperrot** [comment] 2019-01-30 18:40
It looks like your installId is generated correctly on Android 9, can you elaborate what is your issue in details?

**Comment by z0lberg** [comment] 2019-01-31 08:06
Hi! The problem is while sending message to the device with android 9 i have no any results. I have tested that on two android 9 devices:  Sony G8341 and OnePlus6T.
The Sony device was updated from Android 8.1 to Android 9, and before update everything worked fine.
Now messaging works on older android version and on iOS.
I attached logs from android 9 device and screenshots from appcenter where i tried to send message. Please note, that if i try to send  message to all registered devices  i will got it in android 9 device.

AppCenterID: 629bba4f-1d25-4da1-bdbe-7f193a301120
[StartLog.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/2816203/StartLog.txt)
![android9_msg_send](https://user-images.githubusercontent.com/10826294/52040371-7e114200-2537-11e9-82d3-d4805c50705f.PNG)
![android9_msg](https://user-images.githubusercontent.com/10826294/52040372-7e114200-2537-11e9-950c-a8cf4c96cba7.PNG)
![android9_msg_confirmation](https://user-images.githubusercontent.com/10826294/52040373-7e114200-2537-11e9-9ae3-658483710e43.PNG)
![android9_msg_result](https://user-images.githubusercontent.com/10826294/52040374-7e114200-2537-11e9-94bf-2e4836375aec.PNG)
[Android9_msg_send.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/2816205/Android9_msg_send.txt)

**Comment by guperrot** [comment] 2019-01-31 19:35
Hi, I didn't realize it was a push issue since the mention was about the ability to retrieve installId using GetInstallIdAsync, I renamed the issue to avoid confusion.

In your case, it is because you are probably using the old integration for push, in the logs you shared we can see this:

```
01-31 08:45:17.881 W/AppCenterPush(12693): Firebase SDK is not available, using built in registration. For all the Android developers using App Center, there is a change coming where Firebase SDK is required to use Push Notifications. For Android P, its scheduled at the release date for the latest OS version. For all other versions of Android, it will be required after April 2019. Please follow the migration guide at https://aka.ms/acfba.
```

Android P is 9 and only Android 9 devices do no work for you so you probably need to follow the migration steps at https://aka.ms/acfba to make it work for all devices.

**Comment by z0lberg** [comment] 2019-02-01 14:39
I checked my manifest and it seems to be ok. You can browse it in attachment. I made a test project ant it works at my devices. Now i try to find any differences, but all things looks similar. May be some installed libraries in my main project affected firebase.
There is no error in app output like in first one.
If I find the solution I`ll write it here. 

[AndroidManifest.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/2822019/AndroidManifest.txt)

**Comment by guperrot** [comment] 2019-02-01 19:21
What about the google-service.json file, does it have the build action on it?

**Comment by z0lberg** [comment] 2019-02-04 14:16
Build action is GoogleServiceJson.

**Comment by guperrot** [comment] 2019-02-04 19:31
I noticed that you still use the SDK 1.6.1, you need to update App Center nugets for it to work Firebase push on Android 9 devices.

**Comment by guperrot** [comment] 2019-02-04 19:32
Can you please share the csproj file, and also package.config / project.json if you have that?

**Comment by z0lberg** [comment] 2019-02-05 13:16
Hi! Yes, here it, in attachment.
[Companion.Android.txt](https://github.com/Microsoft/AppCenter-SDK-DotNet/files/2832203/Companion.Android.txt)

**Comment by guperrot** [comment] 2019-02-05 19:47
Any chance the content of google-services.json would be invalid such as the package name of your app does not match?

**Comment by z0lberg** [comment] 2019-02-06 08:49
Hi! Thanks for your help! Now problem is solved. The root cause is that I used uppercase for part of package name in manifest and lower in google-services.json. When I made it all in lower case everything started work.

**Comment by guperrot** [comment] 2019-02-06 21:26
Glad the issue was fixed for you, and thanks for using AppCenter.

**Closed by guperrot** 2019-02-06 21:26 UTC
Labels: support
