### ISSUE TITLE
[Xamarin/iOS 15] App crashing in background after receiving a notification. Crash report blames App Center

### ISSUE THREAD

**Issue by JPZV** [microsoft/appcenter-sdk-dotnet#1555] opened 2021-08-16 22:48 UTC
### **Description**

I have an app that receives a lot of notifications, and I've implemented the AppCenter from the start of the development (a year ago, or even more), and this is the first time that I get a crash regarding with the AppCenter.
This app is in TestFlight right now and one of my tester updated his iPhone to iOS 15 (Beta 5), and he said that in the last week he has been receiving a lot of pop-ups from iOS saying that this app is crashing while in Background after receiving a notification. I saw his report (attached at the bottom) and the last five traces are about some calls from the App Center.

Sadly my iPhone (iPhone 6 with iOS 12.5.4) device has no support for iOS 15, so I cannot test it by myself and I cannot reproduce this error whatsoever.

### **Repro Steps**

From what my tester told me, and for what I can see in the report, these are the steps:

1. Install iOS 15 in an physical device
2. Create a Xamarin.Forms project
3. Follow the [Get Started](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin) guide using the [per-platform](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/xamarin#422-xamarinios) initialization.
4. Implement some Cloud Notification service ([FCM](https://firebase.google.com/docs/cloud-messaging) in my case)
5. Send a notification with the app closed from the recent apps (double tap in the Home button and swipe up the app)
6. Repeat step 5 until you receive an "app crashed" pop up from iOS

### **Details**

1. **Platform**: Xamarin.Forms on Android and iOS **(only happens on iOS 15)**
2. **.NET Standard version**: 2.0
3. **SDK Version**: 4.3.0
4. **OS Version with problems**: Only iOS 15
5. **Device**: iPhone 12 with iOS 15
6. **Third parties libraries**: (there're a lot, so I'll only put the most remarkable)
    a. **Xamarin.Forms.GoogleMaps** 3.3.0
    b. **Plugin.CloudFirestore** 4.1.0
    c. **Plugin.FirebaseAuth** 4.1.0
    d. **Xamarin.Forms** 5.0.0.2012
    e. **Xamarin.Essentials** 1.7.0
    f. **Xamarin.Firebase.iOS.CloudMessaging** 4.7.1
7. **Verbose logs**: Unable as the app _crashes_ while calling `AppCenter.Start()` in production (at least in my case)

### **Attachments**

[crash.log](https://github.com/microsoft/appcenter-sdk-dotnet/files/6995761/crash.log)
[feedback.log](https://github.com/microsoft/appcenter-sdk-dotnet/files/6995762/feedback.log)

**Note**: Our app (MyApp in crash.log) uses my company's library (MyLib). The AppCenter SDK is installed in the library. If you see the backtrace, you could see that the last call from our App/Lib before crashing was from `iOSProxy.cs:18` (called from `FinishedLaunching()`), which corresponds to `AppCenter.Start()`.

**Comment by DmitriyKirakosyan** [comment] 2021-08-17 16:10
Hi @JPZV 

Thank you for reporting this issue and providing detailed explanation with repro steps!

We will check it and get back to you with an update.

**Comment by ericbrunner** [comment] 2021-08-19 11:12
Hi, We have, I guess, the same error root cause. Here is the symbolicated crash Log from AppCenter. If you need more, please get back.

We use the latest stable nugets:

`Microsoft.AppCenter.Crash`       v.**4.3.0**
`Microsoft.AppCenter.Analytics`  v.**4.3.0**
Line 178 is the AppCenter.Start method:

**AppDelegate.cs:178**
![image](https://user-images.githubusercontent.com/6480047/130058738-909ad35b-f993-485e-94c7-1dafcd323a6b.png)

**Microsoft_AppCenter_iOS_Bindings_MSACWrapperSdk__ctor**_string_string_string_string_string_string
<unknown>, line 1
EXC_CRASH (SIGABRT)

**LAST EXCEPTION BACKTRACE**
CoreFoundation
0x1807de000 + 626780
libobjc.A.dylib
objc_exception_throw + 60 objc-exception.mm:565
CoreFoundation
0x1807de000 + 1531932
CoreFoundation
0x1807de000 + 189572
CoreFoundation
0x1807de000 + 185792
KommunalmesseiOS
wrapper_managed_to_native_ApiDefinition_Messaging_objc_msgSend_intptr_intptr_intptr_intptr_intptr_intptr_intptr_intptr <unknown>:1
KommunalmesseiOS
Microsoft_AppCenter_iOS_Bindings_MSACWrapperSdk__ctor_string_string_string_string_string_string <unknown>:1
KommunalmesseiOS
Microsoft_AppCenter_AppCenter_SetWrapperSdk <unknown>:1
KommunalmesseiOS
Microsoft_AppCenter_AppCenter_PlatformStart_string_System_Type__ <unknown>:1
KommunalmesseiOS
Microsoft_AppCenter_AppCenter_Start_string_System_Type__ <unknown>:1
KommunalmesseiOS
Kommunalmesse_iOS_AppDelegate_FinishedLaunching_UIKit_UIApplication_Foundation_NSDictionary (C:\VSTS\RiSKommunal\Development\mobileApp\Gem2GoX-XF3\Gem2Go\Kommunalmesse\Kommunalmesse.iOS\AppDelegate.cs:178)
KommunalmesseiOS
wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr
KommunalmesseiOS
mono_jit_runtime_invoke mini-runtime.c:3164
KommunalmesseiOS
mono_runtime_invoke_checked object.c:3052
KommunalmesseiOS
mono_runtime_invoke object.c:3107
KommunalmesseiOS
native_to_managed_trampoline_29(objc_object*, objc_selector*, _MonoMethod**, objc_object*, objc_object*, unsigned int) registrar.m:1355
KommunalmesseiOS
-[AppDelegate application:didFinishLaunchingWithOptions:] registrar.m:9434
UIKitCore
0x182c86000 + 3313936
UIKitCore
0x182c86000 + 5313640
UIKitCore
0x182c86000 + 5217748
UIKitCore
0x182c86000 + 3501816
UIKitCore
0x182c86000 + 1764460
UIKitCore
0x182c86000 + 2992244
UIKitCore
0x182c86000 + 4176772
UIKitCore
0x182c86000 + 6537416
UIKitCore
0x182c86000 + 6060356
UIKitCore
0x182c86000 + 1768048
UIKitCore
0x182c86000 + 2555468
UIKitCore
0x182c86000 + 1776000
UIKitCore
0x182c86000 + 2737436
UIKitCore
0x182c86000 + 7485032
UIKitCore
0x182c86000 + 1967564
UIKitCore
0x182c86000 + 2243560
UIKitCore
0x182c86000 + 3521980
UIKitCore
0x182c86000 + 2729948
FrontBoardServices
0x192268000 + 171568
FrontBoardServices
0x192268000 + 326892
FrontBoardServices
0x192268000 + 42692
FrontBoardServices
0x192268000 + 48388
libdispatch.dylib
_dispatch_client_callout + 20 object.m:560
libdispatch.dylib
_dispatch_block_invoke_direct + 264 queue.c:489
FrontBoardServices
0x192268000 + 49060
FrontBoardServices
0x192268000 + 46052
FrontBoardServices
0x192268000 + 63988
CoreFoundation
0x1807de000 + 766000
CoreFoundation
0x1807de000 + 834800
CoreFoundation
0x1807de000 + 24676
CoreFoundation
0x1807de000 + 47108
CoreFoundation
0x1807de000 + 127944
GraphicsServices
GSEventRunModal + 164 GSEvent.c:2200
UIKitCore
0x182c86000 + 5349336
UIKitCore
0x182c86000 + 2719516
KommunalmesseiOS
wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr
KommunalmesseiOS
UIApplication.cs:86
KommunalmesseiOS
UIApplication.cs:65
KommunalmesseiOS
Roemerland_iOS_Application_Main_string__ (C:\VSTS\RiSKommunal\Development\mobileApp\Gem2GoX-XF3\Gem2Go\Kommunalmesse\Kommunalmesse.iOS\Main.cs:12)
KommunalmesseiOS
wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr
KommunalmesseiOS
mono_jit_runtime_invoke mini-runtime.c:3164
KommunalmesseiOS
mono_runtime_invoke_checked object.c:3052
KommunalmesseiOS
mono_runtime_exec_main_checked object.c:0
KommunalmesseiOS
mono_jit_exec driver.c:1383
KommunalmesseiOS
xamarin_main monotouch-main.m:493
KommunalmesseiOS
main main.m:304
dyld
start + 520 dyldMain.cpp:876

**Comment by AnastasiaKubova** [comment] 2021-08-19 11:29
Hello, @ericbrunner ! Thanks for the additional information. 
Could you please  share some more details:
- What Xcode version do you use?
- What Visual Studio version do you use?
- Could you please share some more details about your Xamarin version (`Visual Studio` -> `About Visual Studio` -> `Show Details`)?
- Do you use linker settings in your project?
- Does this issue happen only in release or you can reproduce in debug mode also?

**Comment by DmitriyKirakosyan** [comment] 2021-08-19 11:53
I couldn't reproduce the issue on my mac, using VSfM 8.10.6/Xcode 13 and iOS 15 device
It would be really helpful if anyone could provide a demo app reproducing the bug.

**Comment by ericbrunner** [comment] 2021-08-19 13:59
We use VS 2019 (latest) and Xcode (latest) not the Xcode beta. It appeared on iPhone 12 Pro with iOS15 in Release mode.

**Comment by DmitriyKirakosyan** [comment] 2021-08-19 22:22
Hi @JPZV and @ericbrunner 

Do you have a chance to try to build your app on Mac machine with Visual Studio for Mac?
I'm suspecting that the issue is in new version of Xamarin components for VS2019.
Could you also try to create a new project with App Center SDK integrated and check if it also crashes on start?

**Comment by JPZV** [comment] 2021-08-19 22:50
Hi @DmitriyKirakosyan 

I cannot build from Windows (using Mac host) since half a year because it was very buggy, so from then I'm building directly from VSfM (copying all the source files and compiling/archiving them directly from the Mac)
Also, as I said before, I cannot reproduce the problem as I don't have iOS 15, but my tester (who has iOS 15 and who also sent me this issue) can actually open the App from the Home Screen, so the problem only comes when he receives a notification (and the code is exactly the same for both cases).



Sorry @AnastasiaKubova for the late answer. Here're my details:

- **Xcode version**: 12.5.1 (12E507)
- **Visual Studio (Windows)**: 16.11.1\*
- **Visual Studio (Mac)**: 8.10.7 (build 17)\*
- **Xamarin.iOS**: 14.20.0.24\*
- **Link (Debug)**: No
- **Link (Release)**: Only Frameworks SDKs
- **Does this issue happen only in release or you can reproduce in debug mode also?**: As I don't have a supported device, I can only reproduce it in release (Test Flight)

\*: May not be the same when I built the latest IPA for Test Flight. That IPA was built in July 30th. Now I'll create a new IPA as yesterday I updated everything and I'll let you know if my tester stills having this issue (I might say that he will)

**Comment by JPZV** [comment] 2021-08-20 00:12
Well, that didn't last. The app stills crashing with the same backtrace. I attached the new crash log as some things have changed, but the problem stills persist with everything up-to-date (i.e. with the versions that I listed above)

[crash.log](https://github.com/microsoft/appcenter-sdk-dotnet/files/7018258/crash.log)
[feedback.log](https://github.com/microsoft/appcenter-sdk-dotnet/files/7018259/feedback.log)

**Comment by ericbrunner** [comment] 2021-08-20 05:29
If you compare my [crash log](https://github.com/microsoft/appcenter-sdk-dotnet/files/7019284/report-2517729339978029999-8a61c125-3ce4-4fcc-a258-2464b3dd9344.txt) with @JPZV one's (crash.log) , you see we both crash at the same line.

In the constructor (.ctor) of Microsoft_AppCenter_iOS_Bindings_MSACWrapperSdk. 

![image](https://user-images.githubusercontent.com/6480047/130183422-f2d633d4-77f6-45eb-b5a0-5e584cd7fd09.png)

@AnastasiaKubova - Here're my details:

- Xcode version: 12.5.1 (12E507)
- Visual Studio (Windows): 16.11.1
- Visual Studio (Mac): 8.10.7 (build 17)
- Xamarin.iOS: 14.20.0.25
- Link (Debug): No
- Link (Release): Only Frameworks SDKs

- Does this issue happen only in release or you can reproduce in debug mode also?: A tester of us has iPhone 12 PRO with iOS 15 installen. He can only reproduce it in release (Test Flight).

**Comment by AnastasiaKubova** [comment] 2021-08-20 05:45
Hi @ericbrunner and @JPZV ! Thanks a lot for your details. 
Yes, @ericbrunner , you are right, your issues are similar and it really looks like a bug. We are trying to reproduce it on our side, but unfortunately all still work well for us. If you have a chance to share a sample project with repro of this issue it will be very helpful in investigating this bug.

**Comment by JPZV** [comment] 2021-08-20 18:56
Hi @AnastasiaKubova 

What kind of build logs do you need? and with what type of level?

About the verbose logs: If you mean about the AppCenter ones, I cannot share you those as the problem only occurs while calling `AppCenter.Start()` in release, and it doesn't log anything in the AppCenter's portal.
Now I'll try to enclose the `Start()` method in `Try-Catch` and write down any exception in a file. Maybe with that I could give you some sort of exception message or something that could help you to figure out what's going on.

**Comment by ericbrunner** [comment] 2021-08-20 22:17
Here are detailed crash logs with LogLevel = Verbose, VS2019 Windows Build.log and the TestFlight Crash.log enabled from my iPhone. 1st start of RELEASE App was ok. 2nd start crashed.

```
AppCenter.LogLevel = LogLevel.Verbose;
            AppCenter.Start("our key",
                typeof(Analytics), typeof(Crashes));
```

https://drive.google.com/drive/folders/1Nn9cuR0Fg5E4FTcr7DwnuCdUl5n5aCMe?usp=sharing

**Comment by JPZV** [comment] 2021-08-21 00:13
Finally I got a way more useful log about this issue (attached below). Hopefully this could help you to find what's going on.

I got this by enclosing the `AppCenter.Start()` method with `Try-Catch` and saving the Exception from `Catch` into a file.

[appcenter_crash.log](https://github.com/microsoft/appcenter-sdk-dotnet/files/7024529/appcenter_crash.log)

**Comment by ericbrunner** [comment] 2021-08-22 05:12
@JPZV After some extensive research I found that github isue with Xamarin.iOS / iOS 15: I changed the minimum OS version to be 14.0 in the info.plist. 
Currently I try that setting to set Minimum OS to 14 in info.plist. I will give some update if that workaround fixes the issue. If so, then it is really not an AppCenter SDK issue

**Comment by ericbrunner** [comment] 2021-08-22 05:41
Ok, I can confirm that the setting https://github.com/xamarin/xamarin-macios/issues/12427#issuecomment-900899606 works. So it's not an AppCenter issue.

**Comment by DmitriyKirakosyan** [comment] 2021-08-22 16:11
@JPZV Can you confirm that this fix works for you as well?
@ericbrunner, Could you check if enabling LLVM optimization also fixes the issue? See https://github.com/xamarin/xamarin-macios/issues/12427#issuecomment-903237843.

**Comment by ericbrunner** [comment] 2021-08-23 04:12
@DmitriyKirakosyan  In our 'Appstore' build config there is LLVM disabled.

**Comment by ericbrunner** [comment] 2021-08-23 05:40
Can confirm it works with [LLVM enabled](https://mallibone.com/post/custom-targets-llvm) in 'AppStore' | iPhone Release build and iOS Min Version still on 10.0.

**Comment by DmitriyKirakosyan** [comment] 2021-08-23 06:41
Thank you for confirming that this is not an SDK bug.
I'm closing issue but feel free to reopen it if you have any additional questions.

**Closed by DmitriyKirakosyan** 2021-08-23 06:41 UTC
Labels: not sdk issue

**Comment by JPZV** [comment] 2021-08-23 18:08
Sorry for the late answer.

@DmitriyKirakosyan it seems that enabling LLVM fixes this issue even with setting the minimum OS to 12.x (thanks @ericbrunner for the links! It helped a lot)

**Comment by sabrigo** [comment] 2021-10-18 18:57
thanks @JPZV , I will post it there, and can you share the details of the error?

Any idea on actual reported issue.  I tried with xcode 13 as well, and still the same issue i have.

**Comment by JPZV** [comment] 2021-10-20 20:30
@sabrigo You can check you NetStandard version by going to PCL -> Right Click -> Properties -> Application -> Target Framework. You can also check your [output verbosity](https://stackoverflow.com/a/45454885/4668642) ir order to get more details about that warning.

Also, for the main issue, as always, remember to Clean and Rebuild your solution, specially if you are using Visual Studio for Windows and a Mac Build Host.

Finally, as this issue is not related with AppCenter SDK, I'd recommend you to move this issue to your Sample App's [Repository](https://github.com/sabrigo/MobileApp). I'll be glad to help you there. Also, try to update your Sample App with the fixes that I mentioned before (Link and Libraries) so I can download what you did and check if it's fixed or not there.

**Comment by DP-Technology-LLC** [comment] 2022-03-11 14:57
I am running into the same error that @ericbrunner had mentioned in this thread.  
I have tried all the suggestions listed such as "set minimum iOS version to 14", etc.. but nothing works.

I have the most vanilla of projects that I can reproduce it on.  Visual Studio -> new Xamarin.Forms project (target iOS only) -> add AppCenter NuGet packages and reference them in both projects-> add one line of code in pcl's App.OnStart() for AppCenter.Start("ios=mysecret;" + "android=mysecret;",typeof(Analytics), typeof(Crashes));

https://github.com/DP-Technology-LLC/iOSXamarinForms-AppCenterErrorOnIOS.git


> [0:] An error occurred: 'Could not create an native instance of the type 'Microsoft.AppCenter.iOS.Bindings.MSACWrapperSdk': the native class hasn't been loaded.
> It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.'. Callstack: '  at Foundation.NSObject.InitializeObject (System.Boolean alloced) [0x0002e] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:327 
>   at Foundation.NSObject..ctor (Foundation.NSObjectFlag x) [0x0000d] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:184 
>   at Microsoft.AppCenter.iOS.Bindings.MSACWrapperSdk..ctor (System.String wrapperSdkVersion, System.String wrapperSdkName, System.String wrapperRuntimeVersion, System.String liveUpdateReleaseLabel, System.String liveUpdateDeploymentKey, System.String liveUpdatePackageHash) <0x110c03b08 + 0x0000a> in <57c9e239a4a24902835d9ec6d66cb938>:0 
>   at Microsoft.AppCenter.AppCenter.SetWrapperSdk () <0x110c02f40 + 0x00012> in <a55b22030e284d4993b4fa4dbd648997>:0 
>   at Microsoft.AppCenter.AppCenter.PlatformStart (System.String appSecret, System.Type[] services) <0x110c02c58 + 0x00002> in <a55b22030e284d4993b4fa4dbd648997>:0 
>   at Microsoft.AppCenter.AppCenter.Start (System.String appSecret, System.Type[] services) <0x110c02750 + 0x00008> in <a55b22030e284d4993b4fa4dbd648997>:0 


Visual Studio Community 2022 (Windows): 17.2.0 Preview 1.0
Xamarin.iOS: 15.7.0.163
Microsoft.AppCenter.Analytics: 4.5.0
Microsoft.AppCenter.Crashes: 4.5.0
Link (Debug): No
Link (Release): Only Frameworks SDKs
iPhone: iPhone 11 Pro Max
iOS: 15.3.1

Thanks.

**Comment by DmitriyKirakosyan** [comment] 2022-03-21 03:31
Hi @DP-Technology-LLC , sorry for the delayed reply.

Enabling LLVM optimization doest help either, right?

I just checked the thread [in xamarin repo](https://github.com/xamarin/xamarin-macios/issues/12427) and they say it was fixed on apple side in ios 15.7. You mentioned that you tested it on iOS 15.3.1, so can you try to reproduce the problem on iOS 15.7?

**Comment by DP-Technology-LLC** [comment] 2022-03-22 19:54
Hi @DmitriyKirakosyan , no worries on the turnaround.

That is correct, enabling LLVM optimization did not work.  Is there an iOS build that is 15.7?  I am pretty sure that the device I had borrowed was running the latest iOS at the time (15.3.1).  I was using Xamarin.iOS version 15.7, you wouldn't be referring to that, would you?

Thanks.

**Comment by DmitriyKirakosyan** [comment] 2022-03-23 04:03
Hi @DP-Technology-LLC , I meant iOS 15 beta 7. Actually the comment in xamarin thread is outdated, haven't noticed that when checked it before. So, your iOS version should be fine.

I'm still pretty confident that this is a xamarin.ios issue.
We will check your demo application with sdk versions you listed and let you know if we were able to reproduce the problem.
Meanwhile, you can try to downgrade xamarin ios sdk or try to build on another machine and see if it helps.

**Comment by sabrigo** [comment] 2022-03-23 04:07
The issue is mainly because of Apple chip MacBooks, I had solved it by compiling directly in the MacBook.

**Comment by DmitriyKirakosyan** [comment] 2022-03-23 06:50
Thanks @sabrigo!
@DP-Technology-LLC Could you try to build on a mac directly and see if it works?

**Comment by DP-Technology-LLC** [comment] 2022-03-24 00:55
I personally don't own any Apple products so I will need to reach out to someone who will kindly let me borrow their mac.  I will post as soon as I can but it may not be until next week.

Thanks.

**Comment by DmitriyKirakosyan** [comment] 2022-05-12 02:54
Hi @DP-Technology-LLC , does the problem still persist for you? Have you had a chance to check it on apple machine?
Have you tried reinstalling/updating Xamarin in Visual Studio or the VS itself?
May I ask you how you built your Xamarin.Forms iOS project without a mac machine?

**Comment by DP-Technology-LLC** [comment] 2022-05-16 13:06
Over the weekend I was able to work with someone with a Mac and who was willing to spend time with me on this issue.  We were able to launch the app on their Mac with an emulator.  I verified in AppCenter, the Analytics section did record one connection from an iOS simulator.

I have always tried to use the latest versions of packages and even Visual Studio itself.  I went to the Visual Studio 2022 Previews in hopes that this would be resolved with no luck.  I have not changed anything as I was trying to locate someone with a Mac.  Now that I have, I will try to get it to work using Windows one more time.  I will post with what I find.

Up until this point I have had access to a someone's iPhone.  I would connect their physical iPhone directly to my Windows machine.  I needed to install iTunes so that Visual Studio would identify the device as a valid device to deploy to.  I would compile and use Visual Studio's Hot Reload to deploy the app to the iPhone.  To use Hot Reload I had to pay for a subscription to Apple's Developer program, Visual Studio asks for credentials when deploying to the device.

**Comment by DmitriyKirakosyan** [comment] 2022-05-16 18:02
@DP-Technology-LLC thank you for sharing this information and confirming that it worked when it was built on a mac machine. Was it an intel mac or m1?
Have you tried to create an empty app with only AppCenter SDK nugets added to it and reproduce the problem on it?

Please keep us updated.

**Comment by DP-Technology-LLC** [comment] 2022-05-16 19:49
I am not sure about the specifics of the Mac, by the way he was talking I imagine it was not an intel mac.

I also saw in the limitations that there is no way to create an app bundle for publishing without a Mac.  So if I am going to have to use a Mac for that, then I guess it isn't the worst thing in the world not having AppCenter when doing actual development (don't really need it at that stage anyways).

Thanks for clarifying that this is what it is.

**Comment by sabrigo** [comment] 2022-05-16 19:56
It won’t work with windows directly :(


Regards
Sabri
________________________________

**Comment by sabrigo** [comment] 2022-10-11 06:54
No point in borrowing Mac, if you are going to be app developer on mac, I suggest you to get one. Get the basic version.


Regards
Sabri
________________________________
