### ISSUE TITLE
Foundation.MonoTouchException and NS Exceptions get swallowed by AppCenter Crashes

### ISSUE THREAD

**Issue by Cheesebaron** [Microsoft/AppCenter-SDK-DotNet#866] opened 2019-04-02 09:25 UTC
### **Description**

When AppCenter crashes are enabled in a Xamarin.iOS App, and the App throws NS Exception, such as NSInternalInconsistencyException when doing something wrong on a UITableView or messing up a constraint. These exceptions are in some of my Apps swallowed by AppCenter Crashes when they are not caught, and crash the App hard without leaving any Stack Trace or anything to go from in the Application Output.

Removing the AppCenter Crashes, initialization from the app. The App actually breaks on such exception on the line or in Main.cs, with a stack trace so you have something useful to fix you app from.

I've tried reproducing in a fresh Xamarin.iOS project, here the app breaks as expected. However, no crashes are reported into AppCenter Crashes.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Set up AppCenter Crashes
2. Make app throw a NS exception

### **Details**

1. Xamarin.iOS
2. NET standard 2.0.
2. Which SDK version are you using? 1.9.0 also tried 1.14.0
4. Which OS version did you experience the issue on? iOS 12.1
5. What device version did you see this error on?  Were you using an emulator or a physical device? iPhone Simulator and various iPhone Devices
6. What third party libraries are you using? Loads... can be reproduced without any but AppCenter too...
7. Please enable verbose logging for your app using `AppCenter.LogLevel = LogLevel.Verbose` before your call to `AppCenter.Start(...)` and include the logs here:

```
2019-04-02 11:21:27.058574+0200 TableViewCrash[11129:8967577] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=11129
2019-04-02 11:21:27.059097+0200 TableViewCrash[11129:8967577] SecTaskCopyDebugDescription: TableViewCrash[11129]/0#-1 LF=0
2019-04-02 11:21:27.077773+0200 TableViewCrash[11129:8967577] libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform.
2019-04-02 11:21:27.236851+0200 TableViewCrash[11129:8967577] [AppCenter] VERBOSE: +[MSAppDelegateForwarder addTraceBlock:]_block_invoke_2/113 Start buffering traces.
2019-04-02 11:21:27.237848+0200 TableViewCrash[11129:8967577] [AppCenter] DEBUG: +[MSAppDelegateForwarder load]_block_invoke/57 Application delegate forwarder is enabled. It may use swizzling.
2019-04-02 11:21:27.238641+0200 TableViewCrash[11129:8967577] [AppCenter] VERBOSE: +[MSAppDelegateForwarder flushTraceBuffer]/436 Stop buffering traces, flushed.
2019-04-02 11:21:27.266018+0200 TableViewCrash[11129:8967577] [AppCenterXamarin] DEBUG: +[MSWrapperLogger MSWrapperLog:tag:level:]/9 No named identifier found in appSecret; using as-is
2019-04-02 11:21:27.328521+0200 TableViewCrash[11129:8967577] [AppCenter] DEBUG: -[MSSessionContext init]/40 1 session(s) in the history.
2019-04-02 11:21:27.333261+0200 TableViewCrash[11129:8967577] [AppCenter] VERBOSE: -[MSSessionContext setSessionId:]/71 Stored new session with id:(null) and timestamp: 2019-04-02 09:21:27 +0000.
2019-04-02 11:21:27.335299+0200 TableViewCrash[11129:8967577] [AppCenter] INFO: -[MSHttpIngestion networkStateChanged]/418 Internet connection is up.
2019-04-02 11:21:27.336259+0200 TableViewCrash[11129:8967577] [AppCenter] INFO: -[MSHttpIngestion networkStateChanged]/418 Internet connection is up.
2019-04-02 11:21:27.344255+0200 TableViewCrash[11129:8967577] [AppCenter] INFO: -[MSAppCenter configureWithAppSecret:transmissionTargetToken:fromApplication:]/274 App Center SDK configured successfully.
2019-04-02 11:21:27.344580+0200 TableViewCrash[11129:8967577] [AppCenter] VERBOSE: -[MSAppCenter start:withServices:fromApplication:]/298 Start services MSCrashes from an application
2019-04-02 11:21:27.351623+0200 TableViewCrash[11129:8967577] [AppCenterCrashes] DEBUG: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/598 EnableUncaughtExceptionHandler is set to NO, we're running in a Xamarin runtime.
2019-04-02 11:21:27.371597+0200 TableViewCrash[11129:8967577] [AppCenterCrashes] DEBUG: -[MSCrashes configureCrashReporterWithUncaughtExceptionHandlerEnabled:]/651 Exception handler successfully initialized but it has not been registered due to the wrapper SDK.
2019-04-02 11:21:27.375051+0200 TableViewCrash[11129:8967577] [AppCenter] VERBOSE: -[MSSessionContext clearSessionHistory]/95 Cleared old sessions.
2019-04-02 11:21:27.375277+0200 TableViewCrash[11129:8967577] [AppCenterCrashes] INFO: -[MSCrashes applyEnabledState:]/356 Crashes service has been enabled.
2019-04-02 11:21:27.385507+0200 TableViewCrash[11129:8967577] [AppCenterCrashes] VERBOSE: -[MSCrashes startWithChannelGroup:appSecret:transmissionTargetToken:fromApplication:]/397 Started crash service.
2019-04-02 11:21:27.394291+0200 TableViewCrash[11129:8967586] [Client] Remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.394291+0200 TableViewCrash[11129:8967577] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.394589+0200 TableViewCrash[11129:8967586] [Client] Remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.394594+0200 TableViewCrash[11129:8967577] [NetworkInfo] Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.394725+0200 TableViewCrash[11129:8967621] [Client] Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.395157+0200 TableViewCrash[11129:8967621] [Client] Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.395394+0200 TableViewCrash[11129:8967586] [Client] Remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.395588+0200 TableViewCrash[11129:8967621] [Client] Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.395600+0200 TableViewCrash[11129:8967577] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.396044+0200 TableViewCrash[11129:8967577] [NetworkInfo] Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.396761+0200 TableViewCrash[11129:8967577] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.396813+0200 TableViewCrash[11129:8967621] [Client] Remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.397240+0200 TableViewCrash[11129:8967586] [Client] Sending selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.397415+0200 TableViewCrash[11129:8967577] [NetworkInfo] Descriptors query returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-04-02 11:21:27.399971+0200 TableViewCrash[11129:8967577] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:withInternalId:]/463 Storing a log to Crashes Buffer: (sid: (null), type: startService)
2019-04-02 11:21:27.400197+0200 TableViewCrash[11129:8967577] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didPrepareLog:withInternalId:]/475 Found an empty buffer position.
2019-04-02 11:21:27.400465+0200 TableViewCrash[11129:8967586] [AppCenter] DEBUG: -[MSChannelUnitDefault enqueueItem:]_block_invoke/195 Saving log, type: startService.
2019-04-02 11:21:27.404792+0200 TableViewCrash[11129:8967586] [AppCenterCrashes] VERBOSE: -[MSCrashes channel:didCompleteEnqueueingLog:withInternalId:]/528 Deleting a log from buffer with id C6FA06FB-DBB5-499E-B136-E159FB940B92
2019-04-02 11:21:28.809372+0200 TableViewCrash[11129:8967577] dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
2019-04-02 11:21:28.809555+0200 TableViewCrash[11129:8967577] dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
2019-04-02 11:21:28.809672+0200 TableViewCrash[11129:8967577] dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
2019-04-02 11:21:30.406847+0200 TableViewCrash[11129:8967586] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/278 Sending 1/1 log, group Id: AppCenter, batch Id: 6C854AC9-C3B1-4F0B-A30F-C3C5401ED415, session Id: (null), payload:
{
  "device" : {
    "appVersion" : "1.0",
    "appBuild" : "1.0",
    "osName" : "iOS",
    "timeZoneOffset" : 120,
    "wrapperSdkVersion" : "1.9.0",
    "osVersion" : "12.1",
    "wrapperRuntimeVersion" : "11.2.0",
    "locale" : "en_US",
    "wrapperSdkName" : "appcenter.xamarin",
    "appNamespace" : "com.companyname.TableViewCrash",
    "osBuild" : "17G5019",
    "sdkName" : "appcenter.ios",
    "oemName" : "Apple",
    "sdkVersion" : "1.9.0",
    "model" : "x86_64",
    "screenSize" : "1334x750"
  },
  "timestamp" : "2019-04-02T09:21:27.386Z",
  "type" : "startService",
  "services" : [
    "Crashes"
  ]
}
2019-04-02 11:21:30.407646+0200 TableViewCrash[11129:8967586] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:appSecret:]/94 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2019-04-02 11:21:30.407953+0200 TableViewCrash[11129:8967586] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:appSecret:]/96 Headers: Install-ID = 0A43ED66-3B69-4D37-8009-12F091CCEE99, App-Secret = ****************************0784f17b, Content-Type = application/json
2019-04-02 11:21:30.426365+0200 TableViewCrash[11129:8967585] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=11129
2019-04-02 11:21:30.426614+0200 TableViewCrash[11129:8967585] SecTaskCopyDebugDescription: TableViewCrash[11129]/0#-1 LF=0
2019-04-02 11:21:30.869664+0200 TableViewCrash[11129:8967621] [AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/302 HTTP response received with status code=200 and payload=CorrelationId: 7d0532ed-496b-44c3-b8d6-ce6b5f181aef  ReasonCode: Success
2019-04-02 11:21:30.870137+0200 TableViewCrash[11129:8967621] [AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/359 Removed call id:6C854AC9-C3B1-4F0B-A30F-C3C5401ED415 from pending calls:{
}
2019-04-02 11:21:30.870230+0200 TableViewCrash[11129:8967585] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/308 Log(s) sent with success, batch Id:6C854AC9-C3B1-4F0B-A30F-C3C5401ED415.
2019-04-02 11:21:30.875138+0200 TableViewCrash[11129:8967585] [AppCenter] VERBOSE: -[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:]/324 Deletion of log(s) by id with value(s) '11' succeeded.
2019-04-02 11:21:32.837702+0200 TableViewCrash[11129:8967577] [AppCenterCrashes] ERROR: +[MSWrapperLogger MSWrapperLog:tag:level:]/9 Unhandled Exception:
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSRangeException Reason: -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:]: row (0) beyond bounds (0) for section (0).
Native stack trace:
	0   CoreFoundation                      0x000000011a25f1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000011b1c5735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011a25f015 +[NSException raise:format:] + 197
	3   UIKitCore                           0x0000000121737636 -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:] + 1828
	4   UIKitCore                           0x0000000121738322 -[UITableView _scrollToRowAtIndexPath:atScrollPosition:animated:usingPresentationValues:] + 146
	5   UIKitCore                           0x00000001217381ab -[UITableView scrollToRowAtIndexPath:atScrollPosition:animated:] + 123
	6   TableViewCrash                      0x000000010c9cf449 xamarin_dyn_objc_msgSend + 217
	7   ???                                 0x000000013fd2abc8 0x0 + 5365738440

  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:411 
  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/runtime/Delegates.generated.cs:128 
  at (wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr_Int64_bool(intptr,intptr,intptr,long,bool)
  at UIKit.UITableView.ScrollToRow (Foundation.NSIndexPath indexPath, UIKit.UITableViewScrollPosition atScrollPosition, System.Boolean animated) [0x00023] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/UIKit/UITableView.g.cs:908 
  at TableViewCrash.ViewController+<>c__DisplayClass2_0.<ViewDidLoad>b__2 (System.Object s, System.EventArgs e) [0x00001] in /Users/tci/Projects/TableViewCrash/TableViewCrash/ViewController.cs:66 
  at TableViewCrash.ViewModel.Clear () [0x0000d] in /Users/tci/Projects/TableViewCrash/TableViewCrash/ViewController.cs:154 
  at TableViewCrash.ViewController+<>c__DisplayClass2_0.<ViewDidLoad>b__0 (System.Object s, System.EventArgs e) [0x00001] in /Users/tci/Projects/TableViewCrash/TableViewCrash/ViewController.cs:52 
  at UIKit.UIBarButtonItem+Callback.Call (Foundation.NSObject sender) [0x0000d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/UIKit/UIBarButtonItem.cs:30 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr_Int64_bool(intptr,intptr,intptr,long,bool)
  at UIKit.UITableView.ScrollToRow (Foundation.NSIndexPath indexPath, UIKit.UITableViewScrollPosition atScrollPosition, System.Boolean animated) [0x00023] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/UIKit/UITableView.g.cs:908 
  at TableViewCrash.ViewController+<>c__DisplayClass2_0.<ViewDidLoad>b__2 (System.Object s, System.EventArgs e) [0x00001] in /Users/tci/Projects/TableViewCrash/TableViewCrash/ViewController.cs:66 
  at TableViewCrash.ViewModel.Clear () [0x0000d] in /Users/tci/Projects/TableViewCrash/TableViewCrash/ViewController.cs:154 
  at TableViewCrash.ViewController+<>c__DisplayClass2_0.<ViewDidLoad>b__0 (System.Object s, System.EventArgs e) [0x00001] in /Users/tci/Projects/TableViewCrash/TableViewCrash/ViewController.cs:52 
  at UIKit.UIBarButtonItem+Callback.Call (Foundation.NSObject sender) [0x0000d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/UIKit/UIBarButtonItem.cs:30 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/UIKit/UIApplication.cs:63 
  at TableViewCrash.Application.Main (System.String[] args) [0x00001] in /Users/tci/Projects/TableViewCrash/TableViewCrash/Main.cs:12 	0   CoreFoundation                      0x000000011a25f1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000011b1c5735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011a25f015 +[NSException raise:format:] + 197
	3   UIKitCore                           0x0000000121737636 -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:] + 1828
	4   UIKitCore                           0x0000000121738322 -[UITableView _scrollToRowAtIndexPath:atScrollPosition:animated:usingPresentationValues:] + 146
	5   UIKitCore                           0x00000001217381ab -[UITableView scrollToRowAtIndexPath:atScrollPosition:animated:] + 123
	6   TableViewCrash                      0x000000010c9cf449 xamarin_dyn_objc_msgSend + 217
	7   ???                                 0x000000013fd2abc8 0x0 + 5365738440
2019-04-02 11:21:32.942021+0200 TableViewCrash[11129:8967577] [AppCenterCrashes] WARNING: +[MSWrapperLogger MSWrapperLog:tag:level:]/9 Cannot serialize Foundation.MonoTouchException exception for client side inspection. If you want to have access to the exception in the callbacks, please add a Serializable attribute and a deserialization constructor to the exception class.
2019-04-02 11:21:32.953324+0200 TableViewCrash[11129:8967577] [AppCenterCrashes] INFO: +[MSWrapperLogger MSWrapperLog:tag:level:]/9 Saving wrapper exception...
2019-04-02 11:21:32.956463+0200 TableViewCrash[11129:8967577] [AppCenterCrashes] INFO: +[MSWrapperLogger MSWrapperLog:tag:level:]/9 Saved wrapper exception.
2019-04-02 11:21:32.958829+0200 TableViewCrash[11129:8967577] Unhandled managed exception:
Objective-C exception thrown.  Name: NSRangeException Reason: -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:]: row (0) beyond bounds (0) for section (0).
Native stack trace:
	0   CoreFoundation                      0x000000011a25f1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000011b1c5735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011a25f015 +[NSException raise:format:] + 197
	3   UIKitCore                           0x0000000121737636 -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:] + 1828
	4   UIKitCore                           0x0000000121738322 -[UITableView _scrollToRowAtIndexPath:atScrollPosition:animated:usingPresentationValues:] + 146
	5   UIKitCore                           0x00000001217381ab -[UITableView scrollToRowAtIndexPath:atScrollPosition:animated:] + 123
	6   TableViewCrash                      0x000000010c9cf449 xamarin_dyn_objc_msgSend + 217
	7   ???                                 0x000000013fd2abc8 0x0 + 5365738440
 (Foundation.MonoTouchException)
  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:411 
  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/runtime/Delegates.generated.cs:128 
  at (wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr_Int64_bool(intptr,intptr,intptr,long,bool)
  at UIKit.UITableView.ScrollToRow (Foundation.NSIndexPath indexPath, UIKit.UITableViewScrollPosition atScrollPosition, System.Boolean animated) [0x00023] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/UIKit/UITableView.g.cs:908 
  at TableViewCrash.ViewController+<>c__DisplayClass2_0.<ViewDidLoad>b__2 (System.Object s, System.EventArgs e) [0x00001] in /Users/tci/Projects/TableViewCrash/TableViewCrash/ViewController.cs:66 
  at TableViewCrash.ViewModel.Clear () [0x0000d] in /Users/tci/Projects/TableViewCrash/TableViewCrash/ViewController.cs:154 
  at TableViewCrash.ViewController+<>c__DisplayClass2_0.<ViewDidLoad>b__0 (System.Object s, System.EventArgs e) [0x00001] in /Users/tci/Projects/TableViewCrash/TableViewCrash/ViewController.cs:52 
  at UIKit.UIBarButtonItem+Callback.Call (Foundation.NSObject sender) [0x0000d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/UIKit/UIBarButtonItem.cs:30 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr_Int64_bool(intptr,intptr,intptr,long,bool)
  at UIKit.UITableView.ScrollToRow (Foundation.NSIndexPath indexPath, UIKit.UITableViewScrollPosition atScrollPosition, System.Boolean animated) [0x00023] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/UIKit/UITableView.g.cs:908 
  at TableViewCrash.ViewController+<>c__DisplayClass2_0.<ViewDidLoad>b__2 (System.Object s, System.EventArgs e) [0x00001] in /Users/tci/Projects/TableViewCrash/TableViewCrash/ViewController.cs:66 
  at TableViewCrash.ViewModel.Clear () [0x0000d] in /Users/tci/Projects/TableViewCrash/TableViewCrash/ViewController.cs:154 
  at TableViewCrash.ViewController+<>c__DisplayClass2_0.<ViewDidLoad>b__0 (System.Object s, System.EventArgs e) [0x00001] in /Users/tci/Projects/TableViewCrash/TableViewCrash/ViewController.cs:52 
  at UIKit.UIBarButtonItem+Callback.Call (Foundation.NSObject sender) [0x0000d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/UIKit/UIBarButtonItem.cs:30 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.6.0.25/src/Xamarin.iOS/UIKit/UIApplication.cs:63 
  at TableViewCrash.Application.Main (System.String[] args) [0x00001] in /Users/tci/Projects/TableViewCrash/TableViewCrash/Main.cs:12
```

The line: 

```
WARNING: +[MSWrapperLogger MSWrapperLog:tag:level:]/9 Cannot serialize Foundation.MonoTouchException exception for client side inspection. If you want to have access to the exception in the callbacks, please add a Serializable attribute and a deserialization constructor to the exception class.
```

Seems like we are back to a regression with #752 #524

**Comment by guperrot** [comment] 2019-04-05 17:35
(The webhook failed notifying on this one)

**Comment by annakocheshkova** [comment] 2019-04-08 15:06
Hi @Cheesebaron! We've tried to reproduce your issue.
We made our Demo App crash with a simple NSErrorException. However, we see that it gets sent to App Center. Can you provide detailed steps of how you crashed your app?

Thanks!

**Comment by Cheesebaron** [comment] 2019-04-09 08:35
@annakocheshkova I tried repro this in a fresh App too, but couldn't. However, in our production App this happens very consistently. I cannot narrow down what causes the issue though. Will dig into this further.

**Comment by annakocheshkova** [comment] 2019-04-09 09:18
Thanks @Cheesebaron! Maybe there is some kind of crash that does not gets processed. If we could determine what kind it is, it will help us a lot.

**Comment by dtrabo** [comment] 2019-04-18 10:33
Hey @Cheesebaron ! 
We haven’t heard from you in a while, so I close this issue. If you have any more questions or details of the issue please let us know.

**Closed by dtrabo** 2019-04-18 10:33 UTC

**Comment by chotaling1** [comment] 2022-06-08 20:39
Hello @guperrot, @dtrabo, @annakocheshkova,

I know this is a closed issue, but we have run into a similar issue as the one brought up here, so I was hoping it could be re-opened. In the reproduce case above, you used an NSErrorException. However, this is not a valid reproduction case, because NSErrorException is derived from the Exception, while NSException is not. Since NSErrorException derives from Exception, it will behave normally in a try-catch. If you need another way to reproduce the issue, you can use the "Broken Code" example found in this Exception Marshaling doc:

https://docs.microsoft.com/en-us/xamarin/ios/platform/exception-marshaling

Run this code in the AppDelegate for a valid reproduce case:

> try {
     var dict = new NSMutableDictionary();
     dict.LowlevelSetObject(IntPtr.Zero, IntPtr.Zero);
}
catch (Exception ex)
{
    Console.Write(ex);
}

AppCenter.Start(typeof(Crashes))
try {
     var dict = new NSMutableDictionary();
     dict.LowlevelSetObject(IntPtr.Zero, IntPtr.Zero);
}
catch (Exception ex)
{
    Console.Write(ex);
}


In the above example, the two try-catches are identical. The first try catch will result in a caught exception and will be allowed to continue, while the second one will result in a crash.

**Comment by DmitriyKirakosyan** [comment] 2022-06-09 05:02
Hi @chotaling1 thank you for reporting!
This is a duplicate of https://github.com/microsoft/appcenter-sdk-dotnet/issues/1639. Please follow the progress there.
