### ISSUE TITLE
iOS Build fails because of AppCenterCrashes.a

### ISSUE THREAD

**Issue by omghb** [microsoft/appcenter-sdk-dotnet#1767] opened 2023-11-21 13:11 UTC
Used versions:
- MAUI 8.0.3
- Microsoft.AppCenter.Crashes 5.0.3

Build for iOS
- Physical device: ✔️ Works correct
- Simulator (e.g. iPhone 15 Pro): ❌ Fails

Build error message:
```
4>Tool xcrun execution finished (exit code = 1).
4>ld: in /Users/dev/Library/Caches/Xamarin/mtbs/builds/.../obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/AppCenterCrashes.a(MSACErrorReport.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/dev/Library/Caches/Xamarin/mtbs/builds/.../obj/Debug/net8.0-ios/iossimulator-arm64/linker-cache/AppCenterCrashes.a'
4>clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jokvist** [comment] 2023-11-21 21:34
Workaround found here: https://github.com/microsoft/appcenter-sdk-dotnet/issues/1755

Add to project file:
```
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-ios|AnyCPU'">
    <ForceSimulatorX64ArchitectureInIDE>true</ForceSimulatorX64ArchitectureInIDE>
</PropertyGroup>
```
Delete obj and bin folder and delete the build cache folder (/Users/_username_/Library/Caches/Xamarin/mtbs/builds/_yourproject_) on the Mac agent.

**Comment by DmitriyKirakosyan** [comment] 2023-11-22 09:23
Closing as duplicate of https://github.com/microsoft/appcenter-sdk-dotnet/issues/1755.
@omghb please follow the original issue.

**Closed by DmitriyKirakosyan** 2023-11-22 09:23 UTC
Labels: support
