### ISSUE TITLE
Support Manual Proxy Server Configuration

### ISSUE THREAD

**Issue by cmiles** [microsoft/appcenter-sdk-dotnet#624] opened 2018-03-20 01:06 UTC
Please consider supporting manual Proxy Server configuration.

I tried setting up AppCenter in a new Xamarin.Forms for a new internal company application but quickly failed because our general policy is that all network traffic should run thru the Proxy Server. Obviously we can make exceptions but getting an exception made to bypass the Proxy is both a huge hurdle and slightly strange in this case since I am not sure there is any reason that AppCenter's traffic couldn't run thru our Proxy except lack of support? (Maybe there is? My experience is minimal since this is the first time I have tried to use AppCenter - perhaps this is not true for Distribute or other features that I didn't test outside our network and Proxy Server exceptions would have to be made anyway?)

I am willing to try to do some coding on this if it would help and deliberately said 'manual' Proxy Server configuration because the issue of auto-detecting proxy settings correctly on every platform/version seems daunting (I have never written code to do proxy auto-setup so that is just a guess but I would be amazed if it turned out to be a simple issue!) - but not sure if this feature has enough interest especially since at a glance I suspect what may be more complex than actually setting up/using the Proxy settings if present would be deciding where/how they are set?

**Comment by dominik-weber** [comment] 2018-08-14 09:20
+1 for this feature :) could this possibly be implemented in a way so we can supply our own HttpMessageHandler instance?

**Comment by elamalani** [comment] 2018-08-14 20:08
@cmiles Thanks for trying out App Center. We don't plan to support manual proxy server configuration in the short term but I'll keep this thread open for visibility and notify you once we decide to support it.

**Comment by albertosilva** [comment] 2019-01-16 20:32
In scenarios where mobile devices and computers are not supposed to have any kind of public internet access, like warehouse mobile devices, production floor devices, IoT, .., it would help to have the option to install a relay service on a computer on the same network, that would forward the diagnostics/analytics to the App Center servers, and configure those devices to use an alternative url… wonder if the AppCenter.SetLogUrl method is there for such situations...

**Comment by clpolet** [comment] 2019-01-17 19:57
@albertosilva what you are saying should be possible. Giving the SDK a different endpoint to send the traffic to is what [AppCenter.SetLogUrl](https://github.com/Microsoft/AppCenter-SDK-DotNet/blob/7f9c39f18a7aaf2b4ea38a6e81ab98c4a03b485e/SDK/AppCenter/Microsoft.AppCenter.Shared/AppCenter.cs#L115) is doing. That should work for Analytics, Push and Crashes but Distribute is using different endpoints you'll also have to use [Distribute.SetInstallUrl](https://github.com/Microsoft/AppCenter-SDK-DotNet/blob/7f9c39f18a7aaf2b4ea38a6e81ab98c4a03b485e/SDK/AppCenterDistribute/Microsoft.AppCenter.Distribute.Shared/Distribute.cs#L32) and [Distribute.SetApiUrl](https://github.com/Microsoft/AppCenter-SDK-DotNet/blob/7f9c39f18a7aaf2b4ea38a6e81ab98c4a03b485e/SDK/AppCenterDistribute/Microsoft.AppCenter.Distribute.Shared/Distribute.cs#L41).

**Comment by clpolet** [comment] 2019-01-17 21:56
@cmiles I am just curious, what's your definition of a "manual Proxy Server configuration"?

**Comment by dominik-weber** [comment] 2019-01-18 09:52
@clpolet maybe I can jump in here. Our app supports Managed App Config, a feature which let's enterprises configure the proxy server and other settings via their MDM solution. In our app we have code that basically reads these settings and routes the traffic accordingly, for example by modifying the HttpClientHandler.Proxy property.
I didn't find a way to forward these settings to AppCenter, so the proxy configuration is bypassed by AppCenter.

If we had a way to tell AppCenter which proxy to use, this would make this scenario possible and also allow the proxy to be "hardcoded" which I think @cmiles was going for.

**Comment by cmiles** [comment] 2019-01-22 16:55
Thanks @dominik-weber - your reply sums things up nicely! Glad there is at least a little continued interest here!

@clpolet  Just to say it in my own words by "manual Proxy Server configuration" I meant configuring all of the proxy settings for AppCenter 'manually' as values in the AppCenter setup code ("hardcoded" proxy values).

My idea at the top is not for AppCenter to try to 'auto-detect' anything related to proxy settings - rather my target is use in an internal app where the proxy value is set by company policy, for use only on company devices, not user-configurable, is known by the code and would be easy to specify in code to AppCenter on startup.

BTW - The Set...Url methods above are interesting - I didn't find those when I was originally testing AppCenter, I will have to review those and make sure I am not overlooking an easy alternative way to solve the problem...

**Comment by clpolet** [comment] 2019-01-22 17:40
@cmiles and @dominik-weber thanks for your answers it certainly helps to understand the use case. So basically "hardcoding" the proxy configuration would mean passing the proxy configuration to the App Center SDK so it can setup the HTTP calls to contact the App Center servers through the configured proxy. The proxy server in this case doesn't need to know about App Center directly since the configuration is done client side. Is that right? 
As opposed to using the `Set...Url` APIs of the SDK since these APIs are just "swaping" the endpoints in the HTTP call which means the proxy server has to be configured to reroute the calls received from the devices to the App Center servers.

**Comment by dominik-weber** [comment] 2019-01-22 19:08
@clpolet you're exactly right. I haven't looked at the set..url methods myself, however I imagine it would be quite hard to convince our customers to change the proxy configuration to reroute the traffic as you described.
On the other hand if we had the option to simply configure the host+port of a standard http proxy server this would make the configuration much easier.

**Comment by juanxeondev** [comment] 2019-05-27 16:33
@clpolet currently I have similar situation like @albertosilva where the android devices is only connected to the internal network and cannot access the internet. Do you have any guidance on how to use the SetLogUrl method? which AppCenter URL endpoint that the reverse proxy/gateway will need to redirect the log to?

I've tried using NGINX as reverse proxy for Application Insight endpoint address and it works. I believe AppCenter should work similarly.

Any advise is very much appreciated. 

Thank you

**Comment by Jamminroot** [comment] 2019-05-30 09:48
Sorry for a delayed response, @juanxeondev.
There is no documentation for this method on the docs.microsoft.com.

SetLogUrl will end up in platform-specific SetLogUrl private method, which will set default log url;
Default log url is "https://in.appcenter.ms" (without quotes).
You can check out those lines of code for more details (Using android repo as reference):

[DEFAULT_LOG_URL](https://github.com/microsoft/appcenter-sdk-android/blob/de4f11b795d5405baad3bd374a93582df8a30f51/sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/AppCenterIngestion.java#L38)
[SetLogUrl()](https://github.com/microsoft/appcenter-sdk-android/blob/de4f11b795d5405baad3bd374a93582df8a30f51/sdk/appcenter/src/main/java/com/microsoft/appcenter/ingestion/AppCenterIngestion.java#L87)
[SetInstanceLogUrl()](https://github.com/microsoft/appcenter-sdk-android/blob/0811dc2035c5acf0581751280efb2a28660fcc3e/sdk/appcenter/src/main/java/com/microsoft/appcenter/AppCenter.java#L494)

**Comment by juanxeondev** [comment] 2019-06-09 16:18
Thank you so much Jamminroot and Guperrot. I have successfully setup the app center to use NGINX as the reverse proxy. For information, I just need to use the http://nginx:port and set the Nginx to route to https://in.appcenter.ms. The /logs?api-version=1.0.0 is not required.

Thanks

**Comment by guperrot** [comment] 2019-06-10 18:41
Just to add a detail if others read, `/logs?api-version=1.0.0` must be omitted indeed when calling `AppCenter.SetLogURL('http://nginx:port')`.

This is the proxy that needs to be aware that the SDK adds this path to the log url automatically. SDK will call `'http://nginx:port/logs?api-version=1.0.0` and the proxy has to call `https://in.appcenter.ms/logs?api-version=1.0.0` as a result.

**Comment by DmitriyKirakosyan** [comment] 2021-12-01 13:09
Since the issue is resolved by using `AppCenter.SetLogURL` API, I'm closing this issue, but feel free to reopen if you have additional questions.

**Closed by DmitriyKirakosyan** 2021-12-01 13:09 UTC
Labels: feature request
