### ISSUE TITLE
Use winsqlite3 on UWP

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/appcenter-sdk-dotnet#1460] opened 2020-11-06 11:59 UTC
**Describe the solution you'd like**
It would be great if UWP package could use `SQLitePCLRaw.bundle_winsqlite3` rather than `SQLitePCLRaw.bundle_green`, to save some space in the final package.

**Comment by Sergio0694** [comment] 2020-11-06 12:00
For reference, duplicate of https://github.com/microsoft/appcenter/issues/2039.

**Closed** 2020-11-06 12:00 UTC
Labels: feature request
