### ISSUE TITLE
Crash service in xamarin forms ios app says enabled, but doesnt log anything in the App center

### ISSUE THREAD

**Issue by PaulsonMac** [microsoft/appcenter-sdk-dotnet#974] opened 2019-06-18 16:58 UTC
### **Description**

I have configured everything correctly, tried generating test crash and crash from code, both crashes the app, but the crash is not logged in App center. But, the analytics works fine.

### **Repro Steps**

NA

### **Details**

Xamarin.Forms on 2 platforms (Android, iOS ).
NET standard 2.0.
SDK version 2.0.0
iOS 12+
Enabled verbose logging, where can I find the logs?

### One kind request:
Kiindly ellaborate more on troubleshooting for crashes in the official documentation, particularly for iOS (Xamarin.Forms iOS in my case) Thanks

**Comment by PaulsonMac** [comment] 2019-06-18 16:59
Shows SDK started successfully, Returns true for Crashes.IsEnabledAsync

**Comment by PaulsonMac** [comment] 2019-06-18 17:14
Crashes.HasCrashedInLastSessionAsync() returns false though previous launch crashed

**Comment by annakocheshkova** [comment] 2019-06-18 17:24
Hi there @PaulsonMac ! You can find verbose logs in an `Output ` window. 
Can you share a snippet of your code related to App Center?
I want to see in what order you make those calls.

**Comment by annakocheshkova** [comment] 2019-06-18 17:26
Can you specify ehat exactly is missing in the docs? We'll be glad to make them better and more clear.

**Comment by PaulsonMac** [comment] 2019-06-18 17:34
@annakocheshkova, thanks for your reply!

My app Center initialisation code:

AppCenter.LogLevel = LogLevel.Verbose;
App enter.Start("ios=...;android=..",
This kind configuration works me as well:

using Microsoft.AppCenter.Crashes;

AppCenter.Start(Settings.AppCenterConfigString, typeof(Analytics), typeof(Crashes) ):

**Comment by PaulsonMac** [comment] 2019-06-18 17:37
>>Can you specify what exactly is missing in the docs? We'll be glad to make them better and more clear.

Pleaae include additional information on Troubleshooting options in the official docs.

**Comment by annakocheshkova** [comment] 2019-06-18 17:39
Thank you for sharing that @PaulsonMac. I will need all of the code (including the calls to `IsEnabledAsync` and `HasCrashedInLastSessionAsync`).
What additional info would you like to have?

**Comment by PaulsonMac** [comment] 2019-06-18 18:50
I just copied the code as it is from the App center SDK docs for xamarin.

bool didAppCrash = await Crashes.HasCrashedInLastSessionAsync();
Console.WriteLine(didAppCrash);
bool isEnabled = await Crashes.IsEnabledAsync();
Console.WriteLine(isEnabled);

Test crash/code crash (throw NotImplementrdException) was generated in the content page's OnAppearing overrided method

**Comment by annakocheshkova** [comment] 2019-06-18 19:01
@PaulsonMac I think you need to move the `HasCrashedInLastSessionAsync` call after the `IsEnabledAsync` call, just to be sure that you are calling this API only after the SDK is initialized.
Could you please try that and get back to me?

**Comment by guperrot** [comment] 2019-06-18 19:03
The order does not matter between those 2 APIs.
However both APIs must be called after `AppCenter.Start`.

To get logs on VS for Mac:

* First, crash the app by launching it from device launch menu (not via VS for Mac so that debugger is not attached, capturing crashes with debugger will not work most of the time).
* After app has crashed, launch a debugging session, AppCenter logs will appear in Application output (look for AppCenter logs).

**Comment by PaulsonMac** [comment] 2019-06-19 09:53
@guperrot , I couldn't reply in-time, sorry for that..! Those 2 APIs are called way before the AppCenter.Start() was called.. I knew that crash occurred in debugging session wouldnot work from one of your little-unobvious docs, so I did crashed from my own device launcher only, still I didnt get any crashes in the AppCenter..

**Comment by annakocheshkova** [comment] 2019-06-19 09:56
@PaulsonMac you should call them after `AppCenter.start()`.
Can you find the verbose logs now? If yes, please send them.
Thanks you!

**Comment by PaulsonMac** [comment] 2019-06-19 10:01
Sorry @annakocheshkova, I had mistakenly commented it.. AppCenter.Start() was called way before those 2 APIs were called, so was the test crash/code crash. Basically, AppCenter.Start() is called in App.xaml.cs and other API calls/crashes were called at Content page's OnAppearing method as I told earlier.. I'll try to get those logs following the 2-steps that @guperrot  gave... Thanks very much

**Comment by annakocheshkova** [comment] 2019-06-19 10:05
Thank you, I will wait for you logs.

> I knew that crash occurred in debugging session wouldnot work from one of your docs (this was little unobvious)
Indeed, we don't make this information explicit in the docs. I will go ahead and fix that.

**Comment by PaulsonMac** [comment] 2019-06-19 10:10
@annakocheshkova, sorry, for some reason I couldnt find the output window logging anything like as it would do normally in the debug-Output window, I tried to follow those 2 steps that @guperrot suggested to get the logs.. I am using Visual Studio 2017 Community edition (version 15.9.11) for Windows.

**Comment by PaulsonMac** [comment] 2019-06-19 10:11
I'll restart VS and try again..

**Comment by PaulsonMac** [comment] 2019-06-19 10:13
I have doubt whether App Center would report handled exceptions/crashes..?
Anyways, I tried for both handled and unhandled exception the previous day..!

**Comment by annakocheshkova** [comment] 2019-06-19 10:13
@PaulsonMac Here's this window: 
![image](https://user-images.githubusercontent.com/34677812/59757251-0ba9c000-9294-11e9-9f43-9e7860248547.png)

**Comment by annakocheshkova** [comment] 2019-06-19 10:14
Yes, App Center SDK for Xamarin has `TrackError` method for handled exceptions.

**Comment by PaulsonMac** [comment] 2019-06-19 10:25
> Yes, App Center SDK for Xamarin has `TrackError` method for handled exceptions.

That's great.. Thank you!

Regarding the output window, I had exactly looked in the same window.. After restart I can see some verbose logs now

[Verbose_Logs_AppCenter_iOS.txt](https://github.com/microsoft/appcenter-sdk-dotnet/files/3305649/Verbose_Logs_AppCenter_iOS.txt)

Please check the verbose logs and kindly assist. Thanks

**Comment by PaulsonMac** [comment] 2019-06-19 10:29
These attached Verbose_Logs_AppCenter_iOS.txt was copied from the Output Window after I
1. Crashed the app without attaching debugging session while launcing the app. I launched it from my device.
2. Then, collected the verbose logs by running the iOS project as @guperrot asked me to do.. Thanks

**Comment by annakocheshkova** [comment] 2019-06-19 10:42
Thank you @PaulsonMac. I looked at the logs, seems like I need some more info.
First, could you send me your code related to Crashes? Let's focus on unhandled exceptions first - how do you crash the app and what other calls to Crashes do you make?
Also, could you check if there were no more logs after the logs that you sent earlier in `Verbose_Logs_AppCenter_iOS.txt` ?

**Comment by PaulsonMac** [comment] 2019-06-19 10:46
protected override void OnAppearing()
{
//tried GenerateTestCrash once and throw new NotImplementedException() once as follows - both didnt work
//Tried without try/catch - Unhandled exception
Microsoft.AppCenter.Crashes.Crashes.GenerateTestCrash();
throw new NotImplementedException();
 ..
base.OnAppearing();
....
}

**Comment by PaulsonMac** [comment] 2019-06-19 11:00
> Also, could you check if there were no more logs after the logs that you sent earlier in Verbose_Logs_AppCenter_iOS.txt ?

There are few more logs titled App center verbose but I think this alone must be enough to look into.., whether it is sending the crash log details to App Center or not..

**Comment by PaulsonMac** [comment] 2019-06-19 11:07
TrackError is getting logged fine.. Very confusing why crashes alone is not working

**Comment by PaulsonMac** [comment] 2019-06-19 11:09
Please upgrade App Center service, lot of my time is getting consumed over this one problem.
Kindly look into this asap. Thanks

**Comment by PaulsonMac** [comment] 2019-06-19 11:25
I need to intialize AppCenter.Start() only in App.xaml.cs OnStart() method for a Xamarin.Forms project right? Do I also need to call AppCenter.Start() in AppDelegate.cs ..?

**Comment by annakocheshkova** [comment] 2019-06-19 11:26
Ok thank you. I have a question: Did you add AppCenter nuget packages to both portable and iOS project?
So far seems like you do everything correct.
Just to make this clear: you have a Xamarin.Forms app, in the shared part in `App.xaml.cs` you start the SDK.
In the shared part, in another page `ContentPage.xaml.cs` in `OnAppearing()` you crash the app.
You don't make other calls to crashes except `HasCrashesInLastSession` or `IsEnabled`.
Everything correct?

**Comment by PaulsonMac** [comment] 2019-06-19 11:31
Yes @annakocheshkova, everything is correct, except that the API calls - HasCrashesInLastSession or IsEnabled are called in another content page's OnAppearing method that gets displayed before the content page where I crash the app.
I have included Nuget packages in both portable and iOS projects - all 3 packages i.e., Microsoft.AppCenter, Microsoft.AppCenter.Analytics and Microsoft.AppCenter.Crashes (All are v2.0.0). Just checked in my projects

**Comment by PaulsonMac** [comment] 2019-06-19 11:37
But the package is not specified in packages.config file found in the root of the .NET standard project (It is not a portable project). Anyways, not all 3rd party packages are there except very few only are found.

**Another doubt:**
My iOS app is targeting iOS version 10.1 as min iOS version for the app, is that any problem, though analytics, trackerror are working..??

**Comment by PaulsonMac** [comment] 2019-06-19 11:41
Sometime back i.e., one month ago, one crash has been logged - maybe I called AppCenter.Start() in AppDelegate.cs at that time. I dont remember.. Anyways I'll check that now..!

**Comment by annakocheshkova** [comment] 2019-06-19 11:48
@PaulsonMac seems everything correct, I just created the app and checked that this scenario works. We support 10.1 iOS version.
If you have a `Xamarin.Forms` app (with App Center apps for each platform), then the `Start()` call should be inside `App.xaml.cs`.
If you have a `Xamarin.iOS` project, then the call to `Start()` should be inside `AppDelegate.cs`.

What do you mean by
>not all 3rd party packages are there except very few only are found ?

Also, you said earlier that the verbose logs you sent are after the Start call.
> //NOTE: Immediately after AppCenter.Start() is called, the below logs are logged

Could you send me the full logs? I need two files:
1. Full set of logs from the moment you started the app til the moment it crashes. 
You can capture those logs:
- From Simulator: open **Debug** > **Open System log...**
- From Device: open **XCode** > **Devices and Simulators** > choose the device > **Open console**
2. Full set of logs from the second start (after the crash).

**Comment by annakocheshkova** [comment] 2019-06-19 11:53
What I mean is these packages should be listed in `packages.config` inside `Xamarin.Forms` **and** `Xamarin.Forms.iOS`

**Comment by PaulsonMac** [comment] 2019-06-19 11:55
> 
What I mean is these packages should be listed in packages.config inside Xamarin.Forms and Xamarin.Forms.iOS

Ok, but Analytics package is also not referred right..? How is that part working?
Are you sure..?

**Comment by annakocheshkova** [comment] 2019-06-19 12:01
If you have added the packages via **Add NuGet Packages** and then installed, they should automatically be added inside `packages.config`. If they are missing from `packages.config`, then it's very likely that something is wrong.

**Comment by PaulsonMac** [comment] 2019-06-19 12:06
Ok, @annakocheshkova... can I add that entry there,..? But in the manage nuget packages window - the app center packages appear as installed for both .NET standard (shared) and iOS project

**Comment by PaulsonMac** [comment] 2019-06-19 12:11
This is the shared project's .csproj file content, it looks like the packages are included correctly. Maybe there was an issue when migrating from packagereference to packages.config, I'm not sure...

```
<ItemGroup>
  <PackageReference Include="Microsoft.AppCenter" Version="2.0.0" />
  <PackageReference Include="Microsoft.AppCenter.Analytics" Version="2.0.0" />
  <PackageReference Include="Microsoft.AppCenter.Crashes" Version="2.0.0" />
</ItemGroup>
```

**Comment by annakocheshkova** [comment] 2019-06-19 12:38
@PaulsonMac I just created an empty project and configured it like you said - all works well.
So I guess there's been some misunderstanding.
Let me share my project with you, maybe you have something different:
[TestFormsApp.zip](https://github.com/microsoft/appcenter-sdk-dotnet/files/3306091/TestFormsApp.zip)

**Comment by PaulsonMac** [comment] 2019-06-19 12:40
@annakocheshkova , thanks very much.. I'll review this and let you know..

**Comment by annakocheshkova** [comment] 2019-06-19 12:42
Since the issue is not reproduced - the only way I could help is by looking at the full set of logs (as described [in this comment](https://github.com/microsoft/appcenter-sdk-dotnet/issues/974#issuecomment-503526998)) or if you send a test application where it can be reproduced.

**Comment by annakocheshkova** [comment] 2019-06-19 12:45
@PaulsonMac You are saying that migrated from **PackageReference** to `packages.config`, could you describe how you did that? I guess you're right, something wrong went at that point.

**Comment by PaulsonMac** [comment] 2019-06-19 12:52
I think I did it like this - https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference

**Comment by annakocheshkova** [comment] 2019-06-19 13:28
Ok @PaulsonMac  so you migrated from `packages.config` to `PacageReference`. Did crashes work before migration or they never worked for you?

**Comment by PaulsonMac** [comment] 2019-06-19 13:29
As I told earlier, only one crash has occurred 3 weeks ago that is logged in AppCenter.. But I dont have that backup nor remember how that was configured..

**Comment by PaulsonMac** [comment] 2019-06-19 13:31
I ony have packages.config now...

**Comment by annakocheshkova** [comment] 2019-06-19 13:32
@PaulsonMac I don't think I get it. You are saying that you migrated from packages.config to PackageReference - why would you have a `packages.config`  then?

**Comment by PaulsonMac** [comment] 2019-06-19 13:47
Sorry, again - I have mistyped.. Please ignore..
All I have now is packages.config - I have migrated to packages.config then..

**Comment by annakocheshkova** [comment] 2019-06-19 13:52
Then you should have packages listed in the `packages.config` file, not in `PackageReference` like you said [in this comment](https://github.com/microsoft/appcenter-sdk-dotnet/issues/974/#issuecomment-503534151)... 
Although I still don't get why would one migrate **to** `packages.config` cause `PackageReference` is the new format.

**Comment by annakocheshkova** [comment] 2019-06-19 13:53
Maybe it makes sense to create a new project and try integrating everything from the start?

**Comment by annakocheshkova** [comment] 2019-06-19 13:56
You also said earlier that you use **Visual Studio 2017 Community edition (version 15.9.11) for Windows** - is that correct? How did you build iOS app without the mac machine?

**Comment by PaulsonMac** [comment] 2019-06-19 13:57
Yeah, I have a macbook that I pair the Windows PC with..

**Comment by PaulsonMac** [comment] 2019-06-19 13:58
I hope you know about xamarin.

**Comment by annakocheshkova** [comment] 2019-06-19 13:59
Ok got it. Just wanted to make sure. If you have mac machine it's fine.

**Comment by PaulsonMac** [comment] 2019-06-19 14:00
If incase you dont know, this is how pair to mac works for building iOS Apps in windows (Xamarin.Forms) - https://docs.microsoft.com/en-gb/xamarin/ios/get-started/installation/windows/connecting-to-mac/

**Comment by PaulsonMac** [comment] 2019-06-19 14:02
But, I dont think it is a problem with packages.config as there is no analytics package also, but for some reason that is working fine.. Anyways I'll try resolving that...

**Comment by annakocheshkova** [comment] 2019-06-19 14:06
Thank you, yes I know about that - just wanted to clarify.
To sum up - I see that there's some confusion around package reference format. 

To eliminate that, I suggest you try configuring from an empty project. If the issue keeps reproducing - please send me the test application where it can be reproduced.

Or if you want me to be able to investigate further, I will need you to provide the verbose logs using the instructions as I sent earlier. 
Thanks!

**Comment by PaulsonMac** [comment] 2019-06-19 15:46
@annakocheshkova, I can get the test crash logged when I try with a new small test project..

**Comment by guperrot** [comment] 2019-06-20 01:36
The verbose logs that were uploaded earlier do not correspond to what normally happen during start.
Can you try sharing them again without filtering any? (for the non working project).

Can you also share the following files:
* the csproj file for the .NET standard portable code
* the package.config or project.json file for the .NET standard portable code (if any)
* the csproj file for the iOS specific project
* the package.config or project.json file for the .NET standard portable code (if any)

Can you also make sure:

* Your application does not keep crashing during startup, as we would never have time to send any logs.
* That the VS debugger is not attached when crashing. To capture the crash, the app must be run by being launched directly from the device or simulator, without VS. Only at restarting after crash you can use VS debugger.
* That the verbose logs you share are the logs after the restart after crash, not the logs before crashing.
* That you do not have HockeyApp SDK or any other crash reporting SDK in the app.

**Comment by dtrabo** [comment] 2019-07-05 14:04
Hey @PaulsonMac ! 
We haven’t heard from you in a while, do you have any more questions? If so, please let us know.  
Thanks for using App Center!

**Comment by PaulsonMac** [comment] 2020-12-03 15:55
> Crashes.HasCrashedInLastSessionAsync() returns false though previous launch crashed

**Linker option :** _Don't link_ reports the crashes fine. 

If the linker option is SDK Framework only, the HasCrashedInLastSessionAsync is returning false. But "Don't link" returns true as expected.

Below is how I checked whether crash occurred in last session:
` bool isCrashedLast = await Crashes.HasCrashedInLastSessionAsync();`

This is in the latest version 4.0.0.

But from my experience, App Center is doing good than Crashlytics.

**Comment by PaulsonMac** [comment] 2020-12-03 16:10
But the problem is that I couldn't take a release build with Linker option : _Don't Link_ (throws build error saying the size is too large). We're blocked from going live.

@annakocheshkova, @guperrot ,  @dtrabo - can any of you suggest any quick workaround that you maybe knowing.

**Comment by Jamminroot** [comment] 2020-12-04 08:48
Hey, @PaulsonMac, sorry for a delay in response.

For now It's hard to tell what actually is going on - but I assume the problem lies within optimization enabled by `-linksdk` flag.
Can this be reproduced in a sample project with nothing else but SDK?
Opening a bug as suggested in [xamarin documentation ](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/linker?tabs=windows#dont-link) would be a good starting point.

Also, what exactly is the build time error you get with `Don't Link`?

**Comment by PaulsonMac** [comment] 2020-12-05 17:19
Thank you @Jamminroot ! I've attached the error that I got while building with the Don't Link option

```
The assembly 'Xamarin.iOS.dll' can't be AOT-compiled for 32-bit architectures because the native code is too big for the 32-bit ARM architecture.	
can not encode offset '0x100CE34' in resulting scattered relocation.
```

**Comment by PaulsonMac** [comment] 2020-12-05 17:34
> Can this be reproduced in a sample project with nothing else but SDK?

No.

**Comment by PaulsonMac** [comment] 2020-12-07 17:31
@Jamminroot / App Center Team , is there anything you guys can help?

**Comment by olmisa** [comment] 2020-12-07 19:09
Hello @PaulsonMac ,
as I understand there are several possible ways:
1. Use linker
2. Select in "Supported architectures" ARM64
3. Maybe the old version of the Xamarin.iOS was used.

Also, I don't see that this error relates to our SDK.
Thanks

**Comment by AnastasiaKubova** [comment] 2020-12-10 06:56
We haven’t heard from you in a while so I’m closing this issue.
Feel free to reopen this issue if it isn’t resolved or you have additional questions.

**Closed by AnastasiaKubova** 2020-12-10 06:56 UTC
Labels: support

**Comment by shreekantmundhe** [comment] 2021-03-19 12:09
I tried to start AppCenter in App.xaml.cs file and then in OnCreate() of Xamarin.Android I did crash  using Crash.GenerateTestCrash(). But Crash logs are not reflecting in AppCenter, I checkde one things is that , My crahs in OnCreate() happen before AppCenter starts in App.xaml.cs.

Can someone please let me know this behavior.
